PhyStar: quadpack::Quadpack< T_fun, T_param, T_real > Struct Template Reference
quadpack::Quadpack< T_fun, T_param, T_real > Struct Template Reference
#include <quadpack.hpp>
Static Public Member Functions
static T_real gk15 (T_fun f, T_param user_data[], T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real gk21 (T_fun f, T_param user_data[], T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real gk31 (T_fun f, T_param user_data[], T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real gk41 (T_fun f, T_param user_data[], T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real gk51 (T_fun f, T_param user_data[], T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real gk61 (T_fun f, T_param user_data[], T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real gk15i (T_fun f, T_param user_data[], T_real boun, int inf, T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real gk15w (T_fun f, T_param user_data[], qwgt< T_real > w, T_real p1, T_real p2, T_real p3, T_real p4, int kp, T_real a, T_real b, T_real *abserr, T_real *resabs, T_real *resasc)
static T_real qext (int *n, T_real epstab[], T_real *abserr, T_real res3la[], int *nres)
static void qsort (int limit, int last, int *maxerr, T_real *ermax, T_real elist[], int iord[], int *nrmax)
static T_real qagi (T_fun f, T_param user_data[], T_real bound, int inf, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static T_real qags (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static T_real qagp (T_fun f, T_param user_data[], T_real a, T_real b, int npts2, T_real *points, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static T_real qng (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static T_real qag (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, int irule, T_real *abserr, int *neval, int *ier)
static T_real qage (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, int irule, T_real *abserr, int *neval, int *ier, int *last)
static void qcheb (T_real *x, T_real *fval, T_real *cheb12, T_real *cheb24)
static T_real qc25o (T_fun f, T_param user_data[], T_real a, T_real b, T_real omega, int integr, int nrmom, int maxp1, int ksave, T_real *abserr, int *neval, T_real *resabs, T_real *resasc, int *momcom, T_real **chebmo)
static T_real qfour (T_fun f, T_param user_data[], T_real a, T_real b, T_real omega, int integr, T_real epsabs, T_real epsrel, int icall, int maxp1, T_real *abserr, int *neval, int *ier, int *momcom, T_real **chebmo)
static T_real qawfe (T_fun f, T_param user_data[], T_real a, T_real omega, int integr, T_real epsabs, int limlst, int maxp1, T_real *abserr, int *neval, int *ier, T_real *rslst, T_real *erlist, int *ierlst, T_real **chebmo)
static T_real qawf (T_fun f, T_param user_data[], T_real a, T_real omega, int integr, T_real epsabs, T_real *abserr, int *neval, int *ier)
static T_real qawo (T_fun f, T_param user_data[], T_real a, T_real b, T_real omega, int integr, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static T_real qaws (T_fun f, T_param user_data[], T_real a, T_real b, T_real alfa, T_real beta, int wgtfunc, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static T_real qawse (T_fun f, T_param user_data[], T_real a, T_real b, T_real alfa, T_real beta, int wgtfunc, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static void qmomo (T_real alfa, T_real beta, T_real ri[], T_real rj[], T_real rg[], T_real rh[], int wgtfunc)
static T_real qc25s (T_fun f, T_param user_data[], T_real a, T_real b, T_real bl, T_real br, T_real alfa, T_real beta, T_real ri[], T_real rj[], T_real rg[], T_real rh[], T_real *abserr, T_real *resasc, int wgtfunc, int *nev)
static T_real qc25c (T_fun f, T_param user_data[], T_real a, T_real b, T_real c, T_real *abserr, int *krul, int *neval)
static T_real qawc (T_fun f, T_param user_data[], T_real a, T_real b, T_real c, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
static T_real qawce (T_fun f, T_param user_data[], T_real a, T_real b, T_real c, T_real epsabs, T_real epsrel, T_real *abserr, int *neval, int *ier)
Member Function Documentation
gk15()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk15 (T_fun f, T_param user_data[], T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
gk15i()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk15i (T_fun f, T_param user_data[], T_real boun, int inf, T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
gk15w()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk15w (T_fun f, T_param user_data[], qwgt< T_real > w, T_real p1, T_real p2, T_real p3, T_real p4, int kp, T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, blockelm::kp, quadpack::max(), quadpack::min(), and quadpack::uflow.
gk21()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk21 (T_fun f, T_param user_data[], T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
gk31()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk31 (T_fun f, T_param user_data[], T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
gk41()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk41 (T_fun f, T_param user_data[], T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
gk51()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk51 (T_fun f, T_param user_data[], T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
gk61()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::gk61 (T_fun f, T_param user_data[], T_real a, T_real b, T_real * abserr, T_real * resabs, T_real * resasc) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
qag()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qag (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, int irule, T_real * abserr, int * neval, int * ier) static
qage()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qage (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, int irule, T_real * abserr, int * neval, int * ier, int * last) static
References quadpack::epmach, quadpack::LIMIT, quadpack::max(), and quadpack::uflow.
qagi()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qagi (T_fun f, T_param user_data[], T_real bound, int inf, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
References quadpack::epmach, quadpack::FALSE, quadpack::LIMIT, quadpack::max(), quadpack::oflow, quadpack::TRUE, and quadpack::uflow.
qagp()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qagp (T_fun f, T_param user_data[], T_real a, T_real b, int npts2, T_real * points, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
References quadpack::epmach, quadpack::FALSE, quadpack::LIMIT, quadpack::max(), quadpack::min(), quadpack::oflow, quadpack::TRUE, and quadpack::uflow.
qags()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qags (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
References quadpack::epmach, quadpack::FALSE, quadpack::LIMIT, quadpack::max(), quadpack::oflow, quadpack::TRUE, and quadpack::uflow.
qawc()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qawc (T_fun f, T_param user_data[], T_real a, T_real b, T_real c, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
qawce()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qawce (T_fun f, T_param user_data[], T_real a, T_real b, T_real c, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
References quadpack::epmach, quadpack::LIMIT, quadpack::max(), quadpack::min(), and quadpack::uflow.
qawf()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qawf (T_fun f, T_param user_data[], T_real a, T_real omega, int integr, T_real epsabs, T_real * abserr, int * neval, int * ier) static
References quadpack::MAXP1.
qawfe()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qawfe (T_fun f, T_param user_data[], T_real a, T_real omega, int integr, T_real epsabs, int limlst, int maxp1, T_real * abserr, int * neval, int * ier, T_real * rslst, T_real * erlist, int * ierlst, T_real ** chebmo) static
References quadpack::COSINE, compgeo::eps, quadpack::max(), quadpack::P, quadpack::Pi, quadpack::SINE, and quadpack::uflow.
qawo()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qawo (T_fun f, T_param user_data[], T_real a, T_real b, T_real omega, int integr, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
References quadpack::MAXP1.
qaws()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qaws (T_fun f, T_param user_data[], T_real a, T_real b, T_real alfa, T_real beta, int wgtfunc, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
qawse()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qawse (T_fun f, T_param user_data[], T_real a, T_real b, T_real alfa, T_real beta, int wgtfunc, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
References quadpack::epmach, quadpack::LIMIT, quadpack::max(), and quadpack::uflow.
qc25c()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qc25c (T_fun f, T_param user_data[], T_real a, T_real b, T_real c, T_real * abserr, int * krul, int * neval) static
References blockelm::kp.
qc25o()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qc25o (T_fun f, T_param user_data[], T_real a, T_real b, T_real omega, int integr, int nrmom, int maxp1, int ksave, T_real * abserr, int * neval, T_real * resabs, T_real * resasc, int * momcom, T_real ** chebmo) static
References quadpack::NMAC, quadpack::oflow, and quadpack::SINE.
qc25s()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qc25s (T_fun f, T_param user_data[], T_real a, T_real b, T_real bl, T_real br, T_real alfa, T_real beta, T_real ri[], T_real rj[], T_real rg[], T_real rh[], T_real * abserr, T_real * resasc, int wgtfunc, int * nev) static
qcheb()
template<typename T_fun , typename T_param , realtype T_real> void quadpack::Quadpack< T_fun, T_param, T_real >::qcheb (T_real * x, T_real * fval, T_real * cheb12, T_real * cheb24) static
qext()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qext (int * n, T_real epstab[], T_real * abserr, T_real res3la[], int * nres) static
References quadpack::epmach, quadpack::max(), and quadpack::oflow.
qfour()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qfour (T_fun f, T_param user_data[], T_real a, T_real b, T_real omega, int integr, T_real epsabs, T_real epsrel, int icall, int maxp1, T_real * abserr, int * neval, int * ier, int * momcom, T_real ** chebmo) static
References quadpack::COSINE, quadpack::epmach, quadpack::FALSE, quadpack::LIMIT, quadpack::max(), quadpack::oflow, quadpack::SINE, quadpack::TRUE, and quadpack::uflow.
qmomo()
template<typename T_fun , typename T_param , realtype T_real> void quadpack::Quadpack< T_fun, T_param, T_real >::qmomo (T_real alfa, T_real beta, T_real ri[], T_real rj[], T_real rg[], T_real rh[], int wgtfunc) static
qng()
template<typename T_fun , typename T_param , realtype T_real> T_real quadpack::Quadpack< T_fun, T_param, T_real >::qng (T_fun f, T_param user_data[], T_real a, T_real b, T_real epsabs, T_real epsrel, T_real * abserr, int * neval, int * ier) static
References quadpack::epmach, quadpack::max(), quadpack::min(), and quadpack::uflow.
qsort()
template<typename T_fun , typename T_param , realtype T_real> void quadpack::Quadpack< T_fun, T_param, T_real >::qsort (int limit, int last, int * maxerr, T_real * ermax, T_real elist[], int iord[], int * nrmax) static
The documentation for this struct was generated from the following files:
/mnt/e/linuxOS/PhyStar/Math/quadpack/quadpack.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk15.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk15i.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk15w.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk21.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk31.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk41.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk51.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/gk61.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qag.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qage.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qagi.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qagp.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qags.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qawc.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qawce.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qawf.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qawfe.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qawo.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qaws.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qawse.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qc25c.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qc25o.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qc25s.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qcheb.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qext.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qfour.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qmomo.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qng.hpp
/mnt/e/linuxOS/PhyStar/Math/quadpack/qsort.hpp