PhyStar: solver::fluidsol::CartFFT< 3 > Struct Reference
solver::fluidsol::CartFFT< 3 > Struct Reference
#include <CartFFT.hpp>
Public Member Functions
void Init ()
void TransformR2C (blin::Array3r &in, blin::Array3cr &out)
void TransformR2C_Dealias (blin::Array3r &in, blin::Array3cr &out)
void TransformC2R (blin::Array3cr &in, blin::Array3r &out)
void TransformC2R_Dealias (blin::Array3cr &in, blin::Array3r &out)
template<DiffTag DT>
void Diff (blin::Array3cr &in)
template<DiffTag DT>
void Diff (blin::Array3cr &in, blin::Array3cr &out, Real alpha=1., Real beta=0.)
void Div (blin::Array3cr &u, blin::Array3cr &v, blin::Array3cr &w, blin::Array3cr &out, Real alpha=1., Real beta=0.)
void Lap (blin::Array3cr &in, blin::Array3cr &out, Real alpha=1., Real beta=0.)
Public Attributes
tfft3d::FFT3D< Real, 100 > origin
tfft3d::FFT3D< Real, 200 > dealias
blin::Array1r kx
blin::Array1r ky
blin::Array1r kz
blin::Array1cr ikx
blin::Array1cr iky
blin::Array1cr ikz
blin::Array1r rtemp
Real one_nxyz
Real one_nxyz_de
Real xr
Real yr
Real zr
Real lx
Real ly
Real lz
Real kmax
std::vector< int > st
std::vector< int > ed
int ghx
int ghy
int ghz
int nx
int ny
int nz
int mx
int my
int mz
int npr
int npc
Member Function Documentation
Diff() [1/2]
template<DiffTag DT> void solver::fluidsol::CartFFT< 3 >::Diff (blin::Array3cr & in) inline
References solver::fluidsol::Dx, solver::fluidsol::DxDx, solver::fluidsol::DxDy, solver::fluidsol::DxDz, solver::fluidsol::Dy, solver::fluidsol::DyDx, solver::fluidsol::DyDy, solver::fluidsol::DyDz, solver::fluidsol::Dz, solver::fluidsol::DzDx, solver::fluidsol::DzDy, and solver::fluidsol::DzDz.
Diff() [2/2]
template<DiffTag DT> void solver::fluidsol::CartFFT< 3 >::Diff (blin::Array3cr & in, blin::Array3cr & out, Real alpha = 1., Real beta = 0.) inline
References solver::fluidsol::Dx, solver::fluidsol::DxDx, solver::fluidsol::DxDy, solver::fluidsol::DxDz, solver::fluidsol::Dy, solver::fluidsol::DyDx, solver::fluidsol::DyDy, solver::fluidsol::DyDz, solver::fluidsol::Dz, solver::fluidsol::DzDx, solver::fluidsol::DzDy, and solver::fluidsol::DzDz.
Div()
void solver::fluidsol::CartFFT< 3 >::Div (blin::Array3cr & u, blin::Array3cr & v, blin::Array3cr & w, blin::Array3cr & out, Real alpha = 1., Real beta = 0.) inline
Init()
void solver::fluidsol::CartFFT< 3 >::Init () inline
References mathconst::cONE(), tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalIndexAfterTrans(), tfft3d::FFT3D< T_real, GroupID, TypeID >::getMaxBufferSize(), tfft3d::kDFTc2c, tfft3d::kDFTr2c, tfft3d::kX, tfft3d::kY, tfft3d::kZ, quadpack::min(), mathconst::PI, and tfft3d::FFT3D< T_real, GroupID, TypeID >::setSizeBeforeTrans().
Lap()
void solver::fluidsol::CartFFT< 3 >::Lap (blin::Array3cr & in, blin::Array3cr & out, Real alpha = 1., Real beta = 0.) inline
TransformC2R()
void solver::fluidsol::CartFFT< 3 >::TransformC2R (blin::Array3cr & in, blin::Array3r & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::AddGhost(), tfft3d::FFT3D< T_real, GroupID, TypeID >::BackwardTrans(), and tfft3d::Before.
TransformC2R_Dealias()
void solver::fluidsol::CartFFT< 3 >::TransformC2R_Dealias (blin::Array3cr & in, blin::Array3r & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::BackwardTrans().
TransformR2C()
void solver::fluidsol::CartFFT< 3 >::TransformR2C (blin::Array3r & in, blin::Array3cr & out) inline
References tfft3d::Before, tfft3d::FFT3D< T_real, GroupID, TypeID >::ForwardTrans(), and tfft3d::FFT3D< T_real, GroupID, TypeID >::RemoveGhost().
TransformR2C_Dealias()
void solver::fluidsol::CartFFT< 3 >::TransformR2C_Dealias (blin::Array3r & in, blin::Array3cr & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::ForwardTrans().
Member Data Documentation
dealias
tfft3d::FFT3D<Real, 200> solver::fluidsol::CartFFT< 3 >::dealias
ed
std::vector<int> solver::fluidsol::CartFFT< 3 >::ed
ghx
int solver::fluidsol::CartFFT< 3 >::ghx
ghy
int solver::fluidsol::CartFFT< 3 >::ghy
ghz
int solver::fluidsol::CartFFT< 3 >::ghz
ikx
blin::Array1cr solver::fluidsol::CartFFT< 3 >::ikx
iky
blin::Array1cr solver::fluidsol::CartFFT< 3 >::iky
ikz
blin::Array1cr solver::fluidsol::CartFFT< 3 >::ikz
kmax
Real solver::fluidsol::CartFFT< 3 >::kmax
kx
blin::Array1r solver::fluidsol::CartFFT< 3 >::kx
ky
blin::Array1r solver::fluidsol::CartFFT< 3 >::ky
kz
blin::Array1r solver::fluidsol::CartFFT< 3 >::kz
lx
Real solver::fluidsol::CartFFT< 3 >::lx
ly
Real solver::fluidsol::CartFFT< 3 >::ly
lz
Real solver::fluidsol::CartFFT< 3 >::lz
mx
int solver::fluidsol::CartFFT< 3 >::mx
my
int solver::fluidsol::CartFFT< 3 >::my
mz
int solver::fluidsol::CartFFT< 3 >::mz
npc
int solver::fluidsol::CartFFT< 3 >::npc
npr
int solver::fluidsol::CartFFT< 3 >::npr
nx
int solver::fluidsol::CartFFT< 3 >::nx
ny
int solver::fluidsol::CartFFT< 3 >::ny
nz
int solver::fluidsol::CartFFT< 3 >::nz
one_nxyz
Real solver::fluidsol::CartFFT< 3 >::one_nxyz
one_nxyz_de
Real solver::fluidsol::CartFFT< 3 >::one_nxyz_de
origin
tfft3d::FFT3D<Real, 100> solver::fluidsol::CartFFT< 3 >::origin
rtemp
blin::Array1r solver::fluidsol::CartFFT< 3 >::rtemp
st
std::vector<int> solver::fluidsol::CartFFT< 3 >::st
xr
Real solver::fluidsol::CartFFT< 3 >::xr
yr
Real solver::fluidsol::CartFFT< 3 >::yr
zr
Real solver::fluidsol::CartFFT< 3 >::zr
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/Solver/FluidSol/SpecDiffHybrid/BoxFFT/CartFFT.hpp