PhyStar: CartBoxFDMDuct Class Reference
CartBoxFDMDuct Class Reference
#include <CartBoxFDMDuct.h>
Public Member Functions
void AddDpDxAndFixFluxIfNecessary ()
void ConfigFlowDict ()
virtual void SolveStageOne (const int &step, const Real &time, const Real &coef) override final
virtual void InitStatLogFile () override final
virtual void StatLog (const int &istep, const Real &time) override final
virtual void Statistic (const int &istep, const Real &time) override final
Public Member Functions inherited from solver::fluidsol::FDMSolver
FDMSolver ()
virtual ~FDMSolver ()
Public Member Functions inherited from solver::Solver
Solver ()
virtual ~Solver ()
void PrintAbstract ()
void Relase (const SolverNameList &flag)
void ConfigGlobalDict (const std::string filename)
void PrintConfigGlobalDict ()
virtual std::string GetSolverName ()
virtual std::string GetMeshName ()
Public Member Functions inherited from solver::CartDataSpace< N_dim, 999 >
CartDataSpace ()
~CartDataSpace ()
void ConfigDataSpaceDict ()
config information of mpi from ControlDict.in
void CheckConfigDataSpaceDict ()
Private Types
using FlowType = solver::fluidsol::boxfdm::FlowType
using DpDxType = solver::fluidsol::boxfdm::DpDxType
Private Member Functions
Real CalDpDxAndFixFlux ()
void AddDpDx (const Real &dpdx)
void InitDuctFlow (const Real &time)
virtual void GenerateInitFlow (const FlowType &ftype, const Real &time) override final
Genearate Flow at the begining.
Private Attributes
struct {
DpDxType dpdx_type
} dict
Additional Inherited Members
Static Public Member Functions inherited from solver::Solver
static const auto & GlobalDict ()
static const auto & Dt ()
Static Public Member Functions inherited from solver::CartDataSpace< N_dim, 999 >
static std::vector< int > CalTotalShape (const std::vector< int > &flag)
Public Attributes inherited from solver::CartDataSpace< N_dim, 999 >
std::vector< Real > domain_size
std::vector< int > mesh_size
std::vector< int > ghost_size
std::vector< int > stagger_flag
Static Public Attributes inherited from solver::CartDataSpace< N_dim, 999 >
static std::vector< std::vector< Real > > domain_size
static std::vector< std::vector< Real > > gb_domain_size
static std::vector< int > mesh_size
static std::vector< int > gb_mesh_size
static std::vector< int > start_index
static std::vector< std::vector< int > > ghost_size
static std::vector< std::vector< int > > stagger_flag
static const std::vector< int > center_flag
static blockelm::CartMesh< N_dim > gb_cartmesh
static blockelm::CartBlock< N_dim > cartblock
static gsmpi::GSMPICart< N_dim > mpicomm
static std::vector< ibm::IBMCart< N_dim > > cartibm
static int ibm_flag
static std::vector< blockelm::CartField< Real, N_dim > * > tempfields
static tml::tmlnode dataspacetml
struct {
std::vector< Real > domain_size
std::vector< int > mesh_size
std::vector< int > ghost_size
std::vector< int > stagger_flag
} dataspacedict
Protected Member Functions inherited from solver::fluidsol::FluidSolBase
FluidSolBase ()
virtual ~FluidSolBase ()
virtual void Init ()=0
virtual void Solve (const int &step, const Real &time, std::vector< std::shared_ptr< ppsol::PPSolBase >>)=0
virtual void SolveStageTwo (const int &step, const Real &time, const Real &coef)=0
virtual void Finish (const int &step, const Real &time)=0
virtual void WriteFields (const int &step, const Real &time)=0
Protected Attributes inherited from solver::fluidsol::FluidSolBase
tml::tmlnode fluidsoltml
tml::tmlnode fparams
Static Protected Attributes inherited from solver::fluidsol::FluidSolBase
static Real & dtf = dt
Static Protected Attributes inherited from solver::Solver
static std::string header = "PhyStar"
static std::string version = "v0.0.1"
static int count
static Solver * ptr_fluidsol = nullptr
static Solver * ptr_point_particlesol = nullptr
static Solver * ptr_resolved_particlesol = nullptr
static Real dt
static Real kvisc
static Real density
static tml::tmlnode globaltml
struct {
std::string casename
Real time_start
Real time_end
Real time_ndump
int ndim
int step_start
int nstep
int step_end
int step_ndump
int step_nscreen
int step_nstat
int step_nrefresh
int ppsol_flag
int ppsol_same_dict
unsigned int random_seed
} globaldict
Member Typedef Documentation
DpDxType
using CartBoxFDMDuct::DpDxType = solver::fluidsol::boxfdm::DpDxType private
FlowType
using CartBoxFDMDuct::FlowType = solver::fluidsol::boxfdm::FlowType private
Member Function Documentation
AddDpDx()
void CartBoxFDMDuct::AddDpDx (const Real & dpdx) private
References solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, and solver::CartDataSpace< N_dim, 999 >::ghost_size.
AddDpDxAndFixFluxIfNecessary()
void CartBoxFDMDuct::AddDpDxAndFixFluxIfNecessary () inline
References AddDpDx(), CalDpDxAndFixFlux(), and dict.
CalDpDxAndFixFlux()
Real CartBoxFDMDuct::CalDpDxAndFixFlux () private
ConfigFlowDict()
void CartBoxFDMDuct::ConfigFlowDict () inline
References dict, solver::fluidsol::FluidSolBase::fluidsoltml, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::Solver::kvisc, and solver::fluidsol::boxfdm::vConfigDpDxType().
GenerateInitFlow()
virtual void CartBoxFDMDuct::GenerateInitFlow (const FlowType & ftype, const Real & time) inline final override private virtual
Genearate Flow at the begining.
this function may be executed in parent class CartBoxFDM.
Parameters
ftype flow type enum
time time
References InitDuctFlow().
InitDuctFlow()
void CartBoxFDMDuct::InitDuctFlow (const Real & time) private
References dict, solver::fluidsol::FluidSolBase::fparams, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mesh_size, mathconst::PI, and RandomNumber< T_real >::randr().
InitStatLogFile()
void CartBoxFDMDuct::InitStatLogFile () final override virtual
References solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
SolveStageOne()
void CartBoxFDMDuct::SolveStageOne (const int & step, const Real & time, const Real & coef) final override virtual
Implements solver::fluidsol::FluidSolBase.
References AddDpDx(), CalDpDxAndFixFlux(), dict, dmdyn::init::None(), and solver::fluidsol::FluidSolBase::SolveStageOne().
Statistic()
void CartBoxFDMDuct::Statistic (const int & istep, const Real & time) final override virtual
References solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, fileio::intTostr(), quadpack::max(), solver::CartDataSpace< N_dim, 999 >::mesh_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
StatLog()
void CartBoxFDMDuct::StatLog (const int & istep, const Real & time) final override virtual
References compgeo::eps, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mesh_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
Member Data Documentation
struct { ... } CartBoxFDMDuct::dict
dpdx_type
DpDxType CartBoxFDMDuct::dpdx_type
The documentation for this class was generated from the following files:
/mnt/e/linuxOS/PhyStar/Apps/cartboxfdmDuct/solver/CartBoxFDMDuct.h
/mnt/e/linuxOS/PhyStar/Apps/cartboxfdmDuct/solver/CartBoxFDMDuct.cpp