PhyStar: gsmpi::CartFieldGhostComm< T, N_dim > Struct Template Reference
gsmpi::CartFieldGhostComm< T, N_dim > Struct Template Reference
#include <cartfieldghostcomm.hpp>
Public Member Functions
CartFieldGhostComm ()
Construct a new Sender object.
CartFieldGhostComm (GSMPICart< N_dim > &comm)
auto & Init (GSMPICart< N_dim > &comm)
auto & AllocateBuffer (std::vector< int > size, std::vector< std::vector< int >> ghost_size)
allocate the buffer
auto SendRecv (T data[], const std::vector< int > &totalsize, const std::vector< int > &grid_flag, const std::vector< std::vector< int >> &ghost_size, MPI_Datatype datatype, double alpha=1.0, double beta=0.0)
Send and receive the fluid data for the ghost mesh.
auto SendRecv (Array< T, N_dim > &data, const std::vector< int > &grid_flag, const std::vector< std::vector< int >> &ghost_size, MPI_Datatype datatype, double alpha=1.0, double beta=0.0)
Send and receive the fluid data for the ghost mesh.
auto SendRecvAlongX (T data[], const std::vector< int > &totalsize, const std::vector< int > &grid_flag, const std::vector< std::vector< int >> &ghost_size, MPI_Datatype datatype, double alpha=1.0, double beta=0.0)
auto SendRecvAlongY (T data[], const std::vector< int > &totalsize, const std::vector< int > &grid_flag, const std::vector< std::vector< int >> &ghost_size, MPI_Datatype datatype, double alpha=1.0, double beta=0.0)
auto SendRecvAlongZ (T data[], const std::vector< int > &totalsize, const std::vector< int > &grid_flag, const std::vector< std::vector< int >> &ghost_size, MPI_Datatype datatype, double alpha=1.0, double beta=0.0)
Public Attributes
MPI_Comm _comm
GSMPICart< N_dim > * ptr_cartcomm
Array1< T > buffer
Array1< T > recv_buffer
int count = 0
Array1i nbrs
int nbrs_num
Constructor & Destructor Documentation
CartFieldGhostComm() [1/2]
template<typename T , int N_dim> gsmpi::CartFieldGhostComm< T, N_dim >::CartFieldGhostComm () inline
Construct a new Sender object.
CartFieldGhostComm() [2/2]
template<typename T , int N_dim> gsmpi::CartFieldGhostComm< T, N_dim >::CartFieldGhostComm (GSMPICart< N_dim > & comm) inline
Member Function Documentation
AllocateBuffer()
template<typename T , int N_dim> auto& gsmpi::CartFieldGhostComm< T, N_dim >::AllocateBuffer (std::vector< int > size, std::vector< std::vector< int >> ghost_size) inline
allocate the buffer
Returns
auto&
References quadpack::max().
Init()
template<typename T , int N_dim> auto& gsmpi::CartFieldGhostComm< T, N_dim >::Init (GSMPICart< N_dim > & comm) inline
References gsmpi::GSMPI::GetComm(), gsmpi::GSMPI::GetNumofNbrs(), and gsmpi::GSMPI::PtrNbrsList().
SendRecv() [1/2]
template<typename T , int N_dim> auto gsmpi::CartFieldGhostComm< T, N_dim >::SendRecv (Array< T, N_dim > & data, const std::vector< int > & grid_flag, const std::vector< std::vector< int >> & ghost_size, MPI_Datatype datatype, double alpha = 1.0, double beta = 0.0) inline
Send and receive the fluid data for the ghost mesh.
Parameters
data containing the ghost cell part
ghost_size
datatype
Returns
SendRecv() [2/2]
template<typename T , int N_dim> auto gsmpi::CartFieldGhostComm< T, N_dim >::SendRecv (T data[], const std::vector< int > & totalsize, const std::vector< int > & grid_flag, const std::vector< std::vector< int >> & ghost_size, MPI_Datatype datatype, double alpha = 1.0, double beta = 0.0) inline
Send and receive the fluid data for the ghost mesh.
Parameters
data containing the ghost part
totalsize containg the ghost
ghost_size
datatype
Returns
none
SendRecvAlongX()
template<typename T , int N_dim> auto gsmpi::CartFieldGhostComm< T, N_dim >::SendRecvAlongX (T data[], const std::vector< int > & totalsize, const std::vector< int > & grid_flag, const std::vector< std::vector< int >> & ghost_size, MPI_Datatype datatype, double alpha = 1.0, double beta = 0.0) inline
References gsmpi::GSMPICart< N_dim, IsColMaj >::RefNbrs().
SendRecvAlongY()
template<typename T , int N_dim> auto gsmpi::CartFieldGhostComm< T, N_dim >::SendRecvAlongY (T data[], const std::vector< int > & totalsize, const std::vector< int > & grid_flag, const std::vector< std::vector< int >> & ghost_size, MPI_Datatype datatype, double alpha = 1.0, double beta = 0.0) inline
References gsmpi::GSMPICart< N_dim, IsColMaj >::RefNbrs().
SendRecvAlongZ()
template<typename T , int N_dim> auto gsmpi::CartFieldGhostComm< T, N_dim >::SendRecvAlongZ (T data[], const std::vector< int > & totalsize, const std::vector< int > & grid_flag, const std::vector< std::vector< int >> & ghost_size, MPI_Datatype datatype, double alpha = 1.0, double beta = 0.0) inline
References gsmpi::GSMPICart< N_dim, IsColMaj >::RefNbrs().
Member Data Documentation
_comm
template<typename T , int N_dim> MPI_Comm gsmpi::CartFieldGhostComm< T, N_dim >::_comm
buffer
template<typename T , int N_dim> Array1<T> gsmpi::CartFieldGhostComm< T, N_dim >::buffer
count
template<typename T , int N_dim> int gsmpi::CartFieldGhostComm< T, N_dim >::count = 0
nbrs
template<typename T , int N_dim> Array1i gsmpi::CartFieldGhostComm< T, N_dim >::nbrs
nbrs_num
template<typename T , int N_dim> int gsmpi::CartFieldGhostComm< T, N_dim >::nbrs_num
ptr_cartcomm
template<typename T , int N_dim> GSMPICart<N_dim>* gsmpi::CartFieldGhostComm< T, N_dim >::ptr_cartcomm
recv_buffer
template<typename T , int N_dim> Array1<T> gsmpi::CartFieldGhostComm< T, N_dim >::recv_buffer
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/Parallel/gsmpi/cartfieldghostcomm.hpp