PhyStar: dmdyn::EllipsoidalPointParticle Struct Reference
dmdyn::EllipsoidalPointParticle Struct Reference
the base of single ellipsoidal point particle
#include <EllipsoidalPointParticle.h>
Public Types
using FM_ptr = std::shared_ptr< ForceModel >
using TM_ptr = std::shared_ptr< TorqueModel >
Public Member Functions
EllipsoidalPointParticle ()
virtual Real Gravity ()
virtual const Vec3< Real > & GravityDir ()
virtual const Vec3< Real > & ResistTransPF () final
virtual const Vec3< Real > & ResistRotatePF () final
virtual const Real & KVisc () final
virtual const Real & Radius () final
virtual Real Mass ()
virtual Real Volume ()
virtual Real Density ()
virtual bool IsInside (const Vec3r &dpos)
virtual bool IsInside (const Vec2r &dpos)
virtual Real LevelSetFunction (const Vec3r &dpos)
virtual Real LevelSetFunction (const Vec2r &dpos)
virtual Real LevelSetVolumeFraction (const Vec3r &pos)
virtual void UpdateLevelSetTransform (const int dim, const Real &dx, const Vec3r &pos, const Vec4r &ee)
Public Member Functions inherited from dmdyn::ParticleModel
virtual ParticleData< 3 > dSolve (ParticleField< 3 > &)
virtual ParticleData< 2 > dSolve (ParticleField< 2 > &)
virtual int & RefLocalSize ()
virtual int & RefTotalSize ()
virtual void InitPModelData (ParticleField< 3 > &pfield)
virtual void InitPModelData (ParticleField< 2 > &pfield)
virtual Real MaxLength ()=0
virtual Real MaxRadius ()=0
virtual Real EquRadius ()=0
virtual ShapeType ShapeID ()=0
virtual int IBMID ()
virtual const Real & Ah ()
virtual const WPDetectMethod & WallContactDetectMethod ()
Public Member Functions inherited from dmdyn::EllipsoidalShape< Real >
EllipsoidalShape ()
~EllipsoidalShape ()
void Initialize (Real kvisc, Real densityRatio, Real radius, const Vec3< Real > &aspectRatio)
Real DistanceFunction (const Vec3< Real > &dpos)
Real DistanceFunction (const Vec2< Real > &dpos)
void UpdateLevelSet (const int dim, const Real dx, const Real pos[], const Real ee[])
Real LevelSetVolFrac (const Vec3< Real > &pos)
Real Radius2 ()
Real Radius3 ()
virtual const Vec3< Real > & AspectRatio ()
Real AspectRatio2 (int i)
Real Volume ()
Real ComputeMass ()
Real Ixx ()
Real Iyy ()
Real Izz ()
Real Ixx_Iyy ()
Real Iyy_Izz ()
Real Ixx_Izz ()
Real Iyy_Ixx ()
Real Izz_Iyy ()
Real Izz_Ixx ()
void ComputeLam ()
void ComputeResistTransPF ()
void ComputeResistRotatePF ()
Real ResponseTimeTrans ()
Real ResponseTimeTransInv ()
virtual void ComputeIntParams ()
Public Attributes
std::vector< FM_ptr > fluid_force_models
std::vector< TM_ptr > fluid_torque_models
Real gravity
Vec3< Real > gravity_dir
Public Attributes inherited from dmdyn::ParticleModel
int nsize
int nsize_total
int modelid
int id
int sensorID
int actorID
int agentID
Real ah = 1.0
WPDetectMethod wcdetect_method = WPDetectMethod::EquRadius
algo::fcl::CollisionGeometryPtr_t geometry
Additional Inherited Members
Static Public Attributes inherited from dmdyn::ParticleModel
static int count = 0
Protected Attributes inherited from dmdyn::EllipsoidalShape< Real >
Real kvisc
Real density_ratio
Real mass
Real radius
Vec3< Real > aspect_ratio
Vec3< Real > uplam
Vec4< Real > int_params
Vec3< Real > resist_trans_pf
Vec3< Real > resist_rotate_pf
EllipsoidLevelSet< Real > levelset
Detailed Description
the base of single ellipsoidal point particle
Member Typedef Documentation
FM_ptr
using dmdyn::EllipsoidalPointParticle::FM_ptr = std::shared_ptr<ForceModel>
TM_ptr
using dmdyn::EllipsoidalPointParticle::TM_ptr = std::shared_ptr<TorqueModel>
Constructor & Destructor Documentation
EllipsoidalPointParticle()
dmdyn::EllipsoidalPointParticle::EllipsoidalPointParticle () inline
Member Function Documentation
Density()
virtual Real dmdyn::EllipsoidalPointParticle::Density () inline virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::density_ratio.
Gravity()
virtual Real dmdyn::EllipsoidalPointParticle::Gravity () inline virtual
Implements dmdyn::ParticleModel.
References gravity.
GravityDir()
virtual const Vec3<Real>& dmdyn::EllipsoidalPointParticle::GravityDir () inline virtual
Implements dmdyn::ParticleModel.
References gravity_dir.
IsInside() [1/2]
virtual bool dmdyn::EllipsoidalPointParticle::IsInside (const Vec2r & dpos) inline virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::DistanceFunction().
IsInside() [2/2]
virtual bool dmdyn::EllipsoidalPointParticle::IsInside (const Vec3r & dpos) inline virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::DistanceFunction().
KVisc()
virtual const Real& dmdyn::EllipsoidalPointParticle::KVisc () inline final virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::kvisc.
LevelSetFunction() [1/2]
virtual Real dmdyn::EllipsoidalPointParticle::LevelSetFunction (const Vec2r & dpos) inline virtual
References dmdyn::EllipsoidalShape< Real >::DistanceFunction().
LevelSetFunction() [2/2]
virtual Real dmdyn::EllipsoidalPointParticle::LevelSetFunction (const Vec3r & dpos) inline virtual
References dmdyn::EllipsoidalShape< Real >::DistanceFunction().
LevelSetVolumeFraction()
virtual Real dmdyn::EllipsoidalPointParticle::LevelSetVolumeFraction (const Vec3r & pos) inline virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< T_real >::LevelSetVolFrac().
Mass()
virtual Real dmdyn::EllipsoidalPointParticle::Mass () inline virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::mass.
Radius()
virtual const Real& dmdyn::EllipsoidalPointParticle::Radius () inline final virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::radius.
ResistRotatePF()
virtual const Vec3<Real>& dmdyn::EllipsoidalPointParticle::ResistRotatePF () inline final virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::resist_rotate_pf.
ResistTransPF()
virtual const Vec3<Real>& dmdyn::EllipsoidalPointParticle::ResistTransPF () inline final virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< Real >::resist_trans_pf.
UpdateLevelSetTransform()
virtual void dmdyn::EllipsoidalPointParticle::UpdateLevelSetTransform (const int dim, const Real & dx, const Vec3r & pos, const Vec4r & ee) inline virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< T_real >::UpdateLevelSet().
Volume()
virtual Real dmdyn::EllipsoidalPointParticle::Volume () inline virtual
Implements dmdyn::ParticleModel.
References dmdyn::EllipsoidalShape< T_real >::Volume().
Member Data Documentation
fluid_force_models
std::vector<FM_ptr> dmdyn::EllipsoidalPointParticle::fluid_force_models
fluid_torque_models
std::vector<TM_ptr> dmdyn::EllipsoidalPointParticle::fluid_torque_models
gravity
Real dmdyn::EllipsoidalPointParticle::gravity
gravity_dir
Vec3<Real> dmdyn::EllipsoidalPointParticle::gravity_dir
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/DMDyn/DMClass/EllipsoidalPointParticle.h