PhyStar: solver::fluidsol::CartBoxFFDSol< 3, SpaceID > Class Template Reference
solver::fluidsol::CartBoxFFDSol< 3, SpaceID > Class Template Reference
#include <CartBoxFFDSol.hpp>
Public Types
using Field = blockelm::CartField< Real, 3 >
using BTypeMap = std::unordered_map< std::string, std::vector< blockelm::BoundaryType > >
using BValMap = std::unordered_map< std::string, std::vector< Real > >
Public Member Functions
CartBoxFFDSol ()
virtual ~CartBoxFFDSol ()
virtual void Init ()
virtual void Solve (const int &step, const Real &time, std::vector< std::shared_ptr< ppsol::PPSolBase >> ppsols={})
virtual void SolveAB2 (const int &step, const Real &time, std::vector< std::shared_ptr< ppsol::PPSolBase >> &ppsols={})
virtual void SolveLSRK3 (const int &step, const Real &time, std::vector< std::shared_ptr< ppsol::PPSolBase >> &ppsols={})
virtual void SolveStageOne (const int &step, const Real &time, const Real &coef=1.0)
virtual void SolveStageTwo (const int &step, const Real &time, const Real &coef=1.0)
virtual void Finish (const int &step, const Real &time)
virtual void WriteFields (const int &step, const Real &time)
virtual void WriteFieldsNew (const int &step, const Real &time)
virtual void WriteMidFields (const int &step, const Real &time)
virtual void LoadFields ()
virtual std::string GetSolverName ()
virtual std::string GetMeshName ()
auto & CreateUniformMesh (std::vector< int > nsize, std::vector< std::vector< Real >> edges, std::vector< std::vector< int >> ghs={{0}, {0}, {0}})
auto & CreateUniformMesh (int nsize, std::vector< Real > edges, std::vector< int > ghs={0})
auto & CreateVelocityFields (std::vector< std::vector< int >> flgs)
auto & CreatePressureField (std::vector< int > flgs)
auto & CreateGradField (std::vector< int > flgs)
auto & CreateScalarFields (std::vector< int > flgs, const int n)
auto & MappingMeshToStretching ()
mapping new mesh of the third direction to stretching mesh
void InitTempFields ()
void InitSpecSpace ()
void NonLinearTerm (const Real &coef=1.0)
void ViscousTerm (const Real &coef=1.0)
void AB2 ()
void PressureTerm (const Real &coef=1.0)
void Correct (const Real &coef=1.0)
void AddCouplingForceIfNecessary (const Real &coef=1.0)
void UpdateDtIfNecessary (const Real &chdt)
void TransToPhysVelocityGradient ()
void TransToPhysVelocity ()
void TransToPhysPressure ()
void TransToSpecVelocity ()
void BoundaryOfSpecVelocity ()
void InitTCF (const Real &time)
init turbulent channel flow in physical space
Real CalDpDxAndFixFluxInTCF ()
void AddDpDxInTCF (const Real &dpdx)
auto CalMaxDivInSpec ()
auto CalMaxCFLDt ()
void Statistic (const int &istep, const Real &time)
void StatLog (const int &istep, const Real &time)
void InitStatLogFile ()
void ConfigFlowDict ()
void CheckConfigFlowDict ()
boxffd::FlowType vConfigFlowType (const std::string &type)
blockelm::MeshType vConfigMeshType (const std::string &type)
blockelm::BoundaryType vConfigBoundaryType (const std::string &type)
boxffd::DpDxType vConfigDpDxType (const std::string &type)
void GenerateInitFlow (const boxffd::FlowType &ftype, const Real &time)
void InitFilePath ()
Public Member Functions inherited from solver::fluidsol::SpecDiffHybrid
SpecDiffHybrid ()
virtual ~SpecDiffHybrid ()
Public Member Functions inherited from solver::Solver
Solver ()
virtual ~Solver ()
void PrintAbstract ()
void Relase (const SolverNameList &flag)
void ConfigGlobalDict (const std::string filename)
void PrintConfigGlobalDict ()
Public Member Functions inherited from solver::CartDataSpace< 3, SpaceID >
CartDataSpace ()
~CartDataSpace ()
void ConfigDataSpaceDict ()
config information of mpi from ControlDict.in
void CheckConfigDataSpaceDict ()
Public Attributes
blockelm::CartBlock< 3 > & block = CartDataSpace<3, SpaceID>::cartblock
blockelm::CartMesh< 3 > & gb_mesh = CartDataSpace<3, SpaceID>::gb_cartmesh
std::vector< std::vector< Real > > & domain_size = CartDataSpace<3, SpaceID>::domain_size
std::vector< std::vector< Real > > & gb_domain_size = CartDataSpace<3, SpaceID>::gb_domain_size
std::vector< int > & mesh_size = CartDataSpace<3, SpaceID>::mesh_size
std::vector< int > & gb_mesh_size = CartDataSpace<3, SpaceID>::gb_mesh_size
std::vector< std::vector< int > > & ghost_size = CartDataSpace<3, SpaceID>::ghost_size
std::vector< std::vector< int > > & stagger_flag = CartDataSpace<3, SpaceID>::stagger_flag
const std::vector< int > & center_flag = CartDataSpace<3, SpaceID>::center_flag
gsmpi::GSMPICart< 3 > & mpicomm = CartDataSpace<3, SpaceID>::mpicomm
std::vector< ibm::IBMCart< 3 > > & cartibm = CartDataSpace<3, SpaceID>::cartibm
int & ibm_flag = CartDataSpace<3, SpaceID>::ibm_flag
gsmpi::CartFieldGhostComm< Real, 3 > ghostcomm
CartFFD< 3, 10 > ffd_at_p
CartFFD< 3, 20 > ffd_at_w
fdm::FDMSecondCenteralDiff< fdm::FDMTAG_Type::Stretch > fdm
blin::Arraycr< 3 > u
blin::Arraycr< 3 > v
blin::Arraycr< 3 > w
blin::Arraycr< 3 > p
blin::Arraycr< 3 > us
blin::Arraycr< 3 > vs
blin::Arraycr< 3 > ws
blin::Arraycr< 3 > utnew
blin::Arraycr< 3 > vtnew
blin::Arraycr< 3 > wtnew
blin::Arraycr< 3 > utold
blin::Arraycr< 3 > vtold
blin::Arraycr< 3 > wtold
blin::Arrayr< 3 > lap
blin::Vec< blin::Arrayr< 3 >, 5 > rwrk
blin::Vec< blin::Arrayr< 3 >, 2 > rwrkf
blin::Vec< blin::Arraycr< 3 >, 3 > cwrk
blin::Vec< blin::Arraycr< 3 >, 1 > cwrkf
std::vector< blockelm::CartField< Real, 3 > * > & tempfields = CartDataSpace<3, SpaceID>::tempfields
Field fx
Field fy
Field fz
blin::Arraycr< 3 > fxwrk
blin::Arraycr< 3 > fywrk
blin::Arraycr< 3 > fzwrk
blin::Vec3i stf
blin::Vec3i edf
blin::Vec3i stp
blin::Vec3i edp
int stf2w
int edf2w
int stp2w
int edp2w
bool flow_start_flag = true
struct solver::fluidsol::CartBoxFFDSol< 3, SpaceID >:: { ... } flowdict
boxffd::FlowType flow_type
Real dt
Real kvisc
Real density
Real Re
Real Retau
std::vector< Real > params
std::string work_path
Real cfl
int conti
boxffd::DpDxType dpdx_type
boxffd::TimeScheme time_scheme
BTypeMap btype
BValMap bval
Public Attributes inherited from solver::CartDataSpace< 3, SpaceID >
std::vector< Real > domain_size
std::vector< int > mesh_size
std::vector< int > ghost_size
std::vector< int > stagger_flag
Private Attributes
const std::string _name = "CartBoxFFDSol"
Additional Inherited Members
Static Public Member Functions inherited from solver::Solver
static const auto & GlobalDict ()
static const auto & Dt ()
Static Public Member Functions inherited from solver::CartDataSpace< 3, SpaceID >
static std::vector< int > CalTotalShape (const std::vector< int > &flag)
Static Public Attributes inherited from solver::CartDataSpace< 3, SpaceID >
static std::vector< std::vector< Real > > domain_size
static std::vector< std::vector< Real > > gb_domain_size
static std::vector< int > mesh_size
static std::vector< int > gb_mesh_size
static std::vector< int > start_index
static std::vector< std::vector< int > > ghost_size
static std::vector< std::vector< int > > stagger_flag
static const std::vector< int > center_flag
static blockelm::CartMesh< N_dim > gb_cartmesh
static blockelm::CartBlock< N_dim > cartblock
static gsmpi::GSMPICart< N_dim > mpicomm
static std::vector< ibm::IBMCart< N_dim > > cartibm
static int ibm_flag
static std::vector< blockelm::CartField< Real, N_dim > * > tempfields
static tml::tmlnode dataspacetml
struct {
std::vector< Real > domain_size
std::vector< int > mesh_size
std::vector< int > ghost_size
std::vector< int > stagger_flag
} dataspacedict
Protected Member Functions inherited from solver::fluidsol::FluidSolBase
FluidSolBase ()
virtual ~FluidSolBase ()
Protected Attributes inherited from solver::fluidsol::FluidSolBase
tml::tmlnode fluidsoltml
tml::tmlnode fparams
Static Protected Attributes inherited from solver::fluidsol::FluidSolBase
static Real & dtf = dt
Static Protected Attributes inherited from solver::Solver
static std::string header = "PhyStar"
static std::string version = "v0.0.1"
static int count
static Solver * ptr_fluidsol = nullptr
static Solver * ptr_point_particlesol = nullptr
static Solver * ptr_resolved_particlesol = nullptr
static Real dt
static Real kvisc
static Real density
static tml::tmlnode globaltml
struct {
std::string casename
Real time_start
Real time_end
Real time_ndump
int ndim
int step_start
int nstep
int step_end
int step_ndump
int step_nscreen
int step_nstat
int step_nrefresh
int ppsol_flag
int ppsol_same_dict
unsigned int random_seed
} globaldict
Member Typedef Documentation
BTypeMap
template<int SpaceID> using solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::BTypeMap = std::unordered_map<std::string, std::vector<blockelm::BoundaryType> >
BValMap
template<int SpaceID> using solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::BValMap = std::unordered_map<std::string, std::vector<Real> >
Field
template<int SpaceID> using solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Field = blockelm::CartField<Real, 3>
Constructor & Destructor Documentation
CartBoxFFDSol()
template<int SpaceID> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CartBoxFFDSol
References solver::Solver::ptr_fluidsol.
~CartBoxFFDSol()
template<int SpaceID> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::~CartBoxFFDSol virtual
References fileio::FluidCartRegularD< N_dim, FT >::DeallocateBuffer(), and solver::Solver::ptr_fluidsol.
Member Function Documentation
AB2()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::AB2
References solver::Solver::dt.
AddCouplingForceIfNecessary()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::AddCouplingForceIfNecessary (const Real & coef = 1.0)
References solver::CartDataSpace< N_dim, 999 >::ghost_size, and gsmpi::GSMPI_REAL.
AddDpDxInTCF()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::AddDpDxInTCF (const Real & dpdx)
References solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
BoundaryOfSpecVelocity()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::BoundaryOfSpecVelocity
CalDpDxAndFixFluxInTCF()
template<int SpaceID> Real solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CalDpDxAndFixFluxInTCF
References solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
CalMaxCFLDt()
template<int SpaceID> auto solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CalMaxCFLDt
References solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::kvisc, quadpack::max(), and solver::CartDataSpace< N_dim, 999 >::mpicomm.
CalMaxDivInSpec()
template<int SpaceID> auto solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CalMaxDivInSpec
References solver::CartDataSpace< N_dim, 999 >::ghost_size, and solver::CartDataSpace< N_dim, 999 >::mpicomm.
CheckConfigFlowDict()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CheckConfigFlowDict () inline
References solver::fluidsol::boxffd::ConstDpDx, solver::Solver::density, solver::Solver::dt, solver::Solver::globaldict, and solver::Solver::kvisc.
ConfigFlowDict()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ConfigFlowDict () inline
References solver::database::controldict, solver::fluidsol::FluidSolBase::fluidsoltml, solver::fluidsol::FluidSolBase::fparams, blockelm::vConfigBoundaryType(), solver::fluidsol::boxfdm::vConfigDpDxType(), solver::fluidsol::boxfdm::vConfigFlowType(), and solver::fluidsol::boxffd::vConfigTimeScheme().
Correct()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Correct (const Real & coef = 1.0)
References solver::Solver::dt, solver::fluidsol::Dx, and solver::fluidsol::Dy.
CreateGradField()
template<int SpaceID> auto& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CreateGradField (std::vector< int > flgs) inline
References blockelm::CartBlock< N_dim >::CreateGradField().
CreatePressureField()
template<int SpaceID> auto& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CreatePressureField (std::vector< int > flgs) inline
References blockelm::CartBlock< N_dim >::CreatePressureField().
CreateScalarFields()
template<int SpaceID> auto& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CreateScalarFields (std::vector< int > flgs, const int n) inline
References blockelm::CartBlock< N_dim >::CreateScalarFields().
CreateUniformMesh() [1/2]
template<int SpaceID> auto& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CreateUniformMesh (int nsize, std::vector< Real > edges, std::vector< int > ghs = {0}) inline
CreateUniformMesh() [2/2]
template<int SpaceID> auto& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CreateUniformMesh (std::vector< int > nsize, std::vector< std::vector< Real >> edges, std::vector< std::vector< int >> ghs = {{0}, {0}, {0}}) inline
CreateVelocityFields()
template<int SpaceID> auto& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::CreateVelocityFields (std::vector< std::vector< int >> flgs) inline
References blockelm::CartBlock< N_dim >::CreateVelocityFields().
Finish()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Finish (const int & step, const Real & time) virtual
Implements solver::fluidsol::FluidSolBase.
GenerateInitFlow()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::GenerateInitFlow (const boxffd::FlowType & ftype, const Real & time) inline
References solver::fluidsol::boxffd::TCF.
GetMeshName()
template<int SpaceID> std::string solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::GetMeshName virtual
Reimplemented from solver::Solver.
GetSolverName()
template<int SpaceID> std::string solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::GetSolverName virtual
Reimplemented from solver::Solver.
References solver::fluidsol::FluidSolBase::_name.
Init()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Init virtual
Implements solver::fluidsol::FluidSolBase.
References fileio::FluidCartRegularD< N_dim, FT >::AllocateBuffer(), solver::CartDataSpace< N_dim, 999 >::cartibm, solver::CartDataSpace< N_dim, 999 >::center_flag, solver::CartDataSpace< N_dim, 999 >::domain_size, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, solver::CartDataSpace< N_dim, 999 >::ibm_flag, solver::CartDataSpace< N_dim, 999 >::mesh_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, and solver::CartDataSpace< N_dim, 999 >::stagger_flag.
InitFilePath()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::InitFilePath () inline
InitSpecSpace()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::InitSpecSpace
References solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, and solver::CartDataSpace< N_dim, 999 >::mpicomm.
InitStatLogFile()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::InitStatLogFile
References solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
InitTCF()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::InitTCF (const Real & time)
init turbulent channel flow in physical space
Template Parameters
SpaceID
Parameters
time
References solver::fluidsol::boxffd::ConstDpDx, solver::fluidsol::FluidSolBase::fparams, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::CartDataSpace< N_dim, 999 >::mesh_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, mathconst::PI, and RandomNumber< T_real >::randr().
InitTempFields()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::InitTempFields
References solver::CartDataSpace< N_dim, 999 >::tempfields.
LoadFields()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::LoadFields virtual
References fileio::FluidCartRegularD< N_dim, FT >::CloseFile(), solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, solver::CartDataSpace< N_dim, 999 >::mpicomm, fileio::FluidCartRegularD< N_dim, FT >::OpenFile(), fileio::FluidCartRegularD< N_dim, FT >::ReadField(), gsmpi::root, fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr(), and fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh().
MappingMeshToStretching()
template<int SpaceID> auto & solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::MappingMeshToStretching
mapping new mesh of the third direction to stretching mesh
Template Parameters
SpaceID
Returns
auto&
References blockelm::atan, solver::CartDataSpace< N_dim, 999 >::domain_size, solver::fluidsol::FluidSolBase::fluidsoltml, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, mathconst::PI_2, gsmpi::root, blockelm::sin, blockelm::tanh, and blockelm::vConfigMeshType().
NonLinearTerm()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::NonLinearTerm (const Real & coef = 1.0)
References solver::fluidsol::Dx, solver::fluidsol::Dy, and solver::CartDataSpace< N_dim, 999 >::ghost_size.
PressureTerm()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::PressureTerm (const Real & coef = 1.0)
References solver::Solver::dt, solver::CartDataSpace< N_dim, 999 >::ghost_size, and blockelm::Neumann.
Solve()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Solve (const int & step, const Real & time, std::vector< std::shared_ptr< ppsol::PPSolBase >> ppsols = {}) virtual
Implements solver::fluidsol::FluidSolBase.
References solver::fluidsol::boxffd::AB2, and solver::fluidsol::boxffd::LSRK3.
SolveAB2()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::SolveAB2 (const int & step, const Real & time, std::vector< std::shared_ptr< ppsol::PPSolBase >> & ppsols = {}) virtual
References solver::Solver::globaldict, solver::Solver::ptr_point_particlesol, solver::fluidsol::FluidSolBase::SolveStageOne(), and solver::fluidsol::FluidSolBase::SolveStageTwo().
SolveLSRK3()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::SolveLSRK3 (const int & step, const Real & time, std::vector< std::shared_ptr< ppsol::PPSolBase >> & ppsols = {}) virtual
References solver::Solver::dt, solver::Solver::globaldict, solver::Solver::ptr_point_particlesol, solver::fluidsol::FluidSolBase::SolveStageOne(), and solver::fluidsol::FluidSolBase::SolveStageTwo().
SolveStageOne()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::SolveStageOne (const int & step, const Real & time, const Real & coef = 1.0) virtual
Implements solver::fluidsol::FluidSolBase.
References solver::fluidsol::boxffd::ConstDpDx, solver::fluidsol::boxffd::ConstFlow, and solver::fluidsol::boxffd::None.
SolveStageTwo()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::SolveStageTwo (const int & step, const Real & time, const Real & coef = 1.0) virtual
Implements solver::fluidsol::FluidSolBase.
Statistic()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Statistic (const int & istep, const Real & time)
References solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, fileio::intTostr(), solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
StatLog()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::StatLog (const int & istep, const Real & time)
References solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mpicomm, and gsmpi::root.
TransToPhysPressure()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::TransToPhysPressure
References solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, and solver::CartDataSpace< N_dim, 999 >::mesh_size.
TransToPhysVelocity()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::TransToPhysVelocity
References solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, and solver::CartDataSpace< N_dim, 999 >::mesh_size.
TransToPhysVelocityGradient()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::TransToPhysVelocityGradient
References blockelm::Dirichlet, solver::fluidsol::Dx, solver::fluidsol::Dy, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, solver::CartDataSpace< N_dim, 999 >::mesh_size, and blockelm::Neumann.
TransToSpecVelocity()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::TransToSpecVelocity
UpdateDtIfNecessary()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::UpdateDtIfNecessary (const Real & chdt)
References solver::Solver::dt, and quadpack::min().
vConfigBoundaryType()
template<int SpaceID> blockelm::BoundaryType solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::vConfigBoundaryType (const std::string & type) inline
References blockelm::Dirichlet, and blockelm::Neumann.
vConfigDpDxType()
template<int SpaceID> boxffd::DpDxType solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::vConfigDpDxType (const std::string & type) inline
References solver::fluidsol::boxffd::ConstDpDx, solver::fluidsol::boxffd::ConstFlow, and solver::fluidsol::boxffd::None.
vConfigFlowType()
template<int SpaceID> boxffd::FlowType solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::vConfigFlowType (const std::string & type) inline
References solver::fluidsol::boxffd::None, and solver::fluidsol::boxffd::TCF.
vConfigMeshType()
template<int SpaceID> blockelm::MeshType solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::vConfigMeshType (const std::string & type) inline
References blockelm::atan, blockelm::sin, blockelm::tanh, and blockelm::uniform.
ViscousTerm()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ViscousTerm (const Real & coef = 1.0)
References solver::Solver::kvisc.
WriteFields()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::WriteFields (const int & step, const Real & time) virtual
Implements solver::fluidsol::FluidSolBase.
References fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo(), fileio::FluidCartRegularD< N_dim, FT >::AddField(), fileio::FluidCartRegularD< N_dim, FT >::CloseFile(), fileio::FluidCartRegularD< N_dim, FT >::CreateFile(), solver::Solver::density, solver::fluidsol::FluidSolBase::dtf, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, fileio::kOtherInfo, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mesh_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, gsmpi::root, fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr(), fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh(), and fileio::FluidCartRegularD< N_dim, FT >::SetMeshc().
WriteFieldsNew()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::WriteFieldsNew (const int & step, const Real & time) virtual
References fileionew::FluidCartRegularD< N_dim >::AddAttributeTo(), fileionew::FluidCartRegularD< N_dim >::AddField(), fileionew::FluidCartRegularD< N_dim >::CloseFile(), fileionew::FluidCartRegularD< N_dim >::CreateFile(), solver::Solver::density, solver::fluidsol::FluidSolBase::dtf, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mpicomm, fileionew::Others(), gsmpi::root, fileionew::FluidCartRegularD< N_dim >::SetFileAttr(), fileionew::FluidCartRegularD< N_dim >::SetGhostMesh(), and fileionew::FluidCartRegularD< N_dim >::SetMeshc().
WriteMidFields()
template<int SpaceID> void solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::WriteMidFields (const int & step, const Real & time) virtual
References fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo(), fileio::FluidCartRegularD< N_dim, FT >::AddField(), fileio::FluidCartRegularD< N_dim, FT >::CloseFile(), fileio::FluidCartRegularD< N_dim, FT >::CreateFile(), solver::Solver::density, solver::fluidsol::FluidSolBase::dtf, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, fileio::kOtherInfo, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mpicomm, gsmpi::root, fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr(), fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh(), and fileio::FluidCartRegularD< N_dim, FT >::SetMeshc().
Member Data Documentation
_name
template<int SpaceID> const std::string solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::_name = "CartBoxFFDSol" private
block
template<int SpaceID> blockelm::CartBlock<3>& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::block = CartDataSpace<3, SpaceID>::cartblock
btype
template<int SpaceID> BTypeMap solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::btype
bval
template<int SpaceID> BValMap solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::bval
cartibm
template<int SpaceID> std::vector<ibm::IBMCart<3> >& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::cartibm = CartDataSpace<3, SpaceID>::cartibm
center_flag
template<int SpaceID> const std::vector<int>& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::center_flag = CartDataSpace<3, SpaceID>::center_flag
cfl
template<int SpaceID> Real solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::cfl
conti
template<int SpaceID> int solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::conti
cwrk
template<int SpaceID> blin::Vec<blin::Arraycr<3>, 3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::cwrk
cwrkf
template<int SpaceID> blin::Vec<blin::Arraycr<3>, 1> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::cwrkf
density
template<int SpaceID> Real solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::density
domain_size
template<int SpaceID> std::vector<std::vector<Real> >& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::domain_size = CartDataSpace<3, SpaceID>::domain_size
dpdx_type
template<int SpaceID> boxffd::DpDxType solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::dpdx_type
dt
template<int SpaceID> Real solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::dt
edf
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::edf
edf2w
template<int SpaceID> int solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::edf2w
edp
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::edp
edp2w
template<int SpaceID> int solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::edp2w
fdm
template<int SpaceID> fdm::FDMSecondCenteralDiff<fdm::FDMTAG_Type::Stretch> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::fdm
ffd_at_p
template<int SpaceID> CartFFD<3, 10> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ffd_at_p
ffd_at_w
template<int SpaceID> CartFFD<3, 20> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ffd_at_w
flow_start_flag
template<int SpaceID> bool solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::flow_start_flag = true
flow_type
template<int SpaceID> boxffd::FlowType solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::flow_type
struct { ... } solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::flowdict
fx
template<int SpaceID> Field solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::fx
fxwrk
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::fxwrk
fy
template<int SpaceID> Field solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::fy
fywrk
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::fywrk
fz
template<int SpaceID> Field solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::fz
fzwrk
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::fzwrk
gb_domain_size
template<int SpaceID> std::vector<std::vector<Real> >& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::gb_domain_size = CartDataSpace<3, SpaceID>::gb_domain_size
gb_mesh
template<int SpaceID> blockelm::CartMesh<3>& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::gb_mesh = CartDataSpace<3, SpaceID>::gb_cartmesh
gb_mesh_size
template<int SpaceID> std::vector<int>& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::gb_mesh_size = CartDataSpace<3, SpaceID>::gb_mesh_size
ghost_size
template<int SpaceID> std::vector<std::vector<int> >& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ghost_size = CartDataSpace<3, SpaceID>::ghost_size
ghostcomm
template<int SpaceID> gsmpi::CartFieldGhostComm<Real, 3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ghostcomm
ibm_flag
template<int SpaceID> int& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ibm_flag = CartDataSpace<3, SpaceID>::ibm_flag
kvisc
template<int SpaceID> Real solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::kvisc
lap
template<int SpaceID> blin::Arrayr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::lap
mesh_size
template<int SpaceID> std::vector<int>& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::mesh_size = CartDataSpace<3, SpaceID>::mesh_size
mpicomm
template<int SpaceID> gsmpi::GSMPICart<3>& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::mpicomm = CartDataSpace<3, SpaceID>::mpicomm
p
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::p
params
template<int SpaceID> std::vector<Real> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::params
Re
template<int SpaceID> Real solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Re
Retau
template<int SpaceID> Real solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::Retau
rwrk
template<int SpaceID> blin::Vec<blin::Arrayr<3>, 5> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::rwrk
rwrkf
template<int SpaceID> blin::Vec<blin::Arrayr<3>, 2> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::rwrkf
stagger_flag
template<int SpaceID> std::vector<std::vector<int> >& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::stagger_flag = CartDataSpace<3, SpaceID>::stagger_flag
stf
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::stf
stf2w
template<int SpaceID> int solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::stf2w
stp
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::stp
stp2w
template<int SpaceID> int solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::stp2w
tempfields
template<int SpaceID> std::vector<blockelm::CartField<Real, 3> *>& solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::tempfields = CartDataSpace<3, SpaceID>::tempfields
time_scheme
template<int SpaceID> boxffd::TimeScheme solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::time_scheme
u
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::u
us
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::us
utnew
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::utnew
utold
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::utold
v
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::v
vs
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::vs
vtnew
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::vtnew
vtold
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::vtold
w
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::w
work_path
template<int SpaceID> std::string solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::work_path
ws
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::ws
wtnew
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::wtnew
wtold
template<int SpaceID> blin::Arraycr<3> solver::fluidsol::CartBoxFFDSol< 3, SpaceID >::wtold
The documentation for this class was generated from the following files:
/mnt/e/linuxOS/PhyStar/Solver/FluidSol/SpecDiffHybrid/BoxFFD/CartBoxFFDSol.hpp
/mnt/e/linuxOS/PhyStar/Solver/FluidSol/SpecDiffHybrid/BoxFFD/CartBoxFFDSol.hxx