PhyStar: dmdyn::init::InitPartData< N_dim > Class Template Reference
dmdyn::init::InitPartData< N_dim > Class Template Reference
#include <InitPartData.hpp>
Public Member Functions
InitPartData ()
InitPartData (tml::table &partinfo, int &id)
~InitPartData ()
auto & setOverlapTag (const OverlapTag tag)
auto & setVelTag (const InitTag tag)
auto & setAngVelTag (const InitTag tag)
auto & setOrientTag (const InitTag tag)
auto & setEdges (const std::vector< std::vector< Real >> &domain_size0)
auto & setMaxNum (const int num)
auto getMaxNum ()
auto getSeedTag ()
auto getOrientTag ()
auto getVelTag ()
auto getAngVelTag ()
Real evalTotalVolume ()
bool evalConstraintFunction (blin::Vecr< N_dim > &pos)
Real testValidVolume (Real err=1e-5)
auto & generateFromRandomTool ()
auto & generateFromFile (std::string filename)
auto & generateFromFile ()
void updateOrientIfNecessary ()
void updateVelIfNecessary ()
void updateAngVelIfNecessary ()
void updateIfNecessary ()
Public Attributes
SmartPList< ParticleData< N_dim > > pdatalist
std::vector< CFunData > cfunlist
std::vector< std::string > oplist
Private Attributes
OverlapTag overlaptag_ = OverlapTag::OverLap
InitTag seedtag_ = InitTag::Random
InitTag veltag_ = InitTag::Local
std::vector< Real > velparams_
InitTag angveltag_ = InitTag::LocalFluidRotation
std::vector< Real > angvelparams_
InitTag orienttag_ = InitTag::Random
std::vector< Real > orientparams_
std::string filename_
Real edge_low_ [N_dim]
Real edge_up_ [N_dim]
Real total_vol_ = 0.0
Real valid_vol_frac = 0.0
int maxnum_ = 0
std::unordered_map< std::string, std::function< bool(bool, bool)> > ops
Constructor & Destructor Documentation
InitPartData() [1/2]
template<int N_dim> dmdyn::init::InitPartData< N_dim >::InitPartData () inline
InitPartData() [2/2]
template<int N_dim> dmdyn::init::InitPartData< N_dim >::InitPartData (tml::table & partinfo, int & id)
References dmdyn::init::FromFile, solver::database::partinfo, dmdyn::init::Random, dmdyn::init::Value, dmdyn::init::vConfigCFunTag(), dmdyn::init::vConfigInitTag(), and dmdyn::init::vConfigInsideOutside().
~InitPartData()
template<int N_dim> dmdyn::init::InitPartData< N_dim >::~InitPartData () inline
Member Function Documentation
evalConstraintFunction()
template<int N_dim> bool dmdyn::init::InitPartData< N_dim >::evalConstraintFunction (blin::Vecr< N_dim > & pos) inline
References dmdyn::init::InitPartData< N_dim >::cfunlist, dmdyn::init::InitPartData< N_dim >::oplist, and dmdyn::init::InitPartData< N_dim >::ops.
evalTotalVolume()
template<int N_dim> Real dmdyn::init::InitPartData< N_dim >::evalTotalVolume () inline
References dmdyn::init::InitPartData< N_dim >::edge_low_, and dmdyn::init::InitPartData< N_dim >::edge_up_.
generateFromFile() [1/2]
template<int N_dim> auto& dmdyn::init::InitPartData< N_dim >::generateFromFile () inline
References dmdyn::init::InitPartData< N_dim >::filename_.
generateFromFile() [2/2]
template<int N_dim> auto & dmdyn::init::InitPartData< N_dim >::generateFromFile (std::string filename)
References dmdyn::AddOnly, dmdyn::init::Box, dmdyn::init::In, and dmdyn::ReadOnly.
generateFromRandomTool()
template<int N_dim> auto & dmdyn::init::InitPartData< N_dim >::generateFromRandomTool
References dmdyn::AddOnly, dmdyn::angular::RandomR(), RandomNumber< T_real >::randr(), dmdyn::ReadOnly, and dmdyn::angular::RrightToee().
getAngVelTag()
template<int N_dim> auto dmdyn::init::InitPartData< N_dim >::getAngVelTag () inline
References dmdyn::init::InitPartData< N_dim >::angveltag_.
getMaxNum()
template<int N_dim> auto dmdyn::init::InitPartData< N_dim >::getMaxNum () inline
References dmdyn::init::InitPartData< N_dim >::maxnum_.
getOrientTag()
template<int N_dim> auto dmdyn::init::InitPartData< N_dim >::getOrientTag () inline
References dmdyn::init::InitPartData< N_dim >::orienttag_.
getSeedTag()
template<int N_dim> auto dmdyn::init::InitPartData< N_dim >::getSeedTag () inline
References dmdyn::init::InitPartData< N_dim >::seedtag_.
getVelTag()
template<int N_dim> auto dmdyn::init::InitPartData< N_dim >::getVelTag () inline
References dmdyn::init::InitPartData< N_dim >::veltag_.
setAngVelTag()
template<int N_dim> auto& dmdyn::init::InitPartData< N_dim >::setAngVelTag (const InitTag tag) inline
References dmdyn::init::InitPartData< N_dim >::angveltag_.
setEdges()
template<int N_dim> auto& dmdyn::init::InitPartData< N_dim >::setEdges (const std::vector< std::vector< Real >> & domain_size0) inline
References dmdyn::init::InitPartData< N_dim >::edge_low_, and dmdyn::init::InitPartData< N_dim >::edge_up_.
setMaxNum()
template<int N_dim> auto& dmdyn::init::InitPartData< N_dim >::setMaxNum (const int num) inline
References dmdyn::init::InitPartData< N_dim >::maxnum_.
setOrientTag()
template<int N_dim> auto& dmdyn::init::InitPartData< N_dim >::setOrientTag (const InitTag tag) inline
References dmdyn::init::InitPartData< N_dim >::orienttag_.
setOverlapTag()
template<int N_dim> auto& dmdyn::init::InitPartData< N_dim >::setOverlapTag (const OverlapTag tag) inline
References dmdyn::init::InitPartData< N_dim >::overlaptag_.
setVelTag()
template<int N_dim> auto& dmdyn::init::InitPartData< N_dim >::setVelTag (const InitTag tag) inline
References dmdyn::init::InitPartData< N_dim >::veltag_.
testValidVolume()
template<int N_dim> Real dmdyn::init::InitPartData< N_dim >::testValidVolume (Real err = 1e-5)
References quadpack::min(), and RandomNumber< T_real >::randr().
updateAngVelIfNecessary()
template<int N_dim> void dmdyn::init::InitPartData< N_dim >::updateAngVelIfNecessary
References dmdyn::init::Value.
updateIfNecessary()
template<int N_dim> void dmdyn::init::InitPartData< N_dim >::updateIfNecessary () inline
References dmdyn::init::InitPartData< N_dim >::updateAngVelIfNecessary(), dmdyn::init::InitPartData< N_dim >::updateOrientIfNecessary(), and dmdyn::init::InitPartData< N_dim >::updateVelIfNecessary().
updateOrientIfNecessary()
template<int N_dim> void dmdyn::init::InitPartData< N_dim >::updateOrientIfNecessary
References dmdyn::init::Value.
updateVelIfNecessary()
template<int N_dim> void dmdyn::init::InitPartData< N_dim >::updateVelIfNecessary
References dmdyn::init::Value.
Member Data Documentation
angvelparams_
template<int N_dim> std::vector<Real> dmdyn::init::InitPartData< N_dim >::angvelparams_ private
angveltag_
template<int N_dim> InitTag dmdyn::init::InitPartData< N_dim >::angveltag_ = InitTag::LocalFluidRotation private
cfunlist
template<int N_dim> std::vector<CFunData> dmdyn::init::InitPartData< N_dim >::cfunlist
edge_low_
template<int N_dim> Real dmdyn::init::InitPartData< N_dim >::edge_low_[N_dim] private
edge_up_
template<int N_dim> Real dmdyn::init::InitPartData< N_dim >::edge_up_[N_dim] private
filename_
template<int N_dim> std::string dmdyn::init::InitPartData< N_dim >::filename_ private
maxnum_
template<int N_dim> int dmdyn::init::InitPartData< N_dim >::maxnum_ = 0 private
oplist
template<int N_dim> std::vector<std::string> dmdyn::init::InitPartData< N_dim >::oplist
ops
template<int N_dim> std::unordered_map<std::string, std::function<bool(bool, bool)> > dmdyn::init::InitPartData< N_dim >::ops private
Initial value:
= {
            {"AND", [](bool a, bool b)
             { return a & b; }},
            {"OR", [](bool a, bool b)
             { return a | b; }},
            {"XOR", [](bool a, bool b)
             { return a ^ b; }},
        }
orientparams_
template<int N_dim> std::vector<Real> dmdyn::init::InitPartData< N_dim >::orientparams_ private
orienttag_
template<int N_dim> InitTag dmdyn::init::InitPartData< N_dim >::orienttag_ = InitTag::Random private
overlaptag_
template<int N_dim> OverlapTag dmdyn::init::InitPartData< N_dim >::overlaptag_ = OverlapTag::OverLap private
pdatalist
template<int N_dim> SmartPList<ParticleData<N_dim> > dmdyn::init::InitPartData< N_dim >::pdatalist
seedtag_
template<int N_dim> InitTag dmdyn::init::InitPartData< N_dim >::seedtag_ = InitTag::Random private
total_vol_
template<int N_dim> Real dmdyn::init::InitPartData< N_dim >::total_vol_ = 0.0 private
valid_vol_frac
template<int N_dim> Real dmdyn::init::InitPartData< N_dim >::valid_vol_frac = 0.0 private
velparams_
template<int N_dim> std::vector<Real> dmdyn::init::InitPartData< N_dim >::velparams_ private
veltag_
template<int N_dim> InitTag dmdyn::init::InitPartData< N_dim >::veltag_ = InitTag::Local private
The documentation for this class was generated from the following files:
/mnt/e/linuxOS/PhyStar/DMDyn/Initialization/InitPartData.hpp
/mnt/e/linuxOS/PhyStar/DMDyn/Initialization/InitPartData.hxx