PhyStar: fileio Namespace Reference
fileio Namespace Reference
Classes
class FluidCartRegularD
fluid io for cartesian coordinates, double percision
struct IOPData
class PointParticleCartRegularD
particle io for cartesian coordinates, double percision
Typedefs
using IOPData3DBasicD = IOPData< 16, double, 3, unsigned int >
using IOPData2DBasicD = IOPData< 9, double, 3, unsigned int >
using IOPData3DOnlyFluidD = IOPData< 12, double, 3, unsigned int >
using IOPData2DOnlyFluidD = IOPData< 6, double, 3, unsigned int >
Enumerations
enum class FileTag { Default = 0 , WithoutGhost }
enum FluidGroup {
kFileProp = 0 , kGeoMesh , kPhysPara , kOtherInfo ,
kField
}
Functions
const auto FileProps ("/0-FileProps")
const auto DataSpace ("/1-DataSpace")
const auto PhysParams ("/2-PhysParams")
const auto Others ("/3-Others")
const auto Fields ("/4-Fields")
template<typename T_real = double>
static auto CreateComplexCompound ()
static void DestroyCompound (hid_t mytypeid)
static auto CreatePointParticleCompound (auto &pdata)
std::string & strToUpper (std::string &str)
std::string & strToLower (std::string &str)
std::string intTostr (int i, int size=7)
void AddAttribute (const hid_t id, const std::string attrname, const std::string strattr)
void AddAttribute (const hid_t id, const std::string attrname, const int intdata[], const int n)
void AddAttribute (const hid_t id, const std::string attrname, const double data[], const int n)
void AddAttribute (const hid_t id, const std::string attrname, const double data)
void AddAttribute (const hid_t id, const std::string attrname, const int intdata)
void AddAttribute (const hid_t id, const std::string attrname, const hsize_t intdata)
void AddDataSet (const hid_t id, const std::string dataname, const int intdata[], const int n)
void AddDataSet (const hid_t id, const std::string dataname, const unsigned long long intdata[], const int n)
void AddDataSet (const hid_t id, const std::string dataname, const double data[], const int n)
void AddDataSet (const hid_t id, const std::string dataname, const int intdata[], const int n0, const int n1)
void AddDataSet (const hid_t id, const std::string dataname, const double data[], const int n0, const int n1)
void AddDataSet (const hid_t id, const std::string dataname, const int intdata[], const int n0, const int n1, const int n2)
void AddDataSet (const hid_t id, const std::string dataname, const double data[], const int n0, const int n1, const int n2)
template<typename T_real >
void AddDataSetCplx (const hid_t id, const std::string dataname, const std::complex< T_real > data[], const int n0, const int n1, const int n2)
template<typename T_real >
void AddDataSetCplx (const hid_t id, const std::string dataname, const std::complex< T_real > data[], const int n0, const int n1)
template<typename T_real >
void AddDataSetCplx (const hid_t id, const std::string dataname, const std::complex< T_real > data[], const int n0)
auto ReadStringAttribute (const hid_t id, const std::string attrname)
void ReadAttribute (const hid_t id, const std::string attrname, int intdata[])
void ReadAttribute (const hid_t id, const std::string attrname, double data[])
void ReadDataSet (const hid_t id, const std::string dataname, int intdata[])
void ReadDataSet (const hid_t id, const std::string dataname, unsigned long long intdata[])
void ReadDataSet (const hid_t id, const std::string dataname, double data[])
const auto PPFileProps ("/0-FileProps")
const auto PPTypes ("/1-PartTypes")
const auto PPOthers ("/2-Others")
const auto PPFields ("/3-Fields")
Typedef Documentation
IOPData2DBasicD
using fileio::IOPData2DBasicD = typedef IOPData<9, double, 3, unsigned int>
IOPData2DOnlyFluidD
using fileio::IOPData2DOnlyFluidD = typedef IOPData<6, double, 3, unsigned int>
IOPData3DBasicD
using fileio::IOPData3DBasicD = typedef IOPData<16, double, 3, unsigned int>
IOPData3DOnlyFluidD
using fileio::IOPData3DOnlyFluidD = typedef IOPData<12, double, 3, unsigned int>
Enumeration Type Documentation
FileTag
enum fileio::FileTag strong
Enumerator
Default
WithoutGhost
FluidGroup
enum fileio::FluidGroup
Enumerator
kFileProp
kGeoMesh
kPhysPara
kOtherInfo
kField
Function Documentation
AddAttribute() [1/6]
void fileio::AddAttribute (const hid_t id, const std::string attrname, const double data) inline
AddAttribute() [2/6]
void fileio::AddAttribute (const hid_t id, const std::string attrname, const double data[], const int n) inline
AddAttribute() [3/6]
void fileio::AddAttribute (const hid_t id, const std::string attrname, const hsize_t intdata) inline
AddAttribute() [4/6]
void fileio::AddAttribute (const hid_t id, const std::string attrname, const int intdata) inline
AddAttribute() [5/6]
void fileio::AddAttribute (const hid_t id, const std::string attrname, const int intdata[], const int n) inline
AddAttribute() [6/6]
void fileio::AddAttribute (const hid_t id, const std::string attrname, const std::string strattr) inline
AddDataSet() [1/7]
void fileio::AddDataSet (const hid_t id, const std::string dataname, const double data[], const int n) inline
AddDataSet() [2/7]
void fileio::AddDataSet (const hid_t id, const std::string dataname, const double data[], const int n0, const int n1) inline
AddDataSet() [3/7]
void fileio::AddDataSet (const hid_t id, const std::string dataname, const double data[], const int n0, const int n1, const int n2) inline
AddDataSet() [4/7]
void fileio::AddDataSet (const hid_t id, const std::string dataname, const int intdata[], const int n) inline
AddDataSet() [5/7]
void fileio::AddDataSet (const hid_t id, const std::string dataname, const int intdata[], const int n0, const int n1) inline
AddDataSet() [6/7]
void fileio::AddDataSet (const hid_t id, const std::string dataname, const int intdata[], const int n0, const int n1, const int n2) inline
AddDataSet() [7/7]
void fileio::AddDataSet (const hid_t id, const std::string dataname, const unsigned long long intdata[], const int n) inline
AddDataSetCplx() [1/3]
template<typename T_real > void fileio::AddDataSetCplx (const hid_t id, const std::string dataname, const std::complex< T_real > data[], const int n0) inline
References DestroyCompound().
AddDataSetCplx() [2/3]
template<typename T_real > void fileio::AddDataSetCplx (const hid_t id, const std::string dataname, const std::complex< T_real > data[], const int n0, const int n1) inline
References DestroyCompound().
AddDataSetCplx() [3/3]
template<typename T_real > void fileio::AddDataSetCplx (const hid_t id, const std::string dataname, const std::complex< T_real > data[], const int n0, const int n1, const int n2) inline
References DestroyCompound().
CreateComplexCompound()
template<typename T_real = double> static auto fileio::CreateComplexCompound () inline static
CreatePointParticleCompound()
static auto fileio::CreatePointParticleCompound (auto & pdata) inline static
DataSpace()
const auto fileio::DataSpace ("/1-DataSpace")
DestroyCompound()
static void fileio::DestroyCompound (hid_t mytypeid) inline static
Fields()
const auto fileio::Fields ("/4-Fields")
FileProps()
const auto fileio::FileProps ("/0-FileProps")
intTostr()
std::string fileio::intTostr (int i, int size = 7) inline
Others()
const auto fileio::Others ("/3-Others")
PhysParams()
const auto fileio::PhysParams ("/2-PhysParams")
PPFields()
const auto fileio::PPFields ("/3-Fields")
PPFileProps()
const auto fileio::PPFileProps ("/0-FileProps")
PPOthers()
const auto fileio::PPOthers ("/2-Others")
PPTypes()
const auto fileio::PPTypes ("/1-PartTypes")
ReadAttribute() [1/2]
void fileio::ReadAttribute (const hid_t id, const std::string attrname, double data[]) inline
ReadAttribute() [2/2]
void fileio::ReadAttribute (const hid_t id, const std::string attrname, int intdata[]) inline
ReadDataSet() [1/3]
void fileio::ReadDataSet (const hid_t id, const std::string dataname, double data[]) inline
ReadDataSet() [2/3]
void fileio::ReadDataSet (const hid_t id, const std::string dataname, int intdata[]) inline
ReadDataSet() [3/3]
void fileio::ReadDataSet (const hid_t id, const std::string dataname, unsigned long long intdata[]) inline
ReadStringAttribute()
auto fileio::ReadStringAttribute (const hid_t id, const std::string attrname) inline
strToLower()
std::string& fileio::strToLower (std::string & str) inline
strToUpper()
std::string& fileio::strToUpper (std::string & str) inline