PhyStar: /mnt/e/linuxOS/PhyStar/Apps/cartboxfdmDuct/duct.cpp File Reference
duct.cpp File Reference
#include <iostream>
#include "solver/CartBoxFDMDuct.h"
Functions
int main ()
Function Documentation
main()
int main ()
References solver::CartDataSpace< N_dim, SpaceID >::ConfigDataSpaceDict(), CartBoxFDMDuct::ConfigFlowDict(), solver::Solver::ConfigGlobalDict(), solver::Solver::Dt(), solver::Solver::GetMeshName(), solver::Solver::GetSolverName(), solver::Solver::GlobalDict(), solver::fluidsol::FluidSolBase::Init(), CartBoxFDMDuct::InitStatLogFile(), solver::CartDataSpace< N_dim, SpaceID >::mpicomm, solver::Solver::PrintAbstract(), solver::Solver::PrintConfigGlobalDict(), gsmpi::root, solver::fluidsol::FluidSolBase::Solve(), CartBoxFDMDuct::Statistic(), CartBoxFDMDuct::StatLog(), and solver::fluidsol::FluidSolBase::WriteFields().