PhyStar: /mnt/e/linuxOS/PhyStar/Apps/smartParticlesSimpleFlow/spsf3d.cpp File Reference
spsf3d.cpp File Reference
#include <iostream>
#include "FluidSol/FLUIDSOL.H"
#include "PPSol/PPSOL.H"
Functions
int main ()
Function Documentation
main()
int main ()
References solver::ppsol::CartSmartPPSol< N_dim >::ActorTakeAction(), solver::ppsol::CartSmartPPSol< N_dim >::AgentDecideAction(), solver::CartDataSpace< N_dim, SpaceID >::ConfigDataSpaceDict(), solver::fluidsol::SimCartFlow< N_dim, SpaceID >::ConfigFlowDict(), solver::Solver::ConfigGlobalDict(), solver::ppsol::CartPPSol< N_dim, SpaceID >::ConfigPPDict(), solver::Solver::Dt(), solver::Solver::GlobalDict(), solver::fluidsol::SimCartFlow< N_dim, SpaceID >::Init(), solver::ppsol::CartPPSol< N_dim, SpaceID >::Init(), solver::ppsol::CartPPSol< N_dim, SpaceID >::InitStatLogFile(), solver::fluidsol::SimCartFlow< N_dim, SpaceID >::mpicomm, solver::ppsol::CartSmartPPSol< N_dim >::Prepare(), solver::Solver::PrintAbstract(), solver::Solver::PrintConfigGlobalDict(), gsmpi::root, solver::ppsol::CartPPSol< N_dim, SpaceID >::ScatterOutput(), solver::ppsol::CartSmartPPSol< N_dim >::SensorGetState(), solver::ppsol::CartPPSol< N_dim, SpaceID >::SetMPI(), solver::ppsol::CartPPSol< N_dim, SpaceID >::Solve(), solver::fluidsol::SimCartFlow< N_dim, SpaceID >::Solve(), solver::ppsol::CartPPSol< N_dim, SpaceID >::Statistic(), solver::fluidsol::SimCartFlow< N_dim, SpaceID >::WriteFields(), solver::ppsol::CartPPSol< N_dim, SpaceID >::WriteMidPPFields(), and solver::ppsol::CartPPSol< N_dim, SpaceID >::WritePPFields().