PhyStar: fileio::PointParticleCartRegularD< N_dim > Class Template Reference
fileio::PointParticleCartRegularD< N_dim > Class Template Reference
particle io for cartesian coordinates, double percision
#include <PointParticleIO.hpp>
Public Member Functions
PointParticleCartRegularD ()
Construct a new Fluid Cart Regular D object.
~PointParticleCartRegularD ()
Destroy the Fluid Cart Regular D object.
auto & SetFileAttr (std::string name, std::string val)
Set the File Attributes object not to create attribute, just set the standard attribute to the buffer in current object.
void Print ()
Print the abstract of the current file attributes.
auto CreateFile (const int istep, const std::string ftype)
Create a hdf5 File.
void CloseFile ()
Close opened hdf5 file.
auto & AddPPField (const std::string fieldname, auto data[], long unsigned int len)
auto & AddPPField (const std::string fieldname, auto &vecdata)
auto OpenFile (const int istep, const std::string ftype)
auto & ReadPPField (const std::string fieldname, auto &vecdata)
Public Attributes
hid_t fileid
handles of HDF5
hid_t filepropid
hid_t parttypeid
hid_t otherinfoid
hid_t fieldid
Private Attributes
const int _dim = N_dim
std::string _casename = "default"
std::string _filestyle = "onestep"
std::string _filepath = "./"
std::string _filenameprefix = "ppfield"
int _numbernamelength = 7
long unsigned long * _count = nullptr
long unsigned long * _displacement = nullptr
int _proc = 1
int _rank = 0
Detailed Description
template<int N_dim>
class fileio::PointParticleCartRegularD< N_dim >
particle io for cartesian coordinates, double percision
Constructor & Destructor Documentation
PointParticleCartRegularD()
template<int N_dim> fileio::PointParticleCartRegularD< N_dim >::PointParticleCartRegularD () inline
Construct a new Fluid Cart Regular D object.
~PointParticleCartRegularD()
template<int N_dim> fileio::PointParticleCartRegularD< N_dim >::~PointParticleCartRegularD () inline
Destroy the Fluid Cart Regular D object.
References fileio::PointParticleCartRegularD< N_dim >::_count, and fileio::PointParticleCartRegularD< N_dim >::_displacement.
Member Function Documentation
AddPPField() [1/2]
template<int N_dim> auto & fileio::PointParticleCartRegularD< N_dim >::AddPPField (const std::string fieldname, auto & vecdata)
References fileio::AddAttribute(), fileio::AddDataSet(), fileio::CreatePointParticleCompound(), and fileio::DestroyCompound().
AddPPField() [2/2]
template<int N_dim> auto & fileio::PointParticleCartRegularD< N_dim >::AddPPField (const std::string fieldname, auto data[], long unsigned int len)
References fileio::AddAttribute(), fileio::AddDataSet(), and fileio::DestroyCompound().
CloseFile()
template<int N_dim> void fileio::PointParticleCartRegularD< N_dim >::CloseFile
Close opened hdf5 file.
CreateFile()
template<int N_dim> auto fileio::PointParticleCartRegularD< N_dim >::CreateFile (const int istep, const std::string ftype)
Create a hdf5 File.
Parameters
istep computation step
ftype select a file style, onestep/mid
Returns
auto id of opened file
References fileio::AddAttribute(), fileio::intTostr(), fileio::PPFields(), fileio::PPFileProps(), fileio::PPOthers(), and fileio::PPTypes().
OpenFile()
template<int N_dim> auto fileio::PointParticleCartRegularD< N_dim >::OpenFile (const int istep, const std::string ftype)
References fileio::intTostr(), fileio::PPFields(), fileio::PPFileProps(), fileio::PPOthers(), fileio::PPTypes(), fileio::ReadAttribute(), and fileio::ReadStringAttribute().
Print()
template<int N_dim> void fileio::PointParticleCartRegularD< N_dim >::Print
Print the abstract of the current file attributes.
References fileio::intTostr().
ReadPPField()
template<int N_dim> auto & fileio::PointParticleCartRegularD< N_dim >::ReadPPField (const std::string fieldname, auto & vecdata)
References fileio::ReadDataSet().
SetFileAttr()
template<int N_dim> auto& fileio::PointParticleCartRegularD< N_dim >::SetFileAttr (std::string name, std::string val) inline
Set the File Attributes object not to create attribute, just set the standard attribute to the buffer in current object.
Parameters
name attribute name
val attribute value
Returns
auto& *this
References fileio::PointParticleCartRegularD< N_dim >::_casename, fileio::PointParticleCartRegularD< N_dim >::_filenameprefix, fileio::PointParticleCartRegularD< N_dim >::_filepath, fileio::PointParticleCartRegularD< N_dim >::_filestyle, and fileio::strToLower().
Member Data Documentation
_casename
template<int N_dim> std::string fileio::PointParticleCartRegularD< N_dim >::_casename = "default" private
_count
template<int N_dim> long unsigned long* fileio::PointParticleCartRegularD< N_dim >::_count = nullptr private
_dim
template<int N_dim> const int fileio::PointParticleCartRegularD< N_dim >::_dim = N_dim private
_displacement
template<int N_dim> long unsigned long* fileio::PointParticleCartRegularD< N_dim >::_displacement = nullptr private
_filenameprefix
template<int N_dim> std::string fileio::PointParticleCartRegularD< N_dim >::_filenameprefix = "ppfield" private
_filepath
template<int N_dim> std::string fileio::PointParticleCartRegularD< N_dim >::_filepath = "./" private
_filestyle
template<int N_dim> std::string fileio::PointParticleCartRegularD< N_dim >::_filestyle = "onestep" private
_numbernamelength
template<int N_dim> int fileio::PointParticleCartRegularD< N_dim >::_numbernamelength = 7 private
_proc
template<int N_dim> int fileio::PointParticleCartRegularD< N_dim >::_proc = 1 private
_rank
template<int N_dim> int fileio::PointParticleCartRegularD< N_dim >::_rank = 0 private
fieldid
template<int N_dim> hid_t fileio::PointParticleCartRegularD< N_dim >::fieldid
fileid
template<int N_dim> hid_t fileio::PointParticleCartRegularD< N_dim >::fileid
handles of HDF5
filepropid
template<int N_dim> hid_t fileio::PointParticleCartRegularD< N_dim >::filepropid
otherinfoid
template<int N_dim> hid_t fileio::PointParticleCartRegularD< N_dim >::otherinfoid
parttypeid
template<int N_dim> hid_t fileio::PointParticleCartRegularD< N_dim >::parttypeid
The documentation for this class was generated from the following file:
/mnt/e/linuxOS/PhyStar/IO/FileIO/PointParticleIO.hpp