PhyStar: ibm::mshio::GmshReader< N_dim, T_real > Struct Template Reference
ibm::mshio::GmshReader< N_dim, T_real > Struct Template Reference
#include <GmshReader.hpp>
Classes
struct Elm
struct Node
Public Member Functions
GmshReader ()
auto Read (std::string filename, bool isline=false)
void MeshFormatRead (std::ifstream &fin)
void NodesRead (std::ifstream &fin)
void ElmsRead (std::ifstream &fin)
auto Print ()
auto Centroid ()
T_real MeanArea ()
T_real Distance (T_real n0[], T_real n1[], int dim=N_dim)
Public Attributes
std::vector< Node > nodelist
std::vector< Elm > elmlist
int num_of_nodes = 0
int num_of_elms = 0
bool is_3dline = 0
Static Public Attributes
static constexpr bool IS3DLINE = true
static constexpr bool ISNOT3DLINE = false
Constructor & Destructor Documentation
GmshReader()
template<int N_dim, typename T_real = double> ibm::mshio::GmshReader< N_dim, T_real >::GmshReader () inline
References ibm::mshio::GmshReader< N_dim, T_real >::elmlist, and ibm::mshio::GmshReader< N_dim, T_real >::nodelist.
Member Function Documentation
Centroid()
template<int N_dim, typename T_real = double> auto ibm::mshio::GmshReader< N_dim, T_real >::Centroid () inline
References ibm::mshio::GmshReader< N_dim, T_real >::Distance(), ibm::mshio::GmshReader< N_dim, T_real >::elmlist, and ibm::mshio::GmshReader< N_dim, T_real >::nodelist.
Distance()
template<int N_dim, typename T_real = double> T_real ibm::mshio::GmshReader< N_dim, T_real >::Distance (T_real n0[], T_real n1[], int dim = N_dim) inline
ElmsRead()
template<int N_dim, typename T_real = double> void ibm::mshio::GmshReader< N_dim, T_real >::ElmsRead (std::ifstream & fin) inline
References ibm::mshio::GmshReader< N_dim, T_real >::Centroid(), ibm::mshio::GmshReader< N_dim, T_real >::elmlist, ibm::mshio::GmshGetline(), ibm::mshio::GmshReader< N_dim, T_real >::Elm::id, ibm::mshio::GmshReader< N_dim, T_real >::is_3dline, ibm::mshio::GmshReader< N_dim, T_real >::Elm::nodeid, ibm::mshio::GmshReader< N_dim, T_real >::nodelist, ibm::mshio::GmshReader< N_dim, T_real >::num_of_elms, and ibm::mshio::GmshReader< N_dim, T_real >::Elm::type.
MeanArea()
template<int N_dim, typename T_real = double> T_real ibm::mshio::GmshReader< N_dim, T_real >::MeanArea () inline
References ibm::mshio::GmshReader< N_dim, T_real >::elmlist.
MeshFormatRead()
template<int N_dim, typename T_real = double> void ibm::mshio::GmshReader< N_dim, T_real >::MeshFormatRead (std::ifstream & fin) inline
References ibm::mshio::GmshGetline().
NodesRead()
template<int N_dim, typename T_real = double> void ibm::mshio::GmshReader< N_dim, T_real >::NodesRead (std::ifstream & fin) inline
References ibm::mshio::GmshGetline(), ibm::mshio::GmshReader< N_dim, T_real >::Node::id, ibm::mshio::GmshReader< N_dim, T_real >::nodelist, ibm::mshio::GmshReader< N_dim, T_real >::num_of_nodes, and ibm::mshio::GmshReader< N_dim, T_real >::Node::pos.
Print()
template<int N_dim, typename T_real = double> auto ibm::mshio::GmshReader< N_dim, T_real >::Print () inline
References ibm::mshio::GmshReader< N_dim, T_real >::elmlist, ibm::mshio::GmshReader< N_dim, T_real >::nodelist, ibm::mshio::GmshReader< N_dim, T_real >::num_of_elms, and ibm::mshio::GmshReader< N_dim, T_real >::num_of_nodes.
Read()
template<int N_dim, typename T_real = double> auto ibm::mshio::GmshReader< N_dim, T_real >::Read (std::string filename, bool isline = false) inline
References ibm::mshio::GmshReader< N_dim, T_real >::ElmsRead(), ibm::mshio::GmshGetline(), ibm::mshio::GmshReader< N_dim, T_real >::is_3dline, ibm::mshio::GmshReader< N_dim, T_real >::MeshFormatRead(), and ibm::mshio::GmshReader< N_dim, T_real >::NodesRead().
Member Data Documentation
elmlist
template<int N_dim, typename T_real = double> std::vector<Elm> ibm::mshio::GmshReader< N_dim, T_real >::elmlist
IS3DLINE
template<int N_dim, typename T_real = double> constexpr bool ibm::mshio::GmshReader< N_dim, T_real >::IS3DLINE = true inline static constexpr
is_3dline
template<int N_dim, typename T_real = double> bool ibm::mshio::GmshReader< N_dim, T_real >::is_3dline = 0
ISNOT3DLINE
template<int N_dim, typename T_real = double> constexpr bool ibm::mshio::GmshReader< N_dim, T_real >::ISNOT3DLINE = false inline static constexpr
nodelist
template<int N_dim, typename T_real = double> std::vector<Node> ibm::mshio::GmshReader< N_dim, T_real >::nodelist
num_of_elms
template<int N_dim, typename T_real = double> int ibm::mshio::GmshReader< N_dim, T_real >::num_of_elms = 0
num_of_nodes
template<int N_dim, typename T_real = double> int ibm::mshio::GmshReader< N_dim, T_real >::num_of_nodes = 0
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/IBM/IBMeshIO/GmshReader.hpp