PhyStar: blockelm::CartBoundary< T, N_dim > Class Template Reference
blockelm::CartBoundary< T, N_dim > Class Template Reference
#include <CartBoundary.hpp>
Public Member Functions
CartBoundary ()
CartBoundary (BoundaryData< T > &bdata)
~CartBoundary ()
void SetBoundaryType (BoundaryData< T > &bdata)
CartBoundary< T, N_dim > & CreateBoundaryFromFieldExcludeData (int dim_flg, CartField< T, N_dim > &field, BoundaryData< T > &bdata)
create a CartBoundary from an existing cartmesh, including the ghost mesh
CartBoundary< T, N_dim > & CopyExcludeData (const CartBoundary< T, N_dim > &bound)
CartBoundary< T, N_dim > & Copy (const CartBoundary< T, N_dim > &bound)
CartBoundary< T, N_dim > & SetVals ()
CartBoundary< T, N_dim > & SetVals (T val)
CartBoundary< T, N_dim > & SetVals (Array< T, N_dim - 1 > &val)
CartBoundary< T, N_dim > & SetVals (BFunc2D pfun, std::vector< T > &params)
CartBoundary< T, N_dim > & SetVals (BFunc1D pfun, std::vector< T > &params)
const CartMesh< N_dim > & GetMesh () const
const Array1r & GetMesh (int dir)
const int & GetGhostLow (int dir)
const int & GetGhostUp (int dir)
Real * PtrData ()
std::vector< int > GetShape ()
Get the shape of the field, including the ghost part.
std::vector< int > GetFlag ()
Get the Flag of the mesh, center or face.
constexpr int GetNdim () const
T atGBIndex (int i)
T atGBIndex (int i, int j)
T Val (int i)
T Val (int i, int j)
Array< T, N_dim > Val (Range range1)
Array< T, N_dim > Val (Range range1, Range range2)
Public Attributes
bool status = false
BoundaryType boundtype = BoundaryType::None
BFunType bfuntype
T val
std::vector< T > params
Array< T, N_dim - 1 > data
Veci< N_dim - 1 > shape
Veci< N_dim - 1 > flag
CartMesh< N_dim > * ptr_mesh = nullptr
Veci< N_dim > & st_ind = ptr_mesh->st_ind
Private Member Functions
void setDimFlag (int flag)
Private Attributes
int _dim_flag
Veci< N_dim - 1 > _other_dim_flags
Constructor & Destructor Documentation
CartBoundary() [1/2]
template<typename T , int N_dim> blockelm::CartBoundary< T, N_dim >::CartBoundary () inline
CartBoundary() [2/2]
template<typename T , int N_dim> blockelm::CartBoundary< T, N_dim >::CartBoundary (BoundaryData< T > & bdata) inline
References blockelm::CartBoundary< T, N_dim >::SetBoundaryType().
~CartBoundary()
template<typename T , int N_dim> blockelm::CartBoundary< T, N_dim >::~CartBoundary () inline
Member Function Documentation
atGBIndex() [1/2]
template<typename T , int N_dim> T blockelm::CartBoundary< T, N_dim >::atGBIndex (int i) inline
References blockelm::CartBoundary< T, N_dim >::_other_dim_flags, blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::st_ind, and blockelm::CartBoundary< T, N_dim >::status.
atGBIndex() [2/2]
template<typename T , int N_dim> T blockelm::CartBoundary< T, N_dim >::atGBIndex (int i, int j) inline
References blockelm::CartBoundary< T, N_dim >::_other_dim_flags, blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::st_ind, and blockelm::CartBoundary< T, N_dim >::status.
Copy()
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::Copy (const CartBoundary< T, N_dim > & bound) inline
References blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::flag, blockelm::CartBoundary< T, N_dim >::ptr_mesh, and blockelm::CartBoundary< T, N_dim >::shape.
CopyExcludeData()
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::CopyExcludeData (const CartBoundary< T, N_dim > & bound) inline
References blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::flag, blockelm::CartBoundary< T, N_dim >::ptr_mesh, and blockelm::CartBoundary< T, N_dim >::shape.
CreateBoundaryFromFieldExcludeData()
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::CreateBoundaryFromFieldExcludeData (int dim_flg, CartField< T, N_dim > & field, BoundaryData< T > & bdata) inline
create a CartBoundary from an existing cartmesh, including the ghost mesh
Parameters
fls flags, center or face
pmsh mesh
Returns
CartField<T,N_dim>&
References blockelm::CartBoundary< T, N_dim >::_other_dim_flags, blockelm::BoundaryData< T >::btype, blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::flag, blockelm::CartField< T, N_dim >::flag, blockelm::kcenter, blockelm::None, blockelm::CartBoundary< T, N_dim >::ptr_mesh, blockelm::CartField< T, N_dim >::ptr_mesh, blockelm::CartBoundary< T, N_dim >::SetBoundaryType(), blockelm::CartBoundary< T, N_dim >::setDimFlag(), blockelm::CartBoundary< T, N_dim >::shape, and blockelm::CartBoundary< T, N_dim >::status.
GetFlag()
template<typename T , int N_dim> std::vector<int> blockelm::CartBoundary< T, N_dim >::GetFlag () inline
Get the Flag of the mesh, center or face.
Returns
References blockelm::CartBoundary< T, N_dim >::flag.
GetGhostLow()
template<typename T , int N_dim> const int& blockelm::CartBoundary< T, N_dim >::GetGhostLow (int dir) inline
References blockelm::CartBoundary< T, N_dim >::_other_dim_flags, and blockelm::CartBoundary< T, N_dim >::ptr_mesh.
GetGhostUp()
template<typename T , int N_dim> const int& blockelm::CartBoundary< T, N_dim >::GetGhostUp (int dir) inline
References blockelm::CartBoundary< T, N_dim >::_other_dim_flags, and blockelm::CartBoundary< T, N_dim >::ptr_mesh.
GetMesh() [1/2]
template<typename T , int N_dim> const CartMesh<N_dim>& blockelm::CartBoundary< T, N_dim >::GetMesh () const inline
References blockelm::CartBoundary< T, N_dim >::ptr_mesh.
GetMesh() [2/2]
template<typename T , int N_dim> const Array1r& blockelm::CartBoundary< T, N_dim >::GetMesh (int dir) inline
References blockelm::CartBoundary< T, N_dim >::_other_dim_flags, blockelm::CartBoundary< T, N_dim >::flag, and blockelm::CartBoundary< T, N_dim >::ptr_mesh.
GetNdim()
template<typename T , int N_dim> constexpr int blockelm::CartBoundary< T, N_dim >::GetNdim () const inline constexpr
GetShape()
template<typename T , int N_dim> std::vector<int> blockelm::CartBoundary< T, N_dim >::GetShape () inline
Get the shape of the field, including the ghost part.
Returns
References blockelm::CartBoundary< T, N_dim >::shape.
PtrData()
template<typename T , int N_dim> Real* blockelm::CartBoundary< T, N_dim >::PtrData () inline
References blockelm::CartBoundary< T, N_dim >::data.
SetBoundaryType()
template<typename T , int N_dim> void blockelm::CartBoundary< T, N_dim >::SetBoundaryType (BoundaryData< T > & bdata) inline
References blockelm::BoundaryData< T >::bfun, blockelm::CartBoundary< T, N_dim >::bfuntype, blockelm::CartBoundary< T, N_dim >::boundtype, blockelm::BoundaryData< T >::btype, blockelm::BoundaryData< T >::params, blockelm::CartBoundary< T, N_dim >::params, blockelm::BoundaryData< T >::val, and blockelm::CartBoundary< T, N_dim >::val.
setDimFlag()
template<typename T , int N_dim> void blockelm::CartBoundary< T, N_dim >::setDimFlag (int flag) inline private
References blockelm::CartBoundary< T, N_dim >::_dim_flag, blockelm::CartBoundary< T, N_dim >::_other_dim_flags, and blockelm::CartBoundary< T, N_dim >::flag.
SetVals() [1/5]
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::SetVals () inline
References blockelm::CartBoundary< T, N_dim >::bfuntype, blockelm::LaminarCircPipe, blockelm::LaminarCircPipeAddNoise, blockelm::CartBoundary< T, N_dim >::params, blockelm::CartBoundary< T, N_dim >::status, blockelm::BoundaryFunction::TwoDim(), blockelm::Uniform, and blockelm::CartBoundary< T, N_dim >::val.
SetVals() [2/5]
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::SetVals (Array< T, N_dim - 1 > & val) inline
References blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::status, and blockelm::CartBoundary< T, N_dim >::val.
SetVals() [3/5]
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::SetVals (BFunc1D pfun, std::vector< T > & params) inline
References blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::GetMesh(), blockelm::CartBoundary< T, N_dim >::params, and blockelm::CartBoundary< T, N_dim >::status.
SetVals() [4/5]
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::SetVals (BFunc2D pfun, std::vector< T > & params) inline
References blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::GetMesh(), blockelm::CartBoundary< T, N_dim >::params, and blockelm::CartBoundary< T, N_dim >::status.
SetVals() [5/5]
template<typename T , int N_dim> CartBoundary<T, N_dim>& blockelm::CartBoundary< T, N_dim >::SetVals (T val) inline
References blockelm::CartBoundary< T, N_dim >::data, blockelm::CartBoundary< T, N_dim >::status, and blockelm::CartBoundary< T, N_dim >::val.
Val() [1/4]
template<typename T , int N_dim> T blockelm::CartBoundary< T, N_dim >::Val (int i) inline
References blockelm::CartBoundary< T, N_dim >::data, and blockelm::CartBoundary< T, N_dim >::status.
Val() [2/4]
template<typename T , int N_dim> T blockelm::CartBoundary< T, N_dim >::Val (int i, int j) inline
References blockelm::CartBoundary< T, N_dim >::data, and blockelm::CartBoundary< T, N_dim >::status.
Val() [3/4]
template<typename T , int N_dim> Array<T, N_dim> blockelm::CartBoundary< T, N_dim >::Val (Range range1) inline
References blockelm::CartBoundary< T, N_dim >::data, and blockelm::CartBoundary< T, N_dim >::status.
Val() [4/4]
template<typename T , int N_dim> Array<T, N_dim> blockelm::CartBoundary< T, N_dim >::Val (Range range1, Range range2) inline
References blockelm::CartBoundary< T, N_dim >::data, and blockelm::CartBoundary< T, N_dim >::status.
Member Data Documentation
_dim_flag
template<typename T , int N_dim> int blockelm::CartBoundary< T, N_dim >::_dim_flag private
_other_dim_flags
template<typename T , int N_dim> Veci<N_dim - 1> blockelm::CartBoundary< T, N_dim >::_other_dim_flags private
bfuntype
template<typename T , int N_dim> BFunType blockelm::CartBoundary< T, N_dim >::bfuntype
boundtype
template<typename T , int N_dim> BoundaryType blockelm::CartBoundary< T, N_dim >::boundtype = BoundaryType::None
data
template<typename T , int N_dim> Array<T, N_dim - 1> blockelm::CartBoundary< T, N_dim >::data
flag
template<typename T , int N_dim> Veci<N_dim - 1> blockelm::CartBoundary< T, N_dim >::flag
params
template<typename T , int N_dim> std::vector<T> blockelm::CartBoundary< T, N_dim >::params
ptr_mesh
template<typename T , int N_dim> CartMesh<N_dim>* blockelm::CartBoundary< T, N_dim >::ptr_mesh = nullptr
shape
template<typename T , int N_dim> Veci<N_dim - 1> blockelm::CartBoundary< T, N_dim >::shape
st_ind
template<typename T , int N_dim> Veci<N_dim>& blockelm::CartBoundary< T, N_dim >::st_ind = ptr_mesh->st_ind
status
template<typename T , int N_dim> bool blockelm::CartBoundary< T, N_dim >::status = false
val
template<typename T , int N_dim> T blockelm::CartBoundary< T, N_dim >::val
The documentation for this class was generated from the following file:
/mnt/e/linuxOS/PhyStar/BlockElm/Boundary/CartBoundary.hpp