PhyStar: smart::OrientationActor Class Reference
smart::OrientationActor Class Reference
#include <OrientationActor.hpp>
Public Member Functions
virtual int dim () const
get the dimension of the state (the size of the pfield.state)
virtual std::string name ()
the name of the actor
virtual void takeAction (dmdyn::ParticleField< 2 > &pfield, const dmdyn::ParticleModel *pmodel, bool inaive)
taking actions
virtual void takeAction (dmdyn::ParticleField< 3 > &pfield, const dmdyn::ParticleModel *pmodel, bool inaive)
virtual void initialize (tml::table *config, tml::table *subconfig)
initialize the actor
virtual std::vector< int > num () const
return the number of possible action of each dimension. return zero if the action is continueous.
Static Public Member Functions
static std::string _name ()
Public Attributes
int N_dim
Member Function Documentation
_name()
static std::string smart::OrientationActor::_name () inline static
dim()
virtual int smart::OrientationActor::dim () const inline virtual
get the dimension of the state (the size of the pfield.state)
Returns
int dimension
Implements smart::Actor.
References N_dim.
initialize()
virtual void smart::OrientationActor::initialize (tml::table * config, tml::table * subconfig) inline virtual
initialize the actor
Parameters
config toml node
Implements smart::Actor.
References N_dim.
name()
virtual std::string smart::OrientationActor::name () inline virtual
the name of the actor
Returns
std::string name
Implements smart::Actor.
References _name().
num()
virtual std::vector<int> smart::OrientationActor::num () const inline virtual
return the number of possible action of each dimension. return zero if the action is continueous.
Returns
std::vector<int>
Implements smart::Actor.
References N_dim.
takeAction() [1/2]
virtual void smart::OrientationActor::takeAction (dmdyn::ParticleField< 2 > & pfield, const dmdyn::ParticleModel * pmodel, bool inaive) inline virtual
taking actions
Parameters
pfield particle field
pmodel particle model
inaive whether the action is in naive mode (preset)
Implements smart::Actor.
References dmdyn::SmartData< N_dim >::action, blin::Norm2(), and dmdyn::ParticleField< N_dim >::pdata.
takeAction() [2/2]
virtual void smart::OrientationActor::takeAction (dmdyn::ParticleField< 3 > & pfield, const dmdyn::ParticleModel * pmodel, bool inaive) inline virtual
Implements smart::Actor.
References dmdyn::SmartData< N_dim >::action, dmdyn::angular::DirToee(), blin::Norm2(), and dmdyn::ParticleField< N_dim >::pdata.
Member Data Documentation
N_dim
int smart::OrientationActor::N_dim
The documentation for this class was generated from the following file:
/mnt/e/linuxOS/PhyStar/SmartParticle/Actor/OrientationActor.hpp