PhyStar: solver::fluidsol::boxfdm::FFTPoisson< 3, id > Struct Template Reference
solver::fluidsol::boxfdm::FFTPoisson< 3, id > Struct Template Reference
#include <FFTPoisson.hpp>
Public Types
using Field = blockelm::CartField< Real, 3 >
Public Member Functions
auto & updateFFTType ()
auto & updatelambda ()
auto & updateNtotal (int dim, int size)
void updateEigenvalue (int dim, int size, blin::Array1r &lam)
void Init (gsmpi::GSMPICart3D &mpicomm)
auto getLocalIndexBeforeTrans ()
auto getLocalIndexAfterTrans ()
auto getLocalSizeBeforeTrans ()
auto getLocalSizeAfterTrans ()
void TransformR2C (blin::Array3r &in, blin::Array3r &out)
void TransformC2R (blin::Array3r &in, blin::Array3r &out)
void SolvePressurePoisson (Field &rhs, Field &out)
void SolvePressurePoissonUniform (Field &rhs, Field &out)
void SolvePressurePoissonStretch (Field &rhs, Field &out)
void SolveViscousPoisson (Field &rhs, Field &out, const Real &visc, const Real &dt, const Real &coef)
void SolveViscousPoissonUniform (Field &rhs, Field &out, const Real &visc, const Real &dt, const Real &coef)
void SolveViscousPoissonStretch (Field &rhs, Field &out, const Real &visc, const Real &dt, const Real &coef)
Public Attributes
tfft3d::FFT3D< Real, 101+id *1000, tfft3d::FFTDataType::RR > origin
tfft3d::Cart3DPencilDecomp< Real, -101 - id *1000 > decomp
blin::Array1r lamx
blin::Array1r lamy
blin::Array1r lamz
blin::Array1r rtemp
Real one_ntotal = 1.
Real xr
Real yr
Real zr
Real lx
Real ly
Real lz
std::vector< int > st
std::vector< int > ed
int ghx
int ghy
int ghz
int nx
int ny
int nz
int stag [3]
int m [3]
int npr
int npc
tfft3d::FFTTYPE fft_type [3] = {tfft3d::kDFTHC, tfft3d::kDFTHC, tfft3d::kDFTHC}
blockelm::BoundaryPairs bc_type [3] = {blockelm::BoundaryPairs::None, blockelm::BoundaryPairs::None, blockelm::BoundaryPairs::None}
fdm::FDMTAG_Type zdir_stretch = fdm::FDMTAG_Type::Uniform
fdm::FDMSecondCenteralDiff< fdm::FDMTAG_Type::Stretch > fdm_zdir
Real * ptr_zdir_mesh = nullptr
blin::Array3r wrk
blin::Array3r wrk1
Member Typedef Documentation
Field
template<int id> using solver::fluidsol::boxfdm::FFTPoisson< 3, id >::Field = blockelm::CartField<Real, 3>
Member Function Documentation
getLocalIndexAfterTrans()
template<int id> auto solver::fluidsol::boxfdm::FFTPoisson< 3, id >::getLocalIndexAfterTrans () inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalIndexAfterTrans().
getLocalIndexBeforeTrans()
template<int id> auto solver::fluidsol::boxfdm::FFTPoisson< 3, id >::getLocalIndexBeforeTrans () inline
References tfft3d::kX, and tfft3d::kY.
getLocalSizeAfterTrans()
template<int id> auto solver::fluidsol::boxfdm::FFTPoisson< 3, id >::getLocalSizeAfterTrans () inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalSizeAfterTrans().
getLocalSizeBeforeTrans()
template<int id> auto solver::fluidsol::boxfdm::FFTPoisson< 3, id >::getLocalSizeBeforeTrans () inline
References tfft3d::kX, and tfft3d::kY.
Init()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::Init (gsmpi::GSMPICart3D & mpicomm) inline
References gsmpi::GSMPICart< N_dim, IsColMaj >::GetCoord(), tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalIndexAfterTrans(), tfft3d::FFT3D< T_real, GroupID, TypeID >::getMaxBufferSize(), gsmpi::GSMPICart< N_dim, IsColMaj >::GetProc(), tfft3d::kDFTHC, tfft3d::kNULL, tfft3d::kX, tfft3d::kY, tfft3d::kZ, quadpack::max(), fdm::FDMDiffBase::setMeshFromRw(), tfft3d::FFT3D< T_real, GroupID, TypeID >::setSizeBeforeTrans(), and fdm::Stretch.
SolvePressurePoisson()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::SolvePressurePoisson (Field & rhs, Field & out) inline
References fdm::Stretch.
SolvePressurePoissonStretch()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::SolvePressurePoissonStretch (Field & rhs, Field & out) inline
References blockelm::D_D, blockelm::D_N, blockelm::CartField< T, N_dim >::data, blockelm::Dirichlet, blockelm::N_D, blockelm::N_N, blockelm::Neumann, and fdm::FDMSecondCenteralDiff< Type >::solveHelmholtzAtRp().
SolvePressurePoissonUniform()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::SolvePressurePoissonUniform (Field & rhs, Field & out) inline
References blockelm::CartField< T, N_dim >::data.
SolveViscousPoisson()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::SolveViscousPoisson (Field & rhs, Field & out, const Real & visc, const Real & dt, const Real & coef) inline
References fdm::Stretch.
SolveViscousPoissonStretch()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::SolveViscousPoissonStretch (Field & rhs, Field & out, const Real & visc, const Real & dt, const Real & coef) inline
References blockelm::D_D, blockelm::D_N, blockelm::CartField< T, N_dim >::data, blockelm::Dirichlet, blockelm::N_D, blockelm::N_N, blockelm::Neumann, fdm::FDMSecondCenteralDiff< Type >::solveHelmholtzAtRp(), and fdm::FDMSecondCenteralDiff< Type >::solveHelmholtzAtRw().
SolveViscousPoissonUniform()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::SolveViscousPoissonUniform (Field & rhs, Field & out, const Real & visc, const Real & dt, const Real & coef) inline
References blockelm::CartField< T, N_dim >::data.
TransformC2R()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::TransformC2R (blin::Array3r & in, blin::Array3r & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::BackwardTrans(), and tfft3d::kBefore.
TransformR2C()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::TransformR2C (blin::Array3r & in, blin::Array3r & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::ForwardTrans(), and tfft3d::kAfter.
updateEigenvalue()
template<int id> void solver::fluidsol::boxfdm::FFTPoisson< 3, id >::updateEigenvalue (int dim, int size, blin::Array1r & lam) inline
References blockelm::D_D, blockelm::D_N, blockelm::N_D, blockelm::N_N, blockelm::P_P, and mathconst::PI.
updateFFTType()
template<int id> auto& solver::fluidsol::boxfdm::FFTPoisson< 3, id >::updateFFTType () inline
References blockelm::D_D, blockelm::D_N, tfft3d::kDCT1, tfft3d::kDCT2, tfft3d::kDCT3, tfft3d::kDCT4, tfft3d::kDFTHC, tfft3d::kDST1, tfft3d::kDST2, tfft3d::kDST3, tfft3d::kDST4, tfft3d::kNULL, blockelm::N_D, blockelm::N_N, blockelm::P_P, and fdm::Stretch.
updatelambda()
template<int id> auto& solver::fluidsol::boxfdm::FFTPoisson< 3, id >::updatelambda () inline
updateNtotal()
template<int id> auto& solver::fluidsol::boxfdm::FFTPoisson< 3, id >::updateNtotal (int dim, int size) inline
References tfft3d::kDCT1, tfft3d::kDCT2, tfft3d::kDCT3, tfft3d::kDCT4, tfft3d::kDFTHC, tfft3d::kDST1, tfft3d::kDST2, tfft3d::kDST3, and tfft3d::kDST4.
Member Data Documentation
bc_type
template<int id> blockelm::BoundaryPairs solver::fluidsol::boxfdm::FFTPoisson< 3, id >::bc_type[3] = {blockelm::BoundaryPairs::None, blockelm::BoundaryPairs::None, blockelm::BoundaryPairs::None}
decomp
template<int id> tfft3d::Cart3DPencilDecomp<Real, -101 - id * 1000> solver::fluidsol::boxfdm::FFTPoisson< 3, id >::decomp
ed
template<int id> std::vector<int> solver::fluidsol::boxfdm::FFTPoisson< 3, id >::ed
fdm_zdir
template<int id> fdm::FDMSecondCenteralDiff<fdm::FDMTAG_Type::Stretch> solver::fluidsol::boxfdm::FFTPoisson< 3, id >::fdm_zdir
fft_type
template<int id> tfft3d::FFTTYPE solver::fluidsol::boxfdm::FFTPoisson< 3, id >::fft_type[3] = {tfft3d::kDFTHC, tfft3d::kDFTHC, tfft3d::kDFTHC}
ghx
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::ghx
ghy
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::ghy
ghz
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::ghz
lamx
template<int id> blin::Array1r solver::fluidsol::boxfdm::FFTPoisson< 3, id >::lamx
lamy
template<int id> blin::Array1r solver::fluidsol::boxfdm::FFTPoisson< 3, id >::lamy
lamz
template<int id> blin::Array1r solver::fluidsol::boxfdm::FFTPoisson< 3, id >::lamz
lx
template<int id> Real solver::fluidsol::boxfdm::FFTPoisson< 3, id >::lx
ly
template<int id> Real solver::fluidsol::boxfdm::FFTPoisson< 3, id >::ly
lz
template<int id> Real solver::fluidsol::boxfdm::FFTPoisson< 3, id >::lz
m
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::m[3]
npc
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::npc
npr
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::npr
nx
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::nx
ny
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::ny
nz
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::nz
one_ntotal
template<int id> Real solver::fluidsol::boxfdm::FFTPoisson< 3, id >::one_ntotal = 1.
origin
template<int id> tfft3d::FFT3D<Real, 101 + id * 1000, tfft3d::FFTDataType::RR> solver::fluidsol::boxfdm::FFTPoisson< 3, id >::origin
ptr_zdir_mesh
template<int id> Real* solver::fluidsol::boxfdm::FFTPoisson< 3, id >::ptr_zdir_mesh = nullptr
rtemp
template<int id> blin::Array1r solver::fluidsol::boxfdm::FFTPoisson< 3, id >::rtemp
st
template<int id> std::vector<int> solver::fluidsol::boxfdm::FFTPoisson< 3, id >::st
stag
template<int id> int solver::fluidsol::boxfdm::FFTPoisson< 3, id >::stag[3]
wrk
template<int id> blin::Array3r solver::fluidsol::boxfdm::FFTPoisson< 3, id >::wrk
wrk1
template<int id> blin::Array3r solver::fluidsol::boxfdm::FFTPoisson< 3, id >::wrk1
xr
template<int id> Real solver::fluidsol::boxfdm::FFTPoisson< 3, id >::xr
yr
template<int id> Real solver::fluidsol::boxfdm::FFTPoisson< 3, id >::yr
zdir_stretch
template<int id> fdm::FDMTAG_Type solver::fluidsol::boxfdm::FFTPoisson< 3, id >::zdir_stretch = fdm::FDMTAG_Type::Uniform
zr
template<int id> Real solver::fluidsol::boxfdm::FFTPoisson< 3, id >::zr
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/Solver/FluidSol/FDMSol/FFTPoisson.hpp