PhyStar: blockelm::CartBlock< N_dim > Class Template Reference
blockelm::CartBlock< N_dim > Class Template Reference
#include <CartBlock.hpp>
Public Member Functions
CartBlock ()
CartBlock (CartBlock< N_dim > &x)
~CartBlock ()
void MeshReference (const CartMesh< N_dim > &x)
void FieldReference (const CartField< Real, N_dim > &x, const int &flag)
void ScalarReference (const Array1< CartField< Real, N_dim >> &x)
void Reference (const CartBlock &block)
void CreateVelocityFields (std::vector< std::vector< int >> flgs)
allocate the space for the velocity field(including the ghost mesh) and the velocity all to zero
void CreatePressureField (std::vector< int > flgs)
allocate the space for the pressure field(including the ghost mesh) and the pressure all to zero
void CreateGradField (std::vector< int > flgs)
allocate the space for the gradient field(including the ghost mesh) and the gradient all to zero
void CreateScalarFields (std::vector< int > flgs, const int n=1)
allocate the space for the scalar field(including the ghost mesh) and the scalar all to zero
Public Attributes
CartMesh< N_dim > mesh
CartField< Real, N_dim > u
CartField< Real, N_dim > v
CartField< Real, N_dim > w
CartField< Real, N_dim > p
Mat< CartField< Real, N_dim >, N_dim > grad
Array1< CartField< Real, N_dim > > scalar
Public Attributes inherited from blockelm::BlockBase
int id
Additional Inherited Members
Static Protected Attributes inherited from blockelm::BlockBase
static std::unordered_map< int, BlockBase * > block_map
Constructor & Destructor Documentation
CartBlock() [1/2]
template<int N_dim> blockelm::CartBlock< N_dim >::CartBlock () inline
CartBlock() [2/2]
template<int N_dim> blockelm::CartBlock< N_dim >::CartBlock (CartBlock< N_dim > & x) inline
References blockelm::CartBlock< N_dim >::Reference().
~CartBlock()
template<int N_dim> blockelm::CartBlock< N_dim >::~CartBlock () inline
Member Function Documentation
CreateGradField()
template<int N_dim> void blockelm::CartBlock< N_dim >::CreateGradField (std::vector< int > flgs) inline
allocate the space for the gradient field(including the ghost mesh) and the gradient all to zero
Parameters
flgs the mesh type, center or face
References blockelm::CartBlock< N_dim >::grad, and blockelm::CartBlock< N_dim >::mesh.
CreatePressureField()
template<int N_dim> void blockelm::CartBlock< N_dim >::CreatePressureField (std::vector< int > flgs) inline
allocate the space for the pressure field(including the ghost mesh) and the pressure all to zero
Parameters
flgs the mesh type, center or face
References blockelm::CartField< T, N_dim >::Create(), blockelm::CartBlock< N_dim >::mesh, and blockelm::CartBlock< N_dim >::p.
CreateScalarFields()
template<int N_dim> void blockelm::CartBlock< N_dim >::CreateScalarFields (std::vector< int > flgs, const int n = 1) inline
allocate the space for the scalar field(including the ghost mesh) and the scalar all to zero
Parameters
flgs the mesh type, center or face
n the number of the scalar type
References blockelm::CartBlock< N_dim >::mesh, and blockelm::CartBlock< N_dim >::scalar.
CreateVelocityFields()
template<int N_dim> void blockelm::CartBlock< N_dim >::CreateVelocityFields (std::vector< std::vector< int >> flgs) inline
allocate the space for the velocity field(including the ghost mesh) and the velocity all to zero
Parameters
flgs the mesh type, center or face
References blockelm::CartField< T, N_dim >::Create(), blockelm::CartBlock< N_dim >::mesh, blockelm::CartBlock< N_dim >::u, blockelm::CartBlock< N_dim >::v, and blockelm::CartBlock< N_dim >::w.
FieldReference()
template<int N_dim> void blockelm::CartBlock< N_dim >::FieldReference (const CartField< Real, N_dim > & x, const int & flag) inline
References blockelm::CartField< T, N_dim >::data, blockelm::kp, blockelm::ku, blockelm::kv, blockelm::kw, blockelm::CartBlock< N_dim >::p, blockelm::CartBlock< N_dim >::u, blockelm::CartBlock< N_dim >::v, and blockelm::CartBlock< N_dim >::w.
MeshReference()
template<int N_dim> void blockelm::CartBlock< N_dim >::MeshReference (const CartMesh< N_dim > & x) inline
References blockelm::CartBlock< N_dim >::mesh, blockelm::CartMesh< N_dim >::meshc, and blockelm::CartMesh< N_dim >::meshf.
Reference()
template<int N_dim> void blockelm::CartBlock< N_dim >::Reference (const CartBlock< N_dim > & block) inline
References blockelm::CartField< T, N_dim >::data, blockelm::CartBlock< N_dim >::grad, blockelm::CartBlock< N_dim >::mesh, blockelm::CartBlock< N_dim >::p, blockelm::CartBlock< N_dim >::scalar, blockelm::CartBlock< N_dim >::u, blockelm::CartBlock< N_dim >::v, and blockelm::CartBlock< N_dim >::w.
ScalarReference()
template<int N_dim> void blockelm::CartBlock< N_dim >::ScalarReference (const Array1< CartField< Real, N_dim >> & x) inline
References blockelm::CartBlock< N_dim >::scalar.
Member Data Documentation
grad
template<int N_dim> Mat<CartField<Real, N_dim>, N_dim> blockelm::CartBlock< N_dim >::grad
mesh
template<int N_dim> CartMesh<N_dim> blockelm::CartBlock< N_dim >::mesh
p
template<int N_dim> CartField<Real, N_dim> blockelm::CartBlock< N_dim >::p
scalar
template<int N_dim> Array1<CartField<Real, N_dim> > blockelm::CartBlock< N_dim >::scalar
u
template<int N_dim> CartField<Real, N_dim> blockelm::CartBlock< N_dim >::u
v
template<int N_dim> CartField<Real, N_dim> blockelm::CartBlock< N_dim >::v
w
template<int N_dim> CartField<Real, N_dim> blockelm::CartBlock< N_dim >::w
The documentation for this class was generated from the following file:
/mnt/e/linuxOS/PhyStar/BlockElm/Block/CartBlock.hpp