PhyStar: dmdyn::EllipsoidLevelSet< T_real > Class Template Reference
dmdyn::EllipsoidLevelSet< T_real > Class Template Reference
#include <LevelSet.hpp>
Public Member Functions
void Init (const int dim, const T_real radii[], const T_real dx)
void UpdateTransform (const T_real pos[], const T_real ee[])
T_real DistanceFuncInMovingFrame (Vec3< T_real > &dpos0)
T_real VolumeFraction (const Vec3< T_real > &pos)
T_real HFun (const T_real phi)
Private Attributes
Vec4< T_real > ee_
Vec3< T_real > inv_radii2_
Vec3< T_real > pos_
T_real dx_
int dim_ = 3
Member Function Documentation
DistanceFuncInMovingFrame()
template<typename T_real > T_real dmdyn::EllipsoidLevelSet< T_real >::DistanceFuncInMovingFrame (Vec3< T_real > & dpos0) inline
References dmdyn::EllipsoidLevelSet< T_real >::ee_, dmdyn::EllipsoidLevelSet< T_real >::inv_radii2_, and dmdyn::angular::VecFromIFToPF3DimByee().
HFun()
template<typename T_real > T_real dmdyn::EllipsoidLevelSet< T_real >::HFun (const T_real phi) inline
Init()
template<typename T_real > void dmdyn::EllipsoidLevelSet< T_real >::Init (const int dim, const T_real radii[], const T_real dx) inline
References dmdyn::EllipsoidLevelSet< T_real >::dim_, dmdyn::EllipsoidLevelSet< T_real >::dx_, and dmdyn::EllipsoidLevelSet< T_real >::inv_radii2_.
UpdateTransform()
template<typename T_real > void dmdyn::EllipsoidLevelSet< T_real >::UpdateTransform (const T_real pos[], const T_real ee[]) inline
References dmdyn::EllipsoidLevelSet< T_real >::dim_, dmdyn::EllipsoidLevelSet< T_real >::ee_, and dmdyn::EllipsoidLevelSet< T_real >::pos_.
VolumeFraction()
template<typename T_real > T_real dmdyn::EllipsoidLevelSet< T_real >::VolumeFraction (const Vec3< T_real > & pos) inline
References dmdyn::EllipsoidLevelSet< T_real >::DistanceFuncInMovingFrame(), dmdyn::EllipsoidLevelSet< T_real >::dx_, dmdyn::EllipsoidLevelSet< T_real >::HFun(), and dmdyn::EllipsoidLevelSet< T_real >::pos_.
Member Data Documentation
dim_
template<typename T_real > int dmdyn::EllipsoidLevelSet< T_real >::dim_ = 3 private
dx_
template<typename T_real > T_real dmdyn::EllipsoidLevelSet< T_real >::dx_ private
ee_
template<typename T_real > Vec4<T_real> dmdyn::EllipsoidLevelSet< T_real >::ee_ private
inv_radii2_
template<typename T_real > Vec3<T_real> dmdyn::EllipsoidLevelSet< T_real >::inv_radii2_ private
pos_
template<typename T_real > Vec3<T_real> dmdyn::EllipsoidLevelSet< T_real >::pos_ private
The documentation for this class was generated from the following file:
/mnt/e/linuxOS/PhyStar/DMDyn/DMClass/LevelSet.hpp