PhyStar: fileio::FluidCartRegularD< N_dim, FT > Class Template Reference
fileio::FluidCartRegularD< N_dim, FT > Class Template Reference
fluid io for cartesian coordinates, double percision
#include <FluidIO.hpp>
Public Member Functions
FluidCartRegularD ()
Construct a new Fluid Cart Regular D object.
~FluidCartRegularD ()
Destroy the Fluid Cart Regular D object.
auto & SetMeshc (const int dim, const int N, const double meshc[])
Set the Mesh [center] object.
auto & SetMeshf (int dim, int N, const double meshf[])
Set the Mesh [face] object.
auto & SetGhostMesh (std::vector< int > gh_down, std::vector< int > gh_up={})
Set the Ghost Mesh object if gh_up={}, it means that gh_down and gh_up have the same size of ghost mesh if the size of gh_down n is below N_dim, the size of ghost mesh of gh_down[n] and gh_down[n+1]...gh_down[N_dim-1] should equal to gh_down[n-1];.
auto & SetGhostMesh (std::vector< std::vector< int >> gh)
auto & SetGhostMesh (int gh_down, int gh_up=-1)
Set the Ghost Mesh object if only input gh_down, it means that gh_up=gh_down.
auto & SetDomain (std::vector< double > domain_down, std::vector< double > domain_up)
Set the compuational Domain object if the size of domain_down/up n is below N_dim, the value of domain_down/up[n] ,[n+1]should equal to domain_down/up[n-1];.
auto & SetDomain (std::vector< std::vector< double >> domain)
auto & SetFileAttr (std::string name, std::string val)
Set the File Attributes object not to create attribute, just set the standard attribute to the buffer in current object.
auto & SetFileAttr (std::string name, double val)
Set the File Attributes object not to create attribute, just set the standard attribute to the buffer in current object.
void Print ()
Print the abstract of the current file attributes.
auto CreateFile (const int istep, const std::string ftype)
Create a hdf5 File.
void CloseFile ()
Close opened hdf5 file.
auto & AddAttributeTo (const FluidGroup &group, const std::string attrname, const std::string str)
add extra attribute to different groups [string]
auto & AddAttributeTo (const FluidGroup &group, const std::string attrname, const int intdata[], const int n)
add extra attribute to different groups [int array]
auto & AddAttributeTo (const FluidGroup &group, const std::string attrname, const double data[], const int n)
add extra attribute to different groups [double array]
auto & AddAttributeTo (const FluidGroup &group, const std::string attrname, const int intdata)
add extra attribute to different groups [int]
auto & AddAttributeTo (const FluidGroup &group, const std::string attrname, const double data)
add extra attribute to different groups [double]
auto & AddDataSetTo (const FluidGroup &group, const std::string dataname, const int intdata[], const int n0)
add dataset to different groups [int array] one dimension
auto & AddDataSetTo (const FluidGroup &group, const std::string dataname, const int intdata[], const int n0, const int n1)
add dataset to different groups [int array] two dimension
auto & AddDataSetTo (const FluidGroup &group, const std::string dataname, const int intdata[], const int n0, const int n1, const int n2)
add dataset to different groups [int array] three dimension
auto & AddDataSetTo (const FluidGroup &group, const std::string dataname, const double data[], const int n0)
add dataset to different groups [double array] one dimension
auto & AddDataSetTo (const FluidGroup &group, const std::string dataname, const double data[], const int n0, const int n1)
add dataset to different groups [double array] two dimension
auto & AddDataSetTo (const FluidGroup &group, const std::string dataname, const double data[], const int n0, const int n1, const int n2)
add dataset to different groups [double array] three dimension
auto & AddDataSetCplxTo (const FluidGroup &group, const std::string dataname, const std::complex< double > data[], const int n0, const int n1)
auto & AddField (const std::string fieldname, const double data[], const std::vector< int > shape, const std::vector< int > gridflag, const std::vector< int > shapetotal)
add Field to Field group for mpi version, but it also supports serial version
auto & AddFieldWithoutGhost (const std::string &fieldname, const double data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & AddFieldDefault (const std::string &fieldname, const double data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & AddCplxField (const std::string fieldname, const std::complex< double > data[], const std::vector< int > shape, const std::vector< int > gridflag, const std::vector< int > shapetotal)
auto & AddCplxFieldWithoutGhost (const std::string &fieldname, const std::complex< double > data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & AddCplxFieldDefault (const std::string &fieldname, const std::complex< double > data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & AddField (const std::string fieldname, double data[], std::vector< int > shape, std::vector< int > gridflag)
add Field to Field group only support serial version
auto & AddCplxField (const std::string fieldname, std::complex< double > data[], std::vector< int > shape, std::vector< int > gridflag)
void CalOffset (const std::vector< int > &shape, const std::vector< int > &gridflag, hsize_t offset[])
calculate offset for writing data by mpi
void MemSlice (const auto *in, auto *out, const int shape[], hsize_t offset[], hsize_t count[])
auto OpenFile (const int istep, const std::string ftype)
Open a existed file.
auto & ReadAttributeFrom (const FluidGroup &group, const std::string attrname, std::string &str)
Read attribute from different groups[string].
auto & ReadAttributeFrom (const FluidGroup &group, const std::string attrname, int intdata[])
Read attribute from different groups [int array].
auto & ReadAttributeFrom (const FluidGroup &group, const std::string attrname, double data[])
Read attribute from different groups [double array].
auto & ReadDataSetFrom (const FluidGroup &group, const std::string dataname, int intdata[])
Read dataset from different groups [int array].
auto & ReadDataSetFrom (const FluidGroup &group, const std::string dataname, double data[])
Read dataset from different groups [double array].
auto & ReadField (const std::string fieldname, double data[], std::vector< int > shape, std::vector< int > gridflag, const std::vector< int > shapetotal)
Read field from Field group for mpi verison, but it also supports serial version.
auto & ReadFieldWithoutGhost (const std::string &fieldname, double data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & ReadFieldDefault (const std::string &fieldname, double data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & ReadCplxField (const std::string fieldname, std::complex< double > data[], std::vector< int > shape, std::vector< int > gridflag, const std::vector< int > shapetotal)
auto & ReadCplxFieldWithoutGhost (const std::string &fieldname, std::complex< double > data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & ReadCplxFieldDefault (const std::string &fieldname, std::complex< double > data[], const std::vector< int > &shape, const std::vector< int > &gridflag, const std::vector< int > &shapetotal)
auto & ReadField (const std::string fieldname, double data[], std::vector< int > shape, std::vector< int > gridflag)
Read field from Field group only support serial verison.
auto & ReadCplxField (const std::string fieldname, std::complex< double > data[], std::vector< int > shape, std::vector< int > gridflag)
Static Public Member Functions
static void AllocateBuffer (const int &maxlength)
static void DeallocateBuffer ()
Public Attributes
hid_t fileid
handles of HDF5
hid_t filepropid
hid_t dataspaceid
hid_t physparaid
hid_t otherinfoid
hid_t fieldid
Private Attributes
const int _dim = N_dim
std::string _casename = "default"
std::string _space = "physical"
std::string _filestyle = "onestep"
std::string _storagestyle = "c-style"
std::string _dataspacestyle = "cartregular"
std::string _filepath = "./"
std::string _filenameprefix = "fluidfield"
int _meshnumc [N_dim] = {0}
int _meshnumf [N_dim] = {0}
int _gh_down [N_dim] = {0}
int _gh_up [N_dim] = {0}
double * _ptr_meshc [N_dim]
double * _ptr_meshf [N_dim]
int _numbernamelength = 7
double _domain_down [N_dim] = {0}
double _domain_up [N_dim] = {0}
double _visc0 = 0.
double _rho0 = 0.
int _mpi_coord [N_dim]
int _mpi_proc [N_dim]
Static Private Attributes
static double * _rtemp = nullptr
static std::complex< double > * _ctemp = nullptr
static int _maxlength = 0
Detailed Description
template<int N_dim, FileTag FT = FileTag::WithoutGhost>
class fileio::FluidCartRegularD< N_dim, FT >
fluid io for cartesian coordinates, double percision
Constructor & Destructor Documentation
FluidCartRegularD()
template<int N_dim, FileTag FT = FileTag::WithoutGhost> fileio::FluidCartRegularD< N_dim, FT >::FluidCartRegularD () inline
Construct a new Fluid Cart Regular D object.
References fileio::FluidCartRegularD< N_dim, FT >::_gh_down, fileio::FluidCartRegularD< N_dim, FT >::_gh_up, fileio::FluidCartRegularD< N_dim, FT >::_meshnumc, fileio::FluidCartRegularD< N_dim, FT >::_meshnumf, fileio::FluidCartRegularD< N_dim, FT >::_mpi_coord, fileio::FluidCartRegularD< N_dim, FT >::_mpi_proc, fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshc, and fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshf.
~FluidCartRegularD()
template<int N_dim, FileTag FT = FileTag::WithoutGhost> fileio::FluidCartRegularD< N_dim, FT >::~FluidCartRegularD () inline
Destroy the Fluid Cart Regular D object.
References fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshc, and fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshf.
Member Function Documentation
AddAttributeTo() [1/5]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo (const FluidGroup & group, const std::string attrname, const double data)
add extra attribute to different groups [double]
Parameters
group which group, an enum constant
attrname attribute name
data attribute, double
Returns
auto& *this
References fileio::AddAttribute(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddAttributeTo() [2/5]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo (const FluidGroup & group, const std::string attrname, const double data[], const int n)
add extra attribute to different groups [double array]
Parameters
group which group, an enum constant
attrname attribute name
data attribute, double array
n size of double array
Returns
auto& *this
References fileio::AddAttribute(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddAttributeTo() [3/5]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo (const FluidGroup & group, const std::string attrname, const int intdata)
add extra attribute to different groups [int]
Parameters
group which group ,a enum constant
attrname attribute name
intdata attribute,int
Returns
auto& *this
References fileio::AddAttribute(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddAttributeTo() [4/5]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo (const FluidGroup & group, const std::string attrname, const int intdata[], const int n)
add extra attribute to different groups [int array]
Parameters
group which group ,a enum constant
attrname attribute name
intdata attribute,int array
n size of int array
Returns
auto& *this
References fileio::AddAttribute(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddAttributeTo() [5/5]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo (const FluidGroup & group, const std::string attrname, const std::string str)
add extra attribute to different groups [string]
Parameters
group which group ,a enum constant
attrname attribute name
str attribute val
Returns
auto& *this
References fileio::AddAttribute(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddCplxField() [1/2]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddCplxField (const std::string fieldname, const std::complex< double > data[], const std::vector< int > shape, const std::vector< int > gridflag, const std::vector< int > shapetotal)
References fileio::WithoutGhost.
AddCplxField() [2/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::AddCplxField (const std::string fieldname, std::complex< double > data[], std::vector< int > shape, std::vector< int > gridflag) inline
References fileio::FluidCartRegularD< N_dim, FT >::AddCplxField().
AddCplxFieldDefault()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddCplxFieldDefault (const std::string & fieldname, const std::complex< double > data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::AddAttribute(), and fileio::DestroyCompound().
AddCplxFieldWithoutGhost()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddCplxFieldWithoutGhost (const std::string & fieldname, const std::complex< double > data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::AddAttribute(), and fileio::DestroyCompound().
AddDataSetCplxTo()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddDataSetCplxTo (const FluidGroup & group, const std::string dataname, const std::complex< double > data[], const int n0, const int n1)
References fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddDataSetTo() [1/6]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddDataSetTo (const FluidGroup & group, const std::string dataname, const double data[], const int n0)
add dataset to different groups [double array] one dimension
Parameters
group which group, an enum constant
dataname dataset name
data double array
n0 size of double array, 0-dimension
Returns
auto&
References fileio::AddDataSet(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddDataSetTo() [2/6]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddDataSetTo (const FluidGroup & group, const std::string dataname, const double data[], const int n0, const int n1)
add dataset to different groups [double array] two dimension
Parameters
group which group, an enum constant
dataname dataset name
data double array
n0 size of double array, 0-dimension
n1 size of double array, 1-dimension
Returns
auto&
References fileio::AddDataSet(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddDataSetTo() [3/6]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddDataSetTo (const FluidGroup & group, const std::string dataname, const double data[], const int n0, const int n1, const int n2)
add dataset to different groups [double array] three dimension
Parameters
group which group, an enum constant
dataname dataset name
data double array
n0 size of int array, 0-dimension
n1 size of int array, 1-dimension
n2 size of int array, 2-dimension
Returns
auto& *this
References fileio::AddDataSet(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddDataSetTo() [4/6]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddDataSetTo (const FluidGroup & group, const std::string dataname, const int intdata[], const int n0)
add dataset to different groups [int array] one dimension
Parameters
group which group, an enum constant
dataname dataset name
intdata int array
n0 size of int array, 0-dimension
Returns
auto& *this
References fileio::AddDataSet(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddDataSetTo() [5/6]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddDataSetTo (const FluidGroup & group, const std::string dataname, const int intdata[], const int n0, const int n1)
add dataset to different groups [int array] two dimension
Parameters
group which group, an enum constant
dataname dataset name
intdata int array
n0 size of int array, 0-dimension
n1 size of int array, 1-dimension
n2 size of int array, 2-dimension
Returns
auto& *this
References fileio::AddDataSet(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddDataSetTo() [6/6]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddDataSetTo (const FluidGroup & group, const std::string dataname, const int intdata[], const int n0, const int n1, const int n2)
add dataset to different groups [int array] three dimension
Parameters
group which group, an enum constant
dataname dataset name
intdata int array
n0 size of int array, 0-dimension
n1 size of int array, 1-dimension
Returns
auto& *this
References fileio::AddDataSet(), fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, and fileio::kPhysPara.
AddField() [1/2]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddField (const std::string fieldname, const double data[], const std::vector< int > shape, const std::vector< int > gridflag, const std::vector< int > shapetotal)
add Field to Field group for mpi version, but it also supports serial version
Parameters
fieldname field name
data double data
shape shape of field at current proc
gridflag grid flag (1,0,1),(F,c,F)
shapetotal total shape of field
Returns
auto& *this
References fileio::WithoutGhost.
AddField() [2/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::AddField (const std::string fieldname, double data[], std::vector< int > shape, std::vector< int > gridflag) inline
add Field to Field group only support serial version
Parameters
fieldname field name
data double data
shape shape of field at current proc
gridflag grid flag (1,0,1),(F,c,F)
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::AddField().
AddFieldDefault()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddFieldDefault (const std::string & fieldname, const double data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::AddAttribute().
AddFieldWithoutGhost()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::AddFieldWithoutGhost (const std::string & fieldname, const double data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::AddAttribute().
AllocateBuffer()
template<int N_dim, FileTag FT = FileTag::WithoutGhost> static void fileio::FluidCartRegularD< N_dim, FT >::AllocateBuffer (const int & maxlength) inline static
References fileio::FluidCartRegularD< N_dim, FT >::_ctemp, fileio::FluidCartRegularD< N_dim, FT >::_maxlength, fileio::FluidCartRegularD< N_dim, FT >::_rtemp, and fileio::WithoutGhost.
CalOffset()
template<int N_dim, FileTag FT> void fileio::FluidCartRegularD< N_dim, FT >::CalOffset (const std::vector< int > & shape, const std::vector< int > & gridflag, hsize_t offset[])
calculate offset for writing data by mpi
Template Parameters
N_dim
FT FileTag
Parameters
shape array size of the current block
gridflag center or face
offset
CloseFile()
template<int N_dim, FileTag FT> void fileio::FluidCartRegularD< N_dim, FT >::CloseFile
Close opened hdf5 file.
CreateFile()
template<int N_dim, FileTag FT> auto fileio::FluidCartRegularD< N_dim, FT >::CreateFile (const int istep, const std::string ftype)
Create a hdf5 File.
Parameters
istep computation step
ftype select a file style, onestep/mid
Returns
auto id of opened file
References fileio::AddAttribute(), fileio::AddDataSet(), fileio::DataSpace(), fileio::Fields(), fileio::FileProps(), fileio::intTostr(), fileio::Others(), fileio::PhysParams(), and fileio::WithoutGhost.
DeallocateBuffer()
template<int N_dim, FileTag FT = FileTag::WithoutGhost> static void fileio::FluidCartRegularD< N_dim, FT >::DeallocateBuffer () inline static
References fileio::FluidCartRegularD< N_dim, FT >::_ctemp, fileio::FluidCartRegularD< N_dim, FT >::_maxlength, fileio::FluidCartRegularD< N_dim, FT >::_rtemp, and fileio::WithoutGhost.
MemSlice()
template<int N_dim, FileTag FT> void fileio::FluidCartRegularD< N_dim, FT >::MemSlice (const auto * in, auto * out, const int shape[], hsize_t offset[], hsize_t count[])
References fileio::WithoutGhost.
OpenFile()
template<int N_dim, FileTag FT> auto fileio::FluidCartRegularD< N_dim, FT >::OpenFile (const int istep, const std::string ftype)
Open a existed file.
Parameters
istep computational step
ftype file style : onestep/mid
Returns
auto id of opened file
References fileio::DataSpace(), fileio::Fields(), fileio::FileProps(), fileio::intTostr(), fileio::kFileProp, fileio::kGeoMesh, fileio::kPhysPara, fileio::Others(), fileio::PhysParams(), and fileio::WithoutGhost.
Print()
template<int N_dim, FileTag FT> void fileio::FluidCartRegularD< N_dim, FT >::Print
Print the abstract of the current file attributes.
References fileio::intTostr().
ReadAttributeFrom() [1/3]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadAttributeFrom (const FluidGroup & group, const std::string attrname, double data[])
Read attribute from different groups [double array].
Parameters
[in] group which group, an enum constant
[in] attrname attribute name
[out] data attribute value,double array
Returns
auto& *this
References fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, fileio::kPhysPara, and fileio::ReadAttribute().
ReadAttributeFrom() [2/3]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadAttributeFrom (const FluidGroup & group, const std::string attrname, int intdata[])
Read attribute from different groups [int array].
Parameters
[in] group which group, an enum constant
[in] attrname attribute name
[out] intdata attribute value,int array
Returns
auto& *this
References fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, fileio::kPhysPara, and fileio::ReadAttribute().
ReadAttributeFrom() [3/3]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadAttributeFrom (const FluidGroup & group, const std::string attrname, std::string & str)
Read attribute from different groups[string].
Parameters
[in] group which group, an enum constant
[in] attrname attribute name
[out] str attribute value
Returns
auto& *this
References fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, fileio::kPhysPara, and fileio::ReadStringAttribute().
ReadCplxField() [1/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::ReadCplxField (const std::string fieldname, std::complex< double > data[], std::vector< int > shape, std::vector< int > gridflag) inline
References fileio::FluidCartRegularD< N_dim, FT >::ReadCplxField().
ReadCplxField() [2/2]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadCplxField (const std::string fieldname, std::complex< double > data[], std::vector< int > shape, std::vector< int > gridflag, const std::vector< int > shapetotal)
References fileio::WithoutGhost.
ReadCplxFieldDefault()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadCplxFieldDefault (const std::string & fieldname, std::complex< double > data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::ReadAttribute().
ReadCplxFieldWithoutGhost()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadCplxFieldWithoutGhost (const std::string & fieldname, std::complex< double > data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::ReadAttribute().
ReadDataSetFrom() [1/2]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadDataSetFrom (const FluidGroup & group, const std::string dataname, double data[])
Read dataset from different groups [double array].
Parameters
[in] group which group, an enum constant
[in] dataname attribute name
[out] data attribute value,int array
Returns
auto& *this
References fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, fileio::kPhysPara, and fileio::ReadDataSet().
ReadDataSetFrom() [2/2]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadDataSetFrom (const FluidGroup & group, const std::string dataname, int intdata[])
Read dataset from different groups [int array].
Parameters
[in] group which group, an enum constant
[in] dataname attribute name
[out] intdata attribute value,int array
Returns
auto& *this
References fileio::kField, fileio::kFileProp, fileio::kGeoMesh, fileio::kOtherInfo, fileio::kPhysPara, and fileio::ReadDataSet().
ReadField() [1/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::ReadField (const std::string fieldname, double data[], std::vector< int > shape, std::vector< int > gridflag) inline
Read field from Field group only support serial verison.
Parameters
[in] fieldname field name
[out] data field data
[in] shape shape of field
[in] gridflag grid flag, (1,0,1) means (Face,center,Face)
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::ReadField().
ReadField() [2/2]
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadField (const std::string fieldname, double data[], std::vector< int > shape, std::vector< int > gridflag, const std::vector< int > shapetotal)
Read field from Field group for mpi verison, but it also supports serial version.
Parameters
[in] fieldname field name
[out] data field data
[in] shape shape of field
[in] gridflag grid flag, (1,0,1) means (Face,center,Face)
Returns
auto& *this
References fileio::WithoutGhost.
ReadFieldDefault()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadFieldDefault (const std::string & fieldname, double data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::ReadAttribute().
ReadFieldWithoutGhost()
template<int N_dim, FileTag FT> auto & fileio::FluidCartRegularD< N_dim, FT >::ReadFieldWithoutGhost (const std::string & fieldname, double data[], const std::vector< int > & shape, const std::vector< int > & gridflag, const std::vector< int > & shapetotal)
References fileio::ReadAttribute().
SetDomain() [1/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetDomain (std::vector< double > domain_down, std::vector< double > domain_up) inline
Set the compuational Domain object if the size of domain_down/up n is below N_dim, the value of domain_down/up[n] ,[n+1]should equal to domain_down/up[n-1];.
Parameters
domain_down the lower boundary of Domain
domain_up the upper boundary of domain
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::_domain_down, and fileio::FluidCartRegularD< N_dim, FT >::_domain_up.
SetDomain() [2/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetDomain (std::vector< std::vector< double >> domain) inline
References fileio::FluidCartRegularD< N_dim, FT >::_domain_down, and fileio::FluidCartRegularD< N_dim, FT >::_domain_up.
SetFileAttr() [1/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr (std::string name, double val) inline
Set the File Attributes object not to create attribute, just set the standard attribute to the buffer in current object.
Parameters
name attribute name
val attribute value
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::_rho0, fileio::FluidCartRegularD< N_dim, FT >::_visc0, and fileio::strToLower().
SetFileAttr() [2/2]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr (std::string name, std::string val) inline
Set the File Attributes object not to create attribute, just set the standard attribute to the buffer in current object.
Parameters
name attribute name
val attribute value
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::_casename, fileio::FluidCartRegularD< N_dim, FT >::_dataspacestyle, fileio::FluidCartRegularD< N_dim, FT >::_filenameprefix, fileio::FluidCartRegularD< N_dim, FT >::_filepath, fileio::FluidCartRegularD< N_dim, FT >::_filestyle, fileio::FluidCartRegularD< N_dim, FT >::_space, fileio::FluidCartRegularD< N_dim, FT >::_storagestyle, and fileio::strToLower().
SetGhostMesh() [1/3]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh (int gh_down, int gh_up = -1) inline
Set the Ghost Mesh object if only input gh_down, it means that gh_up=gh_down.
Parameters
gh_down ghost mesh size of lower boudnary
gh_up ghost mesh size of upper boudnary
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::_gh_down, and fileio::FluidCartRegularD< N_dim, FT >::_gh_up.
SetGhostMesh() [2/3]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh (std::vector< int > gh_down, std::vector< int > gh_up = {}) inline
Set the Ghost Mesh object if gh_up={}, it means that gh_down and gh_up have the same size of ghost mesh if the size of gh_down n is below N_dim, the size of ghost mesh of gh_down[n] and gh_down[n+1]...gh_down[N_dim-1] should equal to gh_down[n-1];.
Parameters
gh_down ghost mesh size of lower boudnary
gh_up ghost mesh size of upper boudnary
Returns
auto& *this
SetGhostMesh() [3/3]
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh (std::vector< std::vector< int >> gh) inline
References fileio::FluidCartRegularD< N_dim, FT >::_gh_down, and fileio::FluidCartRegularD< N_dim, FT >::_gh_up.
SetMeshc()
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetMeshc (const int dim, const int N, const double meshc[]) inline
Set the Mesh [center] object.
Parameters
dim which dimension/direction
N size of mesh
meshc mesh [center]
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::_meshnumc, and fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshc.
SetMeshf()
template<int N_dim, FileTag FT = FileTag::WithoutGhost> auto& fileio::FluidCartRegularD< N_dim, FT >::SetMeshf (int dim, int N, const double meshf[]) inline
Set the Mesh [face] object.
Parameters
dim which dimension/direction
N size of mesh
meshf mesh [face]
Returns
auto& *this
References fileio::FluidCartRegularD< N_dim, FT >::_meshnumf, and fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshf.
Member Data Documentation
_casename
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::string fileio::FluidCartRegularD< N_dim, FT >::_casename = "default" private
_ctemp
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::complex<double>* fileio::FluidCartRegularD< N_dim, FT >::_ctemp = nullptr inline static private
_dataspacestyle
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::string fileio::FluidCartRegularD< N_dim, FT >::_dataspacestyle = "cartregular" private
_dim
template<int N_dim, FileTag FT = FileTag::WithoutGhost> const int fileio::FluidCartRegularD< N_dim, FT >::_dim = N_dim private
_domain_down
template<int N_dim, FileTag FT = FileTag::WithoutGhost> double fileio::FluidCartRegularD< N_dim, FT >::_domain_down[N_dim] = {0} private
_domain_up
template<int N_dim, FileTag FT = FileTag::WithoutGhost> double fileio::FluidCartRegularD< N_dim, FT >::_domain_up[N_dim] = {0} private
_filenameprefix
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::string fileio::FluidCartRegularD< N_dim, FT >::_filenameprefix = "fluidfield" private
_filepath
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::string fileio::FluidCartRegularD< N_dim, FT >::_filepath = "./" private
_filestyle
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::string fileio::FluidCartRegularD< N_dim, FT >::_filestyle = "onestep" private
_gh_down
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_gh_down[N_dim] = {0} private
_gh_up
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_gh_up[N_dim] = {0} private
_maxlength
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_maxlength = 0 inline static private
_meshnumc
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_meshnumc[N_dim] = {0} private
_meshnumf
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_meshnumf[N_dim] = {0} private
_mpi_coord
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_mpi_coord[N_dim] private
_mpi_proc
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_mpi_proc[N_dim] private
_numbernamelength
template<int N_dim, FileTag FT = FileTag::WithoutGhost> int fileio::FluidCartRegularD< N_dim, FT >::_numbernamelength = 7 private
_ptr_meshc
template<int N_dim, FileTag FT = FileTag::WithoutGhost> double* fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshc[N_dim] private
_ptr_meshf
template<int N_dim, FileTag FT = FileTag::WithoutGhost> double* fileio::FluidCartRegularD< N_dim, FT >::_ptr_meshf[N_dim] private
_rho0
template<int N_dim, FileTag FT = FileTag::WithoutGhost> double fileio::FluidCartRegularD< N_dim, FT >::_rho0 = 0. private
_rtemp
template<int N_dim, FileTag FT = FileTag::WithoutGhost> double* fileio::FluidCartRegularD< N_dim, FT >::_rtemp = nullptr inline static private
_space
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::string fileio::FluidCartRegularD< N_dim, FT >::_space = "physical" private
_storagestyle
template<int N_dim, FileTag FT = FileTag::WithoutGhost> std::string fileio::FluidCartRegularD< N_dim, FT >::_storagestyle = "c-style" private
_visc0
template<int N_dim, FileTag FT = FileTag::WithoutGhost> double fileio::FluidCartRegularD< N_dim, FT >::_visc0 = 0. private
dataspaceid
template<int N_dim, FileTag FT = FileTag::WithoutGhost> hid_t fileio::FluidCartRegularD< N_dim, FT >::dataspaceid
fieldid
template<int N_dim, FileTag FT = FileTag::WithoutGhost> hid_t fileio::FluidCartRegularD< N_dim, FT >::fieldid
fileid
template<int N_dim, FileTag FT = FileTag::WithoutGhost> hid_t fileio::FluidCartRegularD< N_dim, FT >::fileid
handles of HDF5
filepropid
template<int N_dim, FileTag FT = FileTag::WithoutGhost> hid_t fileio::FluidCartRegularD< N_dim, FT >::filepropid
otherinfoid
template<int N_dim, FileTag FT = FileTag::WithoutGhost> hid_t fileio::FluidCartRegularD< N_dim, FT >::otherinfoid
physparaid
template<int N_dim, FileTag FT = FileTag::WithoutGhost> hid_t fileio::FluidCartRegularD< N_dim, FT >::physparaid
The documentation for this class was generated from the following file:
/mnt/e/linuxOS/PhyStar/IO/FileIO/FluidIO.hpp