PhyStar: dmdyn::CoupleBase< N_dim > Struct Template Reference
dmdyn::CoupleBase< N_dim > Struct Template Reference
#include <CoupleBase.hpp>
Classes
struct Option
Public Member Functions
CoupleBase ()
void Init (tml::tmlnode &ibtml)
Public Attributes
struct dmdyn::CoupleBase::Option option
Constructor & Destructor Documentation
CoupleBase()
template<int N_dim> dmdyn::CoupleBase< N_dim >::CoupleBase () inline
Member Function Documentation
Init()
template<int N_dim> void dmdyn::CoupleBase< N_dim >::Init (tml::tmlnode & ibtml) inline
References dmdyn::CoupleBase< N_dim >::Option::coupletype, dmdyn::CoupleBase< N_dim >::Option::delta_width, dmdyn::CoupleBase< N_dim >::Option::deltatype, dmdyn::CoupleBase< N_dim >::option, dmdyn::vConfigCoupleType(), dmdyn::vConfigDeltaFunType(), and dmdyn::vConfigDeltaWidth().
Member Data Documentation
option
template<int N_dim> struct dmdyn::CoupleBase::Option dmdyn::CoupleBase< N_dim >::option
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/DMDyn/TwoWayCouple/CoupleBase.hpp