PhyStar: solver::fluidsol::CartFFD< 3, id > Struct Template Reference
solver::fluidsol::CartFFD< 3, id > Struct Template Reference
#include <CartFFD.hpp>
Public Member Functions
void Init ()
void TransformR2C (blin::Array3r &in, blin::Array3cr &out)
void TransformR2C_Dealias (blin::Array3r &in, blin::Array3cr &out)
void TransformC2R (blin::Array3cr &in, blin::Array3r &out)
void TransformC2R_Dealias (blin::Array3cr &in, blin::Array3r &out)
auto getLocalIndexBeforeTrans ()
auto getLocalIndexAfterTrans ()
auto getLocalIndexBeforeTrans_Dealias ()
auto getLocalIndexAfterTrans_Dealias ()
auto getLocalSizeBeforeTrans ()
auto getLocalSizeAfterTrans ()
auto getLocalSizeBeforeTrans_Dealias ()
auto getLocalSizeAfterTrans_Dealias ()
template<DiffTag DT>
void Diff (blin::Array3cr &in)
template<DiffTag DT>
void Diff (blin::Array3cr &in, blin::Array3cr &out, Real alpha=1., Real beta=0.)
void Div (blin::Array3cr &u, blin::Array3cr &v, blin::Array3cr &out, Real alpha=1., Real beta=0.)
void Lap (blin::Array3cr &in, blin::Array3cr &out, Real alpha=1., Real beta=0.)
Public Attributes
tfft3d::FFT3D< Real, 101+id *1000 > origin
tfft3d::FFT3D< Real, 201+id *1000 > dealias
tfft3d::Cart3DPencilDecomp< Real, -101 - id *1000 > decomp
tfft3d::Cart3DPencilDecomp< Real, -201 - id *1000 > decomp_de
blin::Array1r kx
blin::Array1r ky
blin::Array1cr ikx
blin::Array1cr iky
blin::Array1r rtemp
blin::Array1cr ctemp
Real one_nxy
Real one_nxy_de
Real xr
Real yr
Real lx
Real ly
Real lz
Real kmax
std::vector< int > st
std::vector< int > ed
int ghx
int ghy
int ghz
int nx
int ny
int nz
int mx
int my
int mz
int npr
int npc
Member Function Documentation
Diff() [1/2]
template<int id> template<DiffTag DT> void solver::fluidsol::CartFFD< 3, id >::Diff (blin::Array3cr & in) inline
References solver::fluidsol::Dx, solver::fluidsol::DxDx, solver::fluidsol::DxDy, solver::fluidsol::Dy, solver::fluidsol::DyDx, and solver::fluidsol::DyDy.
Diff() [2/2]
template<int id> template<DiffTag DT> void solver::fluidsol::CartFFD< 3, id >::Diff (blin::Array3cr & in, blin::Array3cr & out, Real alpha = 1., Real beta = 0.) inline
References solver::fluidsol::Dx, solver::fluidsol::DxDx, solver::fluidsol::DxDy, solver::fluidsol::Dy, solver::fluidsol::DyDx, and solver::fluidsol::DyDy.
Div()
template<int id> void solver::fluidsol::CartFFD< 3, id >::Div (blin::Array3cr & u, blin::Array3cr & v, blin::Array3cr & out, Real alpha = 1., Real beta = 0.) inline
getLocalIndexAfterTrans()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalIndexAfterTrans () inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalIndexAfterTrans().
getLocalIndexAfterTrans_Dealias()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalIndexAfterTrans_Dealias () inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalIndexAfterTrans().
getLocalIndexBeforeTrans()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalIndexBeforeTrans () inline
References tfft3d::kX, and tfft3d::kY.
getLocalIndexBeforeTrans_Dealias()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalIndexBeforeTrans_Dealias () inline
References tfft3d::kX, and tfft3d::kY.
getLocalSizeAfterTrans()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalSizeAfterTrans () inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalSizeAfterTrans().
getLocalSizeAfterTrans_Dealias()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalSizeAfterTrans_Dealias () inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalSizeAfterTrans().
getLocalSizeBeforeTrans()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalSizeBeforeTrans () inline
References tfft3d::kX, and tfft3d::kY.
getLocalSizeBeforeTrans_Dealias()
template<int id> auto solver::fluidsol::CartFFD< 3, id >::getLocalSizeBeforeTrans_Dealias () inline
References tfft3d::kX, and tfft3d::kY.
Init()
template<int id> void solver::fluidsol::CartFFD< 3, id >::Init () inline
References mathconst::cONE(), tfft3d::FFT3D< T_real, GroupID, TypeID >::getLocalIndexAfterTrans(), tfft3d::FFT3D< T_real, GroupID, TypeID >::getMaxBufferSize(), tfft3d::kDFTc2c, tfft3d::kDFTr2c, tfft3d::kNULL, tfft3d::kX, tfft3d::kY, tfft3d::kZ, quadpack::max(), quadpack::min(), mathconst::PI, and tfft3d::FFT3D< T_real, GroupID, TypeID >::setSizeBeforeTrans().
Lap()
template<int id> void solver::fluidsol::CartFFD< 3, id >::Lap (blin::Array3cr & in, blin::Array3cr & out, Real alpha = 1., Real beta = 0.) inline
TransformC2R()
template<int id> void solver::fluidsol::CartFFD< 3, id >::TransformC2R (blin::Array3cr & in, blin::Array3r & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::BackwardTrans(), and tfft3d::kBefore.
TransformC2R_Dealias()
template<int id> void solver::fluidsol::CartFFD< 3, id >::TransformC2R_Dealias (blin::Array3cr & in, blin::Array3r & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::BackwardTrans(), and tfft3d::kBefore.
TransformR2C()
template<int id> void solver::fluidsol::CartFFD< 3, id >::TransformR2C (blin::Array3r & in, blin::Array3cr & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::ForwardTrans(), and tfft3d::kAfter.
TransformR2C_Dealias()
template<int id> void solver::fluidsol::CartFFD< 3, id >::TransformR2C_Dealias (blin::Array3r & in, blin::Array3cr & out) inline
References tfft3d::FFT3D< T_real, GroupID, TypeID >::ForwardTrans(), and tfft3d::kAfter.
Member Data Documentation
ctemp
template<int id> blin::Array1cr solver::fluidsol::CartFFD< 3, id >::ctemp
dealias
template<int id> tfft3d::FFT3D<Real, 201 + id * 1000> solver::fluidsol::CartFFD< 3, id >::dealias
decomp
template<int id> tfft3d::Cart3DPencilDecomp<Real, -101 - id * 1000> solver::fluidsol::CartFFD< 3, id >::decomp
decomp_de
template<int id> tfft3d::Cart3DPencilDecomp<Real, -201 - id * 1000> solver::fluidsol::CartFFD< 3, id >::decomp_de
ed
template<int id> std::vector<int> solver::fluidsol::CartFFD< 3, id >::ed
ghx
template<int id> int solver::fluidsol::CartFFD< 3, id >::ghx
ghy
template<int id> int solver::fluidsol::CartFFD< 3, id >::ghy
ghz
template<int id> int solver::fluidsol::CartFFD< 3, id >::ghz
ikx
template<int id> blin::Array1cr solver::fluidsol::CartFFD< 3, id >::ikx
iky
template<int id> blin::Array1cr solver::fluidsol::CartFFD< 3, id >::iky
kmax
template<int id> Real solver::fluidsol::CartFFD< 3, id >::kmax
kx
template<int id> blin::Array1r solver::fluidsol::CartFFD< 3, id >::kx
ky
template<int id> blin::Array1r solver::fluidsol::CartFFD< 3, id >::ky
lx
template<int id> Real solver::fluidsol::CartFFD< 3, id >::lx
ly
template<int id> Real solver::fluidsol::CartFFD< 3, id >::ly
lz
template<int id> Real solver::fluidsol::CartFFD< 3, id >::lz
mx
template<int id> int solver::fluidsol::CartFFD< 3, id >::mx
my
template<int id> int solver::fluidsol::CartFFD< 3, id >::my
mz
template<int id> int solver::fluidsol::CartFFD< 3, id >::mz
npc
template<int id> int solver::fluidsol::CartFFD< 3, id >::npc
npr
template<int id> int solver::fluidsol::CartFFD< 3, id >::npr
nx
template<int id> int solver::fluidsol::CartFFD< 3, id >::nx
ny
template<int id> int solver::fluidsol::CartFFD< 3, id >::ny
nz
template<int id> int solver::fluidsol::CartFFD< 3, id >::nz
one_nxy
template<int id> Real solver::fluidsol::CartFFD< 3, id >::one_nxy
one_nxy_de
template<int id> Real solver::fluidsol::CartFFD< 3, id >::one_nxy_de
origin
template<int id> tfft3d::FFT3D<Real, 101 + id * 1000> solver::fluidsol::CartFFD< 3, id >::origin
rtemp
template<int id> blin::Array1r solver::fluidsol::CartFFD< 3, id >::rtemp
st
template<int id> std::vector<int> solver::fluidsol::CartFFD< 3, id >::st
xr
template<int id> Real solver::fluidsol::CartFFD< 3, id >::xr
yr
template<int id> Real solver::fluidsol::CartFFD< 3, id >::yr
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/Solver/FluidSol/SpecDiffHybrid/BoxFFD/CartFFD.hpp