PhyStar: smart Namespace Reference
smart Namespace Reference
Classes
class Actor
class OrientationActor
class Agent
class OptimalSurfingAgent
class FluidVelGradSensor
class Sensor
Functions
static std::shared_ptr< Actor > _ActorSelector (std::string actorName)
select actor according to its name
static std::vector< std::shared_ptr< Actor > > ActorFactory (toml::table &config)
create a shared_ptr of a actor
static std::shared_ptr< Agent > _AgentSelector (std::string agentName)
select actor according to its name
static std::vector< std::shared_ptr< Agent > > AgentFactory (tml::table &config)
create a shared_ptr of a actor
static std::shared_ptr< Sensor > _SensorSelector (std::string sensorName)
select sensor according to its name
static std::vector< std::shared_ptr< Sensor > > SensorFactory (toml::table &config)
create a shared_ptr of a sensor
Detailed Description
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
This file is part of PhyStar, a C++ library for solving mulit-physics fields.
               _____  _            _____ _
              |  __ \| |          / ____| |
              | |__) | |__  _   _| (___ | |_ __ _ _ __
              |  ___/| '_ \| | | |\___ \| __/ _` | '__|
              | |    | | | | |_| |____) | || (_| | |
              |_|    |_| |_|\__, |_____/ \__\__,_|_|
                             __/ |
                            |___/
Copyright (C) 2022 Zhiwen Cui czw17.nosp@m.@tsi.nosp@m.nghua.nosp@m..org.nosp@m..cn Copyright (C) 2022-2024 Lihao Zhao zhaol.nosp@m.ihao.nosp@m.@tsin.nosp@m.ghua.nosp@m..edu..nosp@m.cn
This source code is an in-house code. Unauthorized disclosure, copying, or distribution of any portion of this code is prohibited.
This source code is for internal or collaborative use only. It may not be used
for commercial purposes or outside projects without explicit written permission.
Function Documentation
_ActorSelector()
static std::shared_ptr< Actor > smart::_ActorSelector (std::string actorName) static
select actor according to its name
Parameters
actorName
Returns
std::shared_ptr<Actor>
References smart::OrientationActor::_name().
_AgentSelector()
static std::shared_ptr< Agent > smart::_AgentSelector (std::string agentName) static
select actor according to its name
Parameters
actorName
Returns
std::shared_ptr<Actor>
References smart::OptimalSurfingAgent::_name().
_SensorSelector()
static std::shared_ptr< Sensor > smart::_SensorSelector (std::string sensorName) static
select sensor according to its name
Parameters
sensorName
Returns
std::shared_ptr<Sensor>
ActorFactory()
static std::vector<std::shared_ptr<Actor> > smart::ActorFactory (toml::table & config) static
create a shared_ptr of a actor
Parameters
config toml config
Returns
std::shared_ptr<Actor> the actor
References _ActorSelector(), and gsmpi::root.
AgentFactory()
static std::vector<std::shared_ptr<Agent> > smart::AgentFactory (tml::table & config) static
create a shared_ptr of a actor
Parameters
config toml config
Returns
std::shared_ptr<Actor> the actor
References _AgentSelector(), and gsmpi::root.
SensorFactory()
static std::vector<std::shared_ptr<Sensor> > smart::SensorFactory (toml::table & config) static
create a shared_ptr of a sensor
Parameters
config toml config
Returns
std::shared_ptr<Sensor> the sensor
References _SensorSelector(), and gsmpi::root.