PhyStar: dmdyn::CoupleCart< N_dim > Struct Template Reference
dmdyn::CoupleCart< N_dim > Struct Template Reference
#include <CoupleCart.hpp>
Public Types
using Field = blockelm::CartField< Real, N_dim >
Public Member Functions
CoupleCart ()
void Init (blockelm::CartBlock< N_dim > &block, tml::tmlnode &ibtml, gsmpi::GSMPICart< N_dim > *mpicomm_)
auto & AddCartFieldRef (Field *ptr)
auto & ClearCartFieldRef ()
void GetNearestGridIndex (blockelm::CartMesh< N_dim > &mesh, Vecr< N_dim > &pos)
void GetNearestGridIndex (Field &in, Vecr< N_dim > &pos)
void CalCouple (SmartPList< ParticleField< N_dim >> &pflist, Real dt, int ratio_dt_dtp)
void CalCoupleForce (SmartPList< ParticleField< N_dim >> &pflist, Real dt, int ratio_dt_dtp)
void CalCoupleTorque (SmartPList< ParticleField< N_dim >> &pflist, Real dt, int ratio_dt_dtp)
void CalCoupleStresslet (SmartPList< ParticleField< N_dim >> &pflist, Real dt, int ratio_dt_dtp)
void SetGridSize (Real &dr, int dim, int index)
Public Member Functions inherited from dmdyn::CoupleBase< N_dim >
CoupleBase ()
void Init (tml::tmlnode &ibtml)
Public Attributes
gsmpi::GSMPICart< N_dim > * mpicomm
std::vector< Field * > ptr_fieldlist
blockelm::CartBlock< N_dim > * ptr_block = nullptr
std::vector< Real > ghost_width
Veci< N_dim > ind_of_grid
Public Attributes inherited from dmdyn::CoupleBase< N_dim >
struct dmdyn::CoupleBase::Option option
Member Typedef Documentation
Field
template<int N_dim> using dmdyn::CoupleCart< N_dim >::Field = blockelm::CartField<Real, N_dim>
Constructor & Destructor Documentation
CoupleCart()
template<int N_dim> dmdyn::CoupleCart< N_dim >::CoupleCart () inline
Member Function Documentation
AddCartFieldRef()
template<int N_dim> auto& dmdyn::CoupleCart< N_dim >::AddCartFieldRef (Field * ptr) inline
References dmdyn::CoupleCart< N_dim >::ptr_fieldlist.
CalCouple()
template<int N_dim> void dmdyn::CoupleCart< N_dim >::CalCouple (SmartPList< ParticleField< N_dim >> & pflist, Real dt, int ratio_dt_dtp) inline
References dmdyn::CoupleCart< N_dim >::CalCoupleForce(), dmdyn::CoupleCart< N_dim >::CalCoupleStresslet(), dmdyn::CoupleCart< N_dim >::CalCoupleTorque(), dmdyn::Force, dmdyn::Stresslet, and dmdyn::Torque.
CalCoupleForce()
template<int N_dim> void dmdyn::CoupleCart< N_dim >::CalCoupleForce (SmartPList< ParticleField< N_dim >> & pflist, Real dt, int ratio_dt_dtp) inline
References dmdyn::DeltaFunMap< N_dim >::Delta(), blockelm::CartField< T, N_dim >::GetMesh(), dmdyn::CoupleCart< N_dim >::GetNearestGridIndex(), dmdyn::CoupleCart< N_dim >::ind_of_grid, dmdyn::CoupleCart< N_dim >::ptr_block, dmdyn::CoupleCart< N_dim >::ptr_fieldlist, dmdyn::CoupleCart< N_dim >::SetGridSize(), and blockelm::CartField< T, N_dim >::shape.
CalCoupleStresslet()
template<int N_dim> void dmdyn::CoupleCart< N_dim >::CalCoupleStresslet (SmartPList< ParticleField< N_dim >> & pflist, Real dt, int ratio_dt_dtp) inline
CalCoupleTorque()
template<int N_dim> void dmdyn::CoupleCart< N_dim >::CalCoupleTorque (SmartPList< ParticleField< N_dim >> & pflist, Real dt, int ratio_dt_dtp) inline
ClearCartFieldRef()
template<int N_dim> auto& dmdyn::CoupleCart< N_dim >::ClearCartFieldRef () inline
References dmdyn::CoupleCart< N_dim >::ptr_fieldlist.
GetNearestGridIndex() [1/2]
template<int N_dim> void dmdyn::CoupleCart< N_dim >::GetNearestGridIndex (blockelm::CartMesh< N_dim > & mesh, Vecr< N_dim > & pos) inline
References dmdyn::CoupleCart< N_dim >::ind_of_grid, and blockelm::CartMesh< N_dim >::meshc.
GetNearestGridIndex() [2/2]
template<int N_dim> void dmdyn::CoupleCart< N_dim >::GetNearestGridIndex (Field & in, Vecr< N_dim > & pos) inline
References blockelm::CartField< T, N_dim >::GetMesh(), and dmdyn::CoupleCart< N_dim >::ind_of_grid.
Init()
template<int N_dim> void dmdyn::CoupleCart< N_dim >::Init (blockelm::CartBlock< N_dim > & block, tml::tmlnode & ibtml, gsmpi::GSMPICart< N_dim > * mpicomm_) inline
References dmdyn::CoupleBase< N_dim >::Init(), dmdyn::CoupleCart< N_dim >::mpicomm, and dmdyn::CoupleCart< N_dim >::ptr_block.
SetGridSize()
template<int N_dim> void dmdyn::CoupleCart< N_dim >::SetGridSize (Real & dr, int dim, int index) inline
References blockelm::CartField< T, N_dim >::GetMesh(), dmdyn::CoupleCart< N_dim >::mpicomm, dmdyn::CoupleCart< N_dim >::ptr_fieldlist, and blockelm::CartField< T, N_dim >::shape.
Member Data Documentation
ghost_width
template<int N_dim> std::vector<Real> dmdyn::CoupleCart< N_dim >::ghost_width
ind_of_grid
template<int N_dim> Veci<N_dim> dmdyn::CoupleCart< N_dim >::ind_of_grid
mpicomm
template<int N_dim> gsmpi::GSMPICart<N_dim>* dmdyn::CoupleCart< N_dim >::mpicomm
ptr_block
template<int N_dim> blockelm::CartBlock<N_dim>* dmdyn::CoupleCart< N_dim >::ptr_block = nullptr
ptr_fieldlist
template<int N_dim> std::vector<Field *> dmdyn::CoupleCart< N_dim >::ptr_fieldlist
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/DMDyn/TwoWayCouple/CoupleCart.hpp