PhyStar: dmdyn::ParticleField< N_dim > Struct Template Reference
dmdyn::ParticleField< N_dim > Struct Template Reference
#include <ParticleField.hpp>
Public Member Functions
ParticleField ()
ParticleField (int N, int M=0)
void Init (int N=0, int M=0)
void InitPModelData (int size)
void InitContactForce ()
void InitFluidForce ()
void InitInternalForce ()
ParticleField & operator= (const ParticleField &p)
ParticleField (const ParticleField &p)
std::string ParticleIDHex ()
print Hex particleid
std::string ParticleID ()
void ReadFromParticleIDHex (const char s[])
void ReadFromParticleID (const char s[])
PartID getParticleID ()
void updateParticleID (PartID &temp)
auto & ConvertToIOPData (fileio::IOPData3DBasicD &iopdata, const int n_ext=0)
auto & ConvertToIOPData (fileio::IOPData2DBasicD &iopdata, const int n_ext=0)
auto & ConvertToIOPData (fileio::IOPData3DOnlyFluidD &iopdata, const int n_ext=0)
auto & ConvertToIOPData (fileio::IOPData2DOnlyFluidD &iopdata, const int n_ext=0)
void ConvertFromIOPData (fileio::IOPData3DBasicD &iopdata, const int n_ext=0)
void ConvertFromIOPData (fileio::IOPData2DBasicD &iopdata, const int n_ext=0)
void ConvertFromIOPData (fileio::IOPData3DOnlyFluidD &iopdata, const int n_ext=0)
void ConvertFromIOPData (fileio::IOPData2DOnlyFluidD &iopdata, const int n_ext=0)
int SerializedLen ()
void Serialize (int block, gsmpi::SerializedBuffer &buffer, const int n_ext)
void Unserialize (int block, gsmpi::SerializedBuffer &buffer, const int n_ext)
int ShortSerializedLen ()
void ShortSerialize (int block, gsmpi::SerializedBuffer &buffer)
void ShortUnserialize (int block, gsmpi::SerializedBuffer &buffer)
const auto & GetPos ()
const auto & GetPos (int i)
Public Member Functions inherited from dmdyn::ContactData< N_dim >
ContactData ()
ContactData (const ContactData &p)
void CleanAll ()
void resizeContactData (int n)
ContactData & operator= (const ContactData &p)
void vectorToArray (Array1< uInt > &nbrs_pp_contact_arr, Array1< uInt > &nbrs_contact_stage_old_arr, Array1r &disp_tan_old_arr, Array1r &impart_vel_old_arr)
void arrayToVector (Array1< uInt > &nbrs_pp_contact_arr, Array1< uInt > &nbrs_contact_stage_old_arr, Array1r &disp_tan_old_arr, Array1r &impart_vel_old_arr)
int SerializedLen ()
void Serialize (int block, gsmpi::SerializedBuffer &buffer)
void Unserialize (int block, gsmpi::SerializedBuffer &buffer)
Public Member Functions inherited from dmdyn::SmartData< N_dim >
SmartData ()
SmartData (const SmartData &p)
void CleanAll ()
SmartData & operator= (const SmartData &p)
int SerializedLen ()
void Serialize (int block, gsmpi::SerializedBuffer &buffer)
void Unserialize (int block, gsmpi::SerializedBuffer &buffer)
Public Attributes
ParticleData< N_dim > pdata
PFluidData< N_dim > fdata
Array1< ParticleData< N_dim > > pext
Array1< PFluidData< N_dim > > fext
Vecr< N_dim > fluid_force
Vecr< N_dim > fluid_torque
Vecr< N_dim > contact_force
Vecr< N_dim > contact_torque
Vecr< N_dim > internal_force
Vecr< N_dim > internal_torque
Vecr< N_dim > old_internal_force
Vecr< N_dim > old_internal_torque
Real one_dt_old = 0.
uInt id
uInt block_init
uInt particle_typeid = 0
Real dtp
Real dtc
int rk_step
int np_step
int ncollid_step
int time_scheme
bool is_wpregion = false
Array1< Real > pmodel_data
Public Attributes inherited from dmdyn::ContactData< N_dim >
std::vector< int > nbrs_pp_index
std::vector< PartID > nbrs_pp_contact
std::vector< uInt > nbrs_contact_init_state
std::vector< Vecr< N_dim > > disp_tan_new
std::vector< Vecr< N_dim > > disp_tan_old
std::vector< Real > impart_vel_new
std::vector< Real > impart_vel_old
std::vector< Veci< 4 > > nbrs_contact_stage_new
std::vector< Veci< 4 > > nbrs_contact_stage_old
std::vector< Veci< 3 > > if_cal_once
int curr_ind
Public Attributes inherited from dmdyn::SmartData< N_dim >
Array1< Real > state
Array1< Real > action
Static Public Attributes
static int ndim = N_dim
Constructor & Destructor Documentation
ParticleField() [1/3]
template<int N_dim> dmdyn::ParticleField< N_dim >::ParticleField () inline
ParticleField() [2/3]
template<int N_dim> dmdyn::ParticleField< N_dim >::ParticleField (int N, int M = 0) inline
References dmdyn::N.
ParticleField() [3/3]
template<int N_dim> dmdyn::ParticleField< N_dim >::ParticleField (const ParticleField< N_dim > & p) inline
References dmdyn::ParticleField< N_dim >::block_init, dmdyn::ParticleField< N_dim >::contact_force, dmdyn::ParticleField< N_dim >::contact_torque, dmdyn::ParticleField< N_dim >::dtc, dmdyn::ParticleField< N_dim >::dtp, dmdyn::ParticleField< N_dim >::fdata, dmdyn::ParticleField< N_dim >::fext, dmdyn::ParticleField< N_dim >::fluid_force, dmdyn::ParticleField< N_dim >::fluid_torque, dmdyn::ParticleField< N_dim >::id, dmdyn::ParticleField< N_dim >::internal_force, dmdyn::ParticleField< N_dim >::internal_torque, dmdyn::ParticleField< N_dim >::ncollid_step, dmdyn::ParticleField< N_dim >::np_step, dmdyn::ParticleField< N_dim >::old_internal_force, dmdyn::ParticleField< N_dim >::old_internal_torque, dmdyn::ParticleField< N_dim >::one_dt_old, dmdyn::ParticleField< N_dim >::particle_typeid, dmdyn::ParticleField< N_dim >::pdata, dmdyn::ParticleField< N_dim >::pext, dmdyn::ParticleField< N_dim >::pmodel_data, dmdyn::ParticleField< N_dim >::rk_step, and dmdyn::ParticleField< N_dim >::time_scheme.
Member Function Documentation
ConvertFromIOPData() [1/4]
template<int N_dim> void dmdyn::ParticleField< N_dim >::ConvertFromIOPData (fileio::IOPData2DBasicD & iopdata, const int n_ext = 0) inline
References fileio::IOPData< N_real, T_real, N_int, T_int >::partid.
ConvertFromIOPData() [2/4]
template<int N_dim> void dmdyn::ParticleField< N_dim >::ConvertFromIOPData (fileio::IOPData2DOnlyFluidD & iopdata, const int n_ext = 0) inline
References dmdyn::PFluidData< N_dim >::ConvertFromIOPData().
ConvertFromIOPData() [3/4]
template<int N_dim> void dmdyn::ParticleField< N_dim >::ConvertFromIOPData (fileio::IOPData3DBasicD & iopdata, const int n_ext = 0) inline
References fileio::IOPData< N_real, T_real, N_int, T_int >::partid.
ConvertFromIOPData() [4/4]
template<int N_dim> void dmdyn::ParticleField< N_dim >::ConvertFromIOPData (fileio::IOPData3DOnlyFluidD & iopdata, const int n_ext = 0) inline
References dmdyn::PFluidData< N_dim >::ConvertFromIOPData().
ConvertToIOPData() [1/4]
template<int N_dim> auto& dmdyn::ParticleField< N_dim >::ConvertToIOPData (fileio::IOPData2DBasicD & iopdata, const int n_ext = 0) inline
References fileio::IOPData< N_real, T_real, N_int, T_int >::partid.
ConvertToIOPData() [2/4]
template<int N_dim> auto& dmdyn::ParticleField< N_dim >::ConvertToIOPData (fileio::IOPData2DOnlyFluidD & iopdata, const int n_ext = 0) inline
References dmdyn::PFluidData< N_dim >::ConvertToIOPData(), and fileio::IOPData< N_real, T_real, N_int, T_int >::partid.
ConvertToIOPData() [3/4]
template<int N_dim> auto& dmdyn::ParticleField< N_dim >::ConvertToIOPData (fileio::IOPData3DBasicD & iopdata, const int n_ext = 0) inline
References fileio::IOPData< N_real, T_real, N_int, T_int >::partid.
ConvertToIOPData() [4/4]
template<int N_dim> auto& dmdyn::ParticleField< N_dim >::ConvertToIOPData (fileio::IOPData3DOnlyFluidD & iopdata, const int n_ext = 0) inline
References dmdyn::PFluidData< N_dim >::ConvertToIOPData(), and fileio::IOPData< N_real, T_real, N_int, T_int >::partid.
getParticleID()
template<int N_dim> PartID dmdyn::ParticleField< N_dim >::getParticleID () inline
GetPos() [1/2]
template<int N_dim> const auto& dmdyn::ParticleField< N_dim >::GetPos () inline
GetPos() [2/2]
template<int N_dim> const auto& dmdyn::ParticleField< N_dim >::GetPos (int i) inline
Init()
template<int N_dim> void dmdyn::ParticleField< N_dim >::Init (int N = 0, int M = 0) inline
References dmdyn::ContactData< N_dim >::CleanAll(), dmdyn::SmartData< N_dim >::CleanAll(), and dmdyn::N.
InitContactForce()
template<int N_dim> void dmdyn::ParticleField< N_dim >::InitContactForce () inline
InitFluidForce()
template<int N_dim> void dmdyn::ParticleField< N_dim >::InitFluidForce () inline
InitInternalForce()
template<int N_dim> void dmdyn::ParticleField< N_dim >::InitInternalForce () inline
InitPModelData()
template<int N_dim> void dmdyn::ParticleField< N_dim >::InitPModelData (int size) inline
operator=()
template<int N_dim> ParticleField& dmdyn::ParticleField< N_dim >::operator= (const ParticleField< N_dim > & p) inline
References dmdyn::ParticleField< N_dim >::block_init, dmdyn::ParticleField< N_dim >::contact_force, dmdyn::ParticleField< N_dim >::contact_torque, dmdyn::ParticleField< N_dim >::dtc, dmdyn::ParticleField< N_dim >::dtp, dmdyn::ParticleField< N_dim >::fdata, dmdyn::ParticleField< N_dim >::fext, dmdyn::ParticleField< N_dim >::fluid_force, dmdyn::ParticleField< N_dim >::fluid_torque, dmdyn::ParticleField< N_dim >::id, dmdyn::ParticleField< N_dim >::internal_force, dmdyn::ParticleField< N_dim >::internal_torque, dmdyn::ParticleField< N_dim >::ncollid_step, dmdyn::ParticleField< N_dim >::np_step, dmdyn::ParticleField< N_dim >::old_internal_force, dmdyn::ParticleField< N_dim >::old_internal_torque, dmdyn::ParticleField< N_dim >::one_dt_old, dmdyn::ContactData< N_dim >::operator=(), dmdyn::SmartData< N_dim >::operator=(), dmdyn::ParticleField< N_dim >::particle_typeid, dmdyn::ParticleField< N_dim >::pdata, dmdyn::ParticleField< N_dim >::pext, dmdyn::ParticleField< N_dim >::pmodel_data, dmdyn::ParticleField< N_dim >::rk_step, and dmdyn::ParticleField< N_dim >::time_scheme.
ParticleID()
template<int N_dim> std::string dmdyn::ParticleField< N_dim >::ParticleID () inline
ParticleIDHex()
template<int N_dim> std::string dmdyn::ParticleField< N_dim >::ParticleIDHex () inline
print Hex particleid
Returns
std::string
ReadFromParticleID()
template<int N_dim> void dmdyn::ParticleField< N_dim >::ReadFromParticleID (const char s[]) inline
ReadFromParticleIDHex()
template<int N_dim> void dmdyn::ParticleField< N_dim >::ReadFromParticleIDHex (const char s[]) inline
Serialize()
template<int N_dim> void dmdyn::ParticleField< N_dim >::Serialize (int block, gsmpi::SerializedBuffer & buffer, const int n_ext) inline
References gsmpi::SerializedBuffer::Add(), gsmpi::SerializedBuffer::AddArr(), gsmpi::SerializedBuffer::AddBlinVec(), dmdyn::ContactData< N_dim >::Serialize(), and dmdyn::SmartData< N_dim >::Serialize().
SerializedLen()
template<int N_dim> int dmdyn::ParticleField< N_dim >::SerializedLen () inline
References dmdyn::ContactData< N_dim >::SerializedLen(), and dmdyn::SmartData< N_dim >::SerializedLen().
ShortSerialize()
template<int N_dim> void dmdyn::ParticleField< N_dim >::ShortSerialize (int block, gsmpi::SerializedBuffer & buffer) inline
References gsmpi::SerializedBuffer::Add(), gsmpi::SerializedBuffer::AddArr(), and gsmpi::SerializedBuffer::AddBlinVec().
ShortSerializedLen()
template<int N_dim> int dmdyn::ParticleField< N_dim >::ShortSerializedLen () inline
ShortUnserialize()
template<int N_dim> void dmdyn::ParticleField< N_dim >::ShortUnserialize (int block, gsmpi::SerializedBuffer & buffer) inline
References gsmpi::SerializedBuffer::Get(), gsmpi::SerializedBuffer::GetArr(), and gsmpi::SerializedBuffer::GetBlinVec().
Unserialize()
template<int N_dim> void dmdyn::ParticleField< N_dim >::Unserialize (int block, gsmpi::SerializedBuffer & buffer, const int n_ext) inline
References gsmpi::SerializedBuffer::Get(), gsmpi::SerializedBuffer::GetArr(), gsmpi::SerializedBuffer::GetBlinVec(), dmdyn::ContactData< N_dim >::Unserialize(), and dmdyn::SmartData< N_dim >::Unserialize().
updateParticleID()
template<int N_dim> void dmdyn::ParticleField< N_dim >::updateParticleID (PartID & temp) inline
Member Data Documentation
block_init
template<int N_dim> uInt dmdyn::ParticleField< N_dim >::block_init
contact_force
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::contact_force
contact_torque
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::contact_torque
dtc
template<int N_dim> Real dmdyn::ParticleField< N_dim >::dtc
dtp
template<int N_dim> Real dmdyn::ParticleField< N_dim >::dtp
fdata
template<int N_dim> PFluidData<N_dim> dmdyn::ParticleField< N_dim >::fdata
fext
template<int N_dim> Array1<PFluidData<N_dim> > dmdyn::ParticleField< N_dim >::fext
fluid_force
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::fluid_force
fluid_torque
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::fluid_torque
id
template<int N_dim> uInt dmdyn::ParticleField< N_dim >::id
internal_force
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::internal_force
internal_torque
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::internal_torque
is_wpregion
template<int N_dim> bool dmdyn::ParticleField< N_dim >::is_wpregion = false
ncollid_step
template<int N_dim> int dmdyn::ParticleField< N_dim >::ncollid_step
ndim
template<int N_dim> int dmdyn::ParticleField< N_dim >::ndim = N_dim inline static
np_step
template<int N_dim> int dmdyn::ParticleField< N_dim >::np_step
old_internal_force
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::old_internal_force
old_internal_torque
template<int N_dim> Vecr<N_dim> dmdyn::ParticleField< N_dim >::old_internal_torque
one_dt_old
template<int N_dim> Real dmdyn::ParticleField< N_dim >::one_dt_old = 0.
particle_typeid
template<int N_dim> uInt dmdyn::ParticleField< N_dim >::particle_typeid = 0
pdata
template<int N_dim> ParticleData<N_dim> dmdyn::ParticleField< N_dim >::pdata
pext
template<int N_dim> Array1<ParticleData<N_dim> > dmdyn::ParticleField< N_dim >::pext
pmodel_data
template<int N_dim> Array1<Real> dmdyn::ParticleField< N_dim >::pmodel_data
rk_step
template<int N_dim> int dmdyn::ParticleField< N_dim >::rk_step
time_scheme
template<int N_dim> int dmdyn::ParticleField< N_dim >::time_scheme
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/DMDyn/DataStruct/ParticleField.hpp