PhyStar: ibm::IBMBase< N_dim > Struct Template Reference
ibm::IBMBase< N_dim > Struct Template Reference abstract
#include <IBMBase.hpp>
Classes
struct Geom
struct IBVelBoundary
struct Option
Public Member Functions
IBMBase ()
IBMBase (int id_, std::string filename, tml::tmlnode &ibtml)
IBMBase (int id_, std::vector< Real > pos_ref0, Option &option0)
void Create (int id_, std::string filename, tml::tmlnode &ibtml)
void ConfigGeo (tml::tmlnode &ibtml)
void CreateGeo ()
create wall geometry from toml
auto & GetCollObj ()
Real GetMeanArea ()
virtual void SetIBSolType (IBMSolType soltype0)
virtual void SetIBMethod (IBMethod method0, std::vector< Real > para={})
void SetMPI (const MPI_Comm comm_)
virtual bool IsInside (const blin::Vecr< N_dim > &pos)=0
virtual bool IsInsideWithGhostWidth (const blin::Vecr< N_dim > &pos)=0
virtual bool IsInsideWithMaxCollisionWidth (const blin::Vecr< N_dim > &pos)=0
virtual void Perpare ()=0
void LoadLagPoints (std::string filename)
void AddNode (auto &nd)
void AddVirtualNode (auto &nd)
void AddElm (auto &elm)
void AddVirtualElm (auto &elm)
void InitIBPoints ()
void UpdateIBPoints (dmdyn::ParticleData< N_dim > &pdata)
update ib points by input pdata
void PrintIBPoints ()
void VelocityBoundary ()
auto & CalLocalForceAndTorque ()
auto & CalLocalForceAndTorque (blin::Vecr< N_dim > &ref)
auto CalTotalForceAndTorque ()
void InitForceLog (std::string path, bool iconti)
void ForceLog (std::string path, bool iconti, int istep, Real time)
std::vector< algo::fcl::Vec3f > GenerateFCLPoints ()
void GenerateBVHMesh ()
Public Attributes
int id
MPI_Comm comm
blin::Vecr< N_dim > pos_ref = 0.0
struct ibm::IBMBase::Option option
struct ibm::IBMBase::Geom geo
struct ibm::IBMBase::IBVelBoundary ibvelb
dmdyn::SmartPList< IBPoint< N_dim > > ibpoints
std::unordered_map< int, int > nodeid
std::unordered_map< int, int > elmid
dmdyn::SmartPList< IBNode< N_dim > > nodes
dmdyn::SmartPList< IBElement< N_dim > > elements
Force< N_dim > local
Force< N_dim > total = {0.0, 0.0}
Vecr< N_dim > dr
Real mean_ds = -999.0
Constructor & Destructor Documentation
IBMBase() [1/3]
template<int N_dim> ibm::IBMBase< N_dim >::IBMBase () inline
IBMBase() [2/3]
template<int N_dim> ibm::IBMBase< N_dim >::IBMBase (int id_, std::string filename, tml::tmlnode & ibtml) inline
References ibm::IBMBase< N_dim >::Create().
IBMBase() [3/3]
template<int N_dim> ibm::IBMBase< N_dim >::IBMBase (int id_, std::vector< Real > pos_ref0, Option & option0) inline
References ibm::IBMBase< N_dim >::option, and ibm::IBMBase< N_dim >::pos_ref.
Member Function Documentation
AddElm()
template<int N_dim> void ibm::IBMBase< N_dim >::AddElm (auto & elm) inline
References ibm::IBElement< N_dim >::ds, ibm::IBMBase< N_dim >::elements, ibm::IBMBase< N_dim >::elmid, ibm::IBElement< N_dim >::id, ibm::IBMBase< N_dim >::IsInside(), ibm::IBElement< N_dim >::isinside, ibm::IBElement< N_dim >::isinside_extend, ibm::IBMBase< N_dim >::IsInsideWithGhostWidth(), ibm::IBElement< N_dim >::nodelist, ibm::IBElement< N_dim >::pos, and ibm::IBMBase< N_dim >::pos_ref.
AddNode()
template<int N_dim> void ibm::IBMBase< N_dim >::AddNode (auto & nd) inline
References ibm::IBNode< N_dim >::elmlist, ibm::IBNode< N_dim >::id, ibm::IBMBase< N_dim >::IsInside(), ibm::IBNode< N_dim >::isinside, ibm::IBNode< N_dim >::isinside_extend, ibm::IBMBase< N_dim >::IsInsideWithGhostWidth(), ibm::IBMBase< N_dim >::nodeid, ibm::IBMBase< N_dim >::nodes, ibm::IBNode< N_dim >::pos, and ibm::IBMBase< N_dim >::pos_ref.
AddVirtualElm()
template<int N_dim> void ibm::IBMBase< N_dim >::AddVirtualElm (auto & elm) inline
References ibm::IBElement< N_dim >::ds, ibm::IBMBase< N_dim >::elements, ibm::IBMBase< N_dim >::elmid, ibm::IBElement< N_dim >::id, ibm::IBMBase< N_dim >::IsInside(), ibm::IBElement< N_dim >::isinside, ibm::IBElement< N_dim >::isinside_extend, ibm::IBMBase< N_dim >::IsInsideWithGhostWidth(), ibm::IBElement< N_dim >::nodelist, ibm::IBElement< N_dim >::pos, and ibm::IBMBase< N_dim >::pos_ref.
AddVirtualNode()
template<int N_dim> void ibm::IBMBase< N_dim >::AddVirtualNode (auto & nd) inline
References ibm::IBNode< N_dim >::elmlist, ibm::IBNode< N_dim >::id, ibm::IBMBase< N_dim >::IsInside(), ibm::IBNode< N_dim >::isinside, ibm::IBNode< N_dim >::isinside_extend, ibm::IBMBase< N_dim >::IsInsideWithGhostWidth(), ibm::IBMBase< N_dim >::nodeid, ibm::IBMBase< N_dim >::nodes, ibm::IBNode< N_dim >::pos, and ibm::IBMBase< N_dim >::pos_ref.
CalLocalForceAndTorque() [1/2]
template<int N_dim> auto& ibm::IBMBase< N_dim >::CalLocalForceAndTorque () inline
References ibm::IBMBase< N_dim >::pos_ref.
CalLocalForceAndTorque() [2/2]
template<int N_dim> auto& ibm::IBMBase< N_dim >::CalLocalForceAndTorque (blin::Vecr< N_dim > & ref) inline
References dmdyn::angular::CrossVec3(), ibm::IBMBase< N_dim >::dr, ibm::IBMBase< N_dim >::ibpoints, and ibm::IBMBase< N_dim >::local.
CalTotalForceAndTorque()
template<int N_dim> auto ibm::IBMBase< N_dim >::CalTotalForceAndTorque () inline
References ibm::IBMBase< N_dim >::CalLocalForceAndTorque(), ibm::IBMBase< N_dim >::comm, ibm::IBMBase< N_dim >::local, and ibm::IBMBase< N_dim >::total.
ConfigGeo()
template<int N_dim> void ibm::IBMBase< N_dim >::ConfigGeo (tml::tmlnode & ibtml)
References ibm::vConfigGeoType().
Create()
template<int N_dim> void ibm::IBMBase< N_dim >::Create (int id_, std::string filename, tml::tmlnode & ibtml)
References ibm::vConfigDeltaFunType(), ibm::vConfigDeltaWidth(), ibm::vConfigIBVelBType(), ibm::vConfigMethod(), and ibm::vConfigSolType().
CreateGeo()
template<int N_dim> void ibm::IBMBase< N_dim >::CreateGeo
create wall geometry from toml
Template Parameters
N_dim
References ibm::Box, ibm::BVHMesh, ibm::Capsule, ibm::Cone, ibm::Cylinder, ibm::Ellipsoid, dmdyn::SmartPList< T >::MaxLengthIncludeVirtual(), and ibm::Sphere.
ForceLog()
template<int N_dim> void ibm::IBMBase< N_dim >::ForceLog (std::string path, bool iconti, int istep, Real time) inline
References ibm::IBMBase< N_dim >::CalTotalForceAndTorque(), ibm::IBMBase< N_dim >::comm, ibm::IBMBase< N_dim >::option, ibm::IBMBase< N_dim >::Option::record_force, and ibm::IBMBase< N_dim >::total.
GenerateBVHMesh()
template<int N_dim> void ibm::IBMBase< N_dim >::GenerateBVHMesh
References dmdyn::SmartPList< T >::MaxLengthIncludeVirtual().
GenerateFCLPoints()
template<int N_dim> std::vector< algo::fcl::Vec3f > ibm::IBMBase< N_dim >::GenerateFCLPoints
References dmdyn::SmartPList< T >::MaxLengthIncludeVirtual().
GetCollObj()
template<int N_dim> auto& ibm::IBMBase< N_dim >::GetCollObj () inline
References ibm::IBMBase< N_dim >::Geom::collobj, and ibm::IBMBase< N_dim >::geo.
GetMeanArea()
template<int N_dim> Real ibm::IBMBase< N_dim >::GetMeanArea () inline
References ibm::IBMBase< N_dim >::mean_ds.
InitForceLog()
template<int N_dim> void ibm::IBMBase< N_dim >::InitForceLog (std::string path, bool iconti) inline
References ibm::IBMBase< N_dim >::comm, ibm::IBMBase< N_dim >::option, and ibm::IBMBase< N_dim >::Option::record_force.
InitIBPoints()
template<int N_dim> void ibm::IBMBase< N_dim >::InitIBPoints () inline
References dmdyn::AddOnly, ibm::IBPoint< N_dim >::ds, ibm::IBMBase< N_dim >::elements, ibm::IBMBase< N_dim >::ibpoints, ibm::IBPoint< N_dim >::id, ibm::IBPoint< N_dim >::isinside, ibm::IBPoint< N_dim >::isinside_extend, ibm::IBPoint< N_dim >::pos, and dmdyn::ReadOnly.
IsInside()
template<int N_dim> virtual bool ibm::IBMBase< N_dim >::IsInside (const blin::Vecr< N_dim > & pos) inline pure virtual
Implemented in ibm::IBMCart< N_dim >, and ibm::IBMCart< 3 >.
IsInsideWithGhostWidth()
template<int N_dim> virtual bool ibm::IBMBase< N_dim >::IsInsideWithGhostWidth (const blin::Vecr< N_dim > & pos) inline pure virtual
Implemented in ibm::IBMCart< N_dim >, and ibm::IBMCart< 3 >.
IsInsideWithMaxCollisionWidth()
template<int N_dim> virtual bool ibm::IBMBase< N_dim >::IsInsideWithMaxCollisionWidth (const blin::Vecr< N_dim > & pos) inline pure virtual
Implemented in ibm::IBMCart< N_dim >, and ibm::IBMCart< 3 >.
LoadLagPoints()
template<int N_dim> void ibm::IBMBase< N_dim >::LoadLagPoints (std::string filename) inline
References ibm::IBMBase< N_dim >::AddElm(), ibm::IBMBase< N_dim >::AddNode(), dmdyn::AddOnly, dmdyn::AddVirtualListOnly, ibm::IBMBase< N_dim >::AddVirtualNode(), ibm::IBMBase< N_dim >::elements, ibm::mshio::GmshReader< N_dim, T_real >::elmlist, ibm::IBMBase< N_dim >::Option::is_3dline, ibm::IBMBase< N_dim >::IsInsideWithMaxCollisionWidth(), ibm::IBMBase< N_dim >::mean_ds, ibm::mshio::GmshReader< N_dim, T_real >::MeanArea(), ibm::IBMBase< N_dim >::nodeid, ibm::mshio::GmshReader< N_dim, T_real >::nodelist, ibm::IBMBase< N_dim >::nodes, ibm::IBMBase< N_dim >::option, ibm::IBMBase< N_dim >::pos_ref, ibm::mshio::GmshReader< N_dim, T_real >::Print(), ibm::mshio::GmshReader< N_dim, T_real >::Read(), dmdyn::ReadOnly, ibm::SmallRigidBody, and ibm::IBMBase< N_dim >::Option::soltype.
Perpare()
template<int N_dim> virtual void ibm::IBMBase< N_dim >::Perpare () pure virtual
Implemented in ibm::IBMCart< N_dim >, and ibm::IBMCart< 3 >.
PrintIBPoints()
template<int N_dim> void ibm::IBMBase< N_dim >::PrintIBPoints () inline
References ibm::IBMBase< N_dim >::ibpoints.
SetIBMethod()
template<int N_dim> virtual void ibm::IBMBase< N_dim >::SetIBMethod (IBMethod method0, std::vector< Real > para = {}) inline virtual
SetIBSolType()
template<int N_dim> virtual void ibm::IBMBase< N_dim >::SetIBSolType (IBMSolType soltype0) inline virtual
References ibm::IBMBase< N_dim >::option, and ibm::IBMBase< N_dim >::Option::soltype.
SetMPI()
template<int N_dim> void ibm::IBMBase< N_dim >::SetMPI (const MPI_Comm comm_) inline
References ibm::IBMBase< N_dim >::comm.
UpdateIBPoints()
template<int N_dim> void ibm::IBMBase< N_dim >::UpdateIBPoints (dmdyn::ParticleData< N_dim > & pdata) inline
update ib points by input pdata
Parameters
pdata
References dmdyn::AddOnly, dmdyn::angular::CrossVec3(), ibm::IBPoint< N_dim >::ds, ibm::IBMBase< N_dim >::elements, ibm::IBMBase< N_dim >::ibpoints, ibm::IBPoint< N_dim >::id, ibm::IBMBase< N_dim >::IsInside(), ibm::IBPoint< N_dim >::isinside, ibm::IBPoint< N_dim >::isinside_extend, ibm::IBMBase< N_dim >::IsInsideWithGhostWidth(), ibm::IBPoint< N_dim >::pos, dmdyn::ReadOnly, dmdyn::angular::VecFromPFToIF3DimByee(), ibm::IBPoint< N_dim >::vel, and ibm::IBPoint< N_dim >::velb.
VelocityBoundary()
template<int N_dim> void ibm::IBMBase< N_dim >::VelocityBoundary () inline
References ibm::IBMBase< N_dim >::ibpoints, ibm::IBMBase< N_dim >::ibvelb, ibm::IBMBase< N_dim >::IBVelBoundary::params, and ibm::IBMBase< N_dim >::IBVelBoundary::type.
Member Data Documentation
comm
template<int N_dim> MPI_Comm ibm::IBMBase< N_dim >::comm
dr
template<int N_dim> Vecr<N_dim> ibm::IBMBase< N_dim >::dr
elements
template<int N_dim> dmdyn::SmartPList<IBElement<N_dim> > ibm::IBMBase< N_dim >::elements
elmid
template<int N_dim> std::unordered_map<int, int> ibm::IBMBase< N_dim >::elmid
geo
template<int N_dim> struct ibm::IBMBase::Geom ibm::IBMBase< N_dim >::geo
ibpoints
template<int N_dim> dmdyn::SmartPList<IBPoint<N_dim> > ibm::IBMBase< N_dim >::ibpoints
ibvelb
template<int N_dim> struct ibm::IBMBase::IBVelBoundary ibm::IBMBase< N_dim >::ibvelb
id
template<int N_dim> int ibm::IBMBase< N_dim >::id
local
template<int N_dim> Force<N_dim> ibm::IBMBase< N_dim >::local
mean_ds
template<int N_dim> Real ibm::IBMBase< N_dim >::mean_ds = -999.0
nodeid
template<int N_dim> std::unordered_map<int, int> ibm::IBMBase< N_dim >::nodeid
nodes
template<int N_dim> dmdyn::SmartPList<IBNode<N_dim> > ibm::IBMBase< N_dim >::nodes
option
template<int N_dim> struct ibm::IBMBase::Option ibm::IBMBase< N_dim >::option
pos_ref
template<int N_dim> blin::Vecr<N_dim> ibm::IBMBase< N_dim >::pos_ref = 0.0
total
template<int N_dim> Force<N_dim> ibm::IBMBase< N_dim >::total = {0.0, 0.0}
The documentation for this struct was generated from the following file:
/mnt/e/linuxOS/PhyStar/IBM/IBMClass/IBMBase.hpp