PhyStar: dmdyn::EllipsoidalShape< T_real > Class Template Reference
dmdyn::EllipsoidalShape< T_real > Class Template Reference
particle type class
#include <EllipsoidalShape.hpp>
Public Member Functions
EllipsoidalShape ()
~EllipsoidalShape ()
void Initialize (T_real kvisc, T_real densityRatio, T_real radius, const Vec3< T_real > &aspectRatio)
T_real DistanceFunction (const Vec3< T_real > &dpos)
T_real DistanceFunction (const Vec2< T_real > &dpos)
void UpdateLevelSet (const int dim, const T_real dx, const T_real pos[], const T_real ee[])
T_real LevelSetVolFrac (const Vec3< T_real > &pos)
T_real Radius2 ()
T_real Radius3 ()
virtual const Vec3< Real > & AspectRatio ()
T_real AspectRatio2 (int i)
T_real Volume ()
T_real ComputeMass ()
T_real Ixx ()
T_real Iyy ()
T_real Izz ()
T_real Ixx_Iyy ()
T_real Iyy_Izz ()
T_real Ixx_Izz ()
T_real Iyy_Ixx ()
T_real Izz_Iyy ()
T_real Izz_Ixx ()
void ComputeLam ()
void ComputeResistTransPF ()
void ComputeResistRotatePF ()
T_real ResponseTimeTrans ()
T_real ResponseTimeTransInv ()
virtual void ComputeIntParams ()
Protected Attributes
T_real kvisc = 1.
T_real density_ratio = 1.
T_real mass = 0.
T_real radius = 0.
Vec3< T_real > aspect_ratio = 1.
Vec3< T_real > uplam = 0.
Vec4< T_real > int_params
Vec3< T_real > resist_trans_pf
Vec3< T_real > resist_rotate_pf
EllipsoidLevelSet< T_real > levelset
Detailed Description
template<typename T_real = double>
class dmdyn::EllipsoidalShape< T_real >
particle type class
Template Parameters
T_real
Constructor & Destructor Documentation
EllipsoidalShape()
template<typename T_real = double> dmdyn::EllipsoidalShape< T_real >::EllipsoidalShape () inline
~EllipsoidalShape()
template<typename T_real = double> dmdyn::EllipsoidalShape< T_real >::~EllipsoidalShape () inline
Member Function Documentation
AspectRatio()
template<typename T_real = double> virtual const Vec3<Real>& dmdyn::EllipsoidalShape< T_real >::AspectRatio () inline virtual
AspectRatio2()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::AspectRatio2 (int i) inline
ComputeIntParams()
template<typename T_real = double> virtual void dmdyn::EllipsoidalShape< T_real >::ComputeIntParams () inline virtual
References dmdyn::ShapeIntegral< T_real >::ComputeIntParams().
ComputeLam()
template<typename T_real = double> void dmdyn::EllipsoidalShape< T_real >::ComputeLam () inline
ComputeMass()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::ComputeMass () inline
References mathconst::PI.
ComputeResistRotatePF()
template<typename T_real = double> void dmdyn::EllipsoidalShape< T_real >::ComputeResistRotatePF () inline
References mathconst::PI.
ComputeResistTransPF()
template<typename T_real = double> void dmdyn::EllipsoidalShape< T_real >::ComputeResistTransPF () inline
References mathconst::PI.
DistanceFunction() [1/2]
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::DistanceFunction (const Vec2< T_real > & dpos) inline
References dmdyn::radius.
DistanceFunction() [2/2]
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::DistanceFunction (const Vec3< T_real > & dpos) inline
References dmdyn::radius.
Initialize()
template<typename T_real = double> void dmdyn::EllipsoidalShape< T_real >::Initialize (T_real kvisc, T_real densityRatio, T_real radius, const Vec3< T_real > & aspectRatio) inline
References dmdyn::radius.
Ixx()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Ixx () inline
Ixx_Iyy()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Ixx_Iyy () inline
Ixx_Izz()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Ixx_Izz () inline
Iyy()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Iyy () inline
Iyy_Ixx()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Iyy_Ixx () inline
Iyy_Izz()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Iyy_Izz () inline
Izz()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Izz () inline
Izz_Ixx()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Izz_Ixx () inline
Izz_Iyy()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Izz_Iyy () inline
LevelSetVolFrac()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::LevelSetVolFrac (const Vec3< T_real > & pos) inline
References dmdyn::EllipsoidLevelSet< T_real >::VolumeFraction().
Radius2()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Radius2 () inline
References dmdyn::radius.
Radius3()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Radius3 () inline
References dmdyn::radius.
ResponseTimeTrans()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::ResponseTimeTrans () inline
References dmdyn::radius.
ResponseTimeTransInv()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::ResponseTimeTransInv () inline
UpdateLevelSet()
template<typename T_real = double> void dmdyn::EllipsoidalShape< T_real >::UpdateLevelSet (const int dim, const T_real dx, const T_real pos[], const T_real ee[]) inline
References dmdyn::EllipsoidLevelSet< T_real >::Init(), dmdyn::radius, and dmdyn::EllipsoidLevelSet< T_real >::UpdateTransform().
Volume()
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::Volume () inline
Member Data Documentation
aspect_ratio
template<typename T_real = double> Vec3<T_real> dmdyn::EllipsoidalShape< T_real >::aspect_ratio = 1. protected
density_ratio
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::density_ratio = 1. protected
int_params
template<typename T_real = double> Vec4<T_real> dmdyn::EllipsoidalShape< T_real >::int_params protected
kvisc
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::kvisc = 1. protected
levelset
template<typename T_real = double> EllipsoidLevelSet<T_real> dmdyn::EllipsoidalShape< T_real >::levelset protected
mass
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::mass = 0. protected
radius
template<typename T_real = double> T_real dmdyn::EllipsoidalShape< T_real >::radius = 0. protected
resist_rotate_pf
template<typename T_real = double> Vec3<T_real> dmdyn::EllipsoidalShape< T_real >::resist_rotate_pf protected
resist_trans_pf
template<typename T_real = double> Vec3<T_real> dmdyn::EllipsoidalShape< T_real >::resist_trans_pf protected
uplam
template<typename T_real = double> Vec3<T_real> dmdyn::EllipsoidalShape< T_real >::uplam = 0. protected
The documentation for this class was generated from the following file:
/mnt/e/linuxOS/PhyStar/DMDyn/DMClass/EllipsoidalShape.hpp