PhyStar: /mnt/e/linuxOS/PhyStar/Apps/cartboxffd/channel.cpp File Reference
channel.cpp File Reference
#include <iostream>
#include "FluidSol/FLUIDSOL.H"
#include "PPSol/PPSOL.H"
Functions
int main ()
Function Documentation
main()
int main ()
References solver::CartDataSpace< N_dim, SpaceID >::ConfigDataSpaceDict(), solver::Solver::ConfigGlobalDict(), solver::Solver::Dt(), solver::Solver::GlobalDict(), solver::fluidsol::FluidSolBase::Init(), solver::CartDataSpace< N_dim, SpaceID >::mpicomm, solver::Solver::PrintConfigGlobalDict(), gsmpi::root, solver::fluidsol::FluidSolBase::Solve(), and solver::fluidsol::FluidSolBase::WriteFields().