PhyStar: tfft3d Namespace Reference
tfft3d Namespace Reference
Classes
class FFT3D
struct PencilBase
class Cart3DPencilDecomp
Enumerations
enum class GhostFlag { Before = 0 , After = 1 }
enum class FFTDataType { CC = 0 , RR , RC }
enum FFTTYPE {
kNULL = -9 , kDFTc2c = 0 , kDFTc2r , kDFTr2c ,
kDFTHC , kDCT1 , kDCT2 , kDCT3 ,
kDCT4 , kDST1 , kDST2 , kDST3 ,
kDST4
}
enum FFTDimension { FirstDim = 0 , SecondDim , ThirdDim }
enum MemoryAlignType { kLeft = 0 , kJustified }
enum DCTTYPE { DCT1 = 0 , DCT2 , DCT3 , DCT4 }
enum DSTTYPE { DST1 = 0 , DST2 , DST3 , DST4 }
enum DecompLabel { kP = 0 , kR = 1 , kC = 2 }
enum AxisLabel { kX = 0 , kY , kZ }
enum GhostIgnoreFlag { kNone = 0 , kBefore , kAfter , kAll }
Functions
void MemoryCopy (auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, const int align_type=kLeft)
copy the memory of one array to a new array with a different size for three dimensional case
template<typename T_real = double>
void MemoryCopy (T_real *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, const int align_type=kLeft)
template<typename T_real = double>
void MemoryCopy (std::complex< T_real > *in, int m0, int m1, int m2, T_real *out, int n0, int n1, int n2, const int align_type=kLeft)
template<int Rank, typename T_real = double>
static void PencilDFTForwardc2c (std::complex< T_real > *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
Forward DFT for a 3D-pencil array (c2c)
template<int Rank, typename T_real = double>
static void PencilDFTBackwardc2c (std::complex< T_real > *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
Backward DFT for a 3D-pencil array (c2c)
template<int Rank, typename T_real = double>
static void PencilDFTc2c (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2, const int fftw_dir)
DFT for a 3D-pencil array (c2c) (the sizes of input and output arrays are the same)
template<int Rank, typename T_real = double>
static void PencilDFTr2c (T_real *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
DFT for a 3D-pencil array (r2c)
template<int Rank, typename T_real = double>
static void PencilDFTc2r (std::complex< T_real > *in, int m0, int m1, int m2, T_real *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTr2c (T_real *in, std::complex< T_real > *out, int n0, int n1, int n2)
DFT for a 3D-pencil array (r2c) (the logical sizes of input and output arrays are the same)
template<int Rank, typename T_real = double>
static void PencilDFTc2r (std::complex< T_real > *in, T_real *out, int n0, int n1, int n2)
DFT for a 3D-pencil array (c2r) (the logical sizes of input and output arrays are the same)
template<int Rank, typename T_real = double>
static void PencilDFTForwardr2r (T_real *in, int m0, int m1, int m2, T_real *out, int n0, int n1, int n2, const fftw_r2r_kind kind, T_real *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTForwardr2r (std::complex< T_real > *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, const fftw_r2r_kind kind, std::complex< T_real > *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackwardr2r (T_real *in, int m0, int m1, int m2, T_real *out, int n0, int n1, int n2, const fftw_r2r_kind kind, T_real *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackwardr2r (std::complex< T_real > *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, const fftw_r2r_kind kind, std::complex< T_real > *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTr2r (T_real *in, T_real *out, int n0, int n1, int n2, const fftw_r2r_kind kind)
template<int Rank, typename T_real = double>
static void PencilDFTr2r (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2, const fftw_r2r_kind kind)
template<int Rank, typename T_real = double>
static void PencilDFTForwardc2c (auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTr2c (auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTc2r (auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTc2c (auto *in, auto *out, int n0, int n1, int n2, int fftw_flag)
template<int Rank, typename T_real = double>
static void PencilDFTr2c (auto *in, auto *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFTc2r (auto *in, auto *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFTr2r (auto *in, auto *out, int n0, int n1, int n2, const fftw_r2r_kind kind)
template<int Rank, typename T_real = double>
static void PencilDFTForwardr2r (auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, const fftw_r2r_kind kind, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackwardc2c (auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackwardr2r (auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, const fftw_r2r_kind kind, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTForward (std::complex< T_real > *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTForward (T_real *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTForward (T_real *in, int m0, int m1, int m2, T_real *out, int n0, int n1, int n2, const fftw_r2r_kind *kind, T_real *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackward (std::complex< T_real > *in, int m0, int m1, int m2, std::complex< T_real > *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackward (std::complex< T_real > *in, int m0, int m1, int m2, T_real *out, int n0, int n1, int n2, std::complex< T_real > *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackward (T_real *in, int m0, int m1, int m2, T_real *out, int n0, int n1, int n2, const fftw_r2r_kind *kind, T_real *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTForward (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFTForward (T_real *in, std::complex< T_real > *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFTBackward (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFTBackward (std::complex< T_real > *in, T_real *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFT (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2, const int fftw_dir)
template<int Rank, typename T_real = double>
static void PencilDFT (std::complex< T_real > *in, T_real *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFT (T_real *in, std::complex< T_real > *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFT (T_real *in, T_real *out, int n0, int n1, int n2, const fftw_r2r_kind *kind)
template<int Rank, typename T_real = double>
static void PencilDFTHC (T_real *in, T_real *out, int n0, int n1, int n2, const int fftw_dir)
template<int Rank, typename T_real = double>
static void PencilDFTHC (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2, const int fftw_dir)
template<int Rank, typename T_real = double>
static void PencilDCT (T_real *in, T_real *out, int n0, int n1, int n2, const int fftw_dir, const int dcttype=DCT1)
template<int Rank, typename T_real = double>
static void PencilDCT (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2, const int fftw_dir, const int dcttype=DCT1)
template<int Rank, typename T_real = double>
static void PencilDST (T_real *in, T_real *out, int n0, int n1, int n2, const int fftw_dir, const int dsttype=DST1)
template<int Rank, typename T_real = double>
static void PencilDST (std::complex< T_real > *in, std::complex< T_real > *out, int n0, int n1, int n2, const int fftw_dir, const int dsttype=DST1)
template<int Rank>
void ZeroNyquistWave (auto *in, int n0, int n1, int n2, const int align_type)
template<int Rank, typename T_real = double>
static void PencilDFTForward (const int fft_type, auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTBackward (const int fft_type, auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<int Rank, typename T_real = double>
static void PencilDFTForward (const int fft_type, auto *in, auto *out, int n0, int n1, int n2)
template<int Rank, typename T_real = double>
static void PencilDFTBackward (const int fft_type, auto *in, auto *out, int n0, int n1, int n2)
template<typename T_real = double>
static void PencilDFTForward (const int fftdim, const int fft_type, auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<typename T_real = double>
static void PencilDFTBackward (const int fftdim, const int fft_type, auto *in, int m0, int m1, int m2, auto *out, int n0, int n1, int n2, auto *temp=nullptr)
template<typename T_real = double>
static void PencilDFTForward (const int fftdim, const int fft_type, auto *in, auto *out, int n0, int n1, int n2)
template<typename T_real = double>
static void PencilDFTBackward (const int fftdim, const int fft_type, auto *in, auto *out, int n0, int n1, int n2)
Enumeration Type Documentation
AxisLabel
enum tfft3d::AxisLabel
Enumerator
kX
kY
kZ
DCTTYPE
enum tfft3d::DCTTYPE
Enumerator
DCT1
DCT2
DCT3
DCT4
DecompLabel
enum tfft3d::DecompLabel
Enumerator
kP
kR
kC
DSTTYPE
enum tfft3d::DSTTYPE
Enumerator
DST1
DST2
DST3
DST4
FFTDataType
enum tfft3d::FFTDataType strong
Enumerator
CC
RR
RC
FFTDimension
enum tfft3d::FFTDimension
Enumerator
FirstDim
SecondDim
ThirdDim
FFTTYPE
enum tfft3d::FFTTYPE
Enumerator
kNULL
kDFTc2c
kDFTc2r
kDFTr2c
kDFTHC
kDCT1
kDCT2
kDCT3
kDCT4
kDST1
kDST2
kDST3
kDST4
GhostFlag
enum tfft3d::GhostFlag strong
Enumerator
Before
After
GhostIgnoreFlag
enum tfft3d::GhostIgnoreFlag
Enumerator
kNone
kBefore
kAfter
kAll
MemoryAlignType
enum tfft3d::MemoryAlignType
Enumerator
kLeft
kJustified
Function Documentation
MemoryCopy() [1/3]
void tfft3d::MemoryCopy (auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, const int align_type = kLeft)
copy the memory of one array to a new array with a different size for three dimensional case
Parameters
in input memory of array
m0 size of the input array
m1 size of the input array
m2 size of the input array
out output memory of array
n0 size of the output array
n1 size of the input array
n2 size of the input array
References kJustified, and kLeft.
MemoryCopy() [2/3]
template<typename T_real = double> void tfft3d::MemoryCopy (std::complex< T_real > * in, int m0, int m1, int m2, T_real * out, int n0, int n1, int n2, const int align_type = kLeft)
MemoryCopy() [3/3]
template<typename T_real = double> void tfft3d::MemoryCopy (T_real * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, const int align_type = kLeft)
PencilDCT() [1/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDCT (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2, const int fftw_dir, const int dcttype = DCT1) static
References DCT1, DCT2, DCT3, and DCT4.
PencilDCT() [2/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDCT (T_real * in, T_real * out, int n0, int n1, int n2, const int fftw_dir, const int dcttype = DCT1) static
References DCT1, DCT2, DCT3, and DCT4.
PencilDFT() [1/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFT (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2, const int fftw_dir) inline static
PencilDFT() [2/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFT (std::complex< T_real > * in, T_real * out, int n0, int n1, int n2) inline static
PencilDFT() [3/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFT (T_real * in, std::complex< T_real > * out, int n0, int n1, int n2) inline static
PencilDFT() [4/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFT (T_real * in, T_real * out, int n0, int n1, int n2, const fftw_r2r_kind * kind) inline static
PencilDFTBackward() [1/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackward (const int fft_type, auto * in, auto * out, int n0, int n1, int n2) inline static
References kDCT1, kDCT2, kDCT3, kDCT4, kDFTc2c, kDFTc2r, kDFTHC, kDFTr2c, kDST1, kDST2, kDST3, kDST4, kNULL, and MemoryCopy().
PencilDFTBackward() [2/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackward (const int fft_type, auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
References kDCT1, kDCT2, kDCT3, kDCT4, kDFTc2c, kDFTc2r, kDFTHC, kDFTr2c, kDST1, kDST2, kDST3, kDST4, kNULL, and MemoryCopy().
PencilDFTBackward() [3/9]
template<typename T_real = double> static void tfft3d::PencilDFTBackward (const int fftdim, const int fft_type, auto * in, auto * out, int n0, int n1, int n2) inline static
References FirstDim, SecondDim, and ThirdDim.
PencilDFTBackward() [4/9]
template<typename T_real = double> static void tfft3d::PencilDFTBackward (const int fftdim, const int fft_type, auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
References FirstDim, SecondDim, and ThirdDim.
PencilDFTBackward() [5/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackward (std::complex< T_real > * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) inline static
PencilDFTBackward() [6/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackward (std::complex< T_real > * in, int m0, int m1, int m2, T_real * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) inline static
PencilDFTBackward() [7/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackward (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2) inline static
PencilDFTBackward() [8/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackward (std::complex< T_real > * in, T_real * out, int n0, int n1, int n2) inline static
PencilDFTBackward() [9/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackward (T_real * in, int m0, int m1, int m2, T_real * out, int n0, int n1, int n2, const fftw_r2r_kind * kind, T_real * temp = nullptr) inline static
PencilDFTBackwardc2c() [1/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackwardc2c (auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
PencilDFTBackwardc2c() [2/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackwardc2c (std::complex< T_real > * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) static
Backward DFT for a 3D-pencil array (c2c)
Template Parameters
Rank which dimension for DFT
T_real
Parameters
in input memory of array
m0 size of the input array
m1 size of the input array
m2 size of the input array
out output memory of array
n0 size of the output array
n1 size of the output array
n2 size of the output array
fftw_dir direction of fft: FFTW_FORWARD(-1) and FFTW_BACKWARD(1)
temp temporary memory for fft transformation, default: nullptr, which means this memory will be allocated in function and be deallocated in the end; when the pointer 'temp' specifies a certain memory space, the space will not be reallocated inside this function, and this memory should be manually deallocated outsie the function
References kJustified, and MemoryCopy().
PencilDFTBackwardr2r() [1/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackwardr2r (auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, const fftw_r2r_kind kind, auto * temp = nullptr) inline static
PencilDFTBackwardr2r() [2/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackwardr2r (std::complex< T_real > * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, const fftw_r2r_kind kind, std::complex< T_real > * temp = nullptr) static
References kJustified, kLeft, and MemoryCopy().
PencilDFTBackwardr2r() [3/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTBackwardr2r (T_real * in, int m0, int m1, int m2, T_real * out, int n0, int n1, int n2, const fftw_r2r_kind kind, T_real * temp = nullptr) static
References kJustified, kLeft, and MemoryCopy().
PencilDFTc2c() [1/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTc2c (auto * in, auto * out, int n0, int n1, int n2, int fftw_flag) inline static
PencilDFTc2c() [2/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTc2c (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2, const int fftw_dir) static
DFT for a 3D-pencil array (c2c) (the sizes of input and output arrays are the same)
Template Parameters
Rank which dimension for DFT
T_real
Parameters
in input memory of array
out output memory of array
n0 size of the output array
n1 size of the output array
n2 size of the output array
fftw_dir direction of fft: FFTW_FORWARD(-1) and FFTW_BACKWARD(1)
PencilDFTc2r() [1/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTc2r (auto * in, auto * out, int n0, int n1, int n2) inline static
PencilDFTc2r() [2/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTc2r (auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
PencilDFTc2r() [3/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTc2r (std::complex< T_real > * in, int m0, int m1, int m2, T_real * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) static
References kLeft, and MemoryCopy().
PencilDFTc2r() [4/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTc2r (std::complex< T_real > * in, T_real * out, int n0, int n1, int n2) static
DFT for a 3D-pencil array (c2r) (the logical sizes of input and output arrays are the same)
Template Parameters
Rank which dimension for DFT
T_real
Parameters
in input memory of array
out output memory of array
n0 logical size of the array (output)
n1 logical size of the array (output)
n2 logical size of the array (output)
PencilDFTForward() [1/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForward (const int fft_type, auto * in, auto * out, int n0, int n1, int n2) inline static
References kDCT1, kDCT2, kDCT3, kDCT4, kDFTc2c, kDFTc2r, kDFTHC, kDFTr2c, kDST1, kDST2, kDST3, kDST4, kNULL, and MemoryCopy().
PencilDFTForward() [2/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForward (const int fft_type, auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
References kDCT1, kDCT2, kDCT3, kDCT4, kDFTc2c, kDFTc2r, kDFTHC, kDFTr2c, kDST1, kDST2, kDST3, kDST4, kNULL, and MemoryCopy().
PencilDFTForward() [3/9]
template<typename T_real = double> static void tfft3d::PencilDFTForward (const int fftdim, const int fft_type, auto * in, auto * out, int n0, int n1, int n2) inline static
References FirstDim, SecondDim, and ThirdDim.
PencilDFTForward() [4/9]
template<typename T_real = double> static void tfft3d::PencilDFTForward (const int fftdim, const int fft_type, auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
References FirstDim, SecondDim, and ThirdDim.
PencilDFTForward() [5/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForward (std::complex< T_real > * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) inline static
PencilDFTForward() [6/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForward (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2) inline static
PencilDFTForward() [7/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForward (T_real * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) inline static
PencilDFTForward() [8/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForward (T_real * in, int m0, int m1, int m2, T_real * out, int n0, int n1, int n2, const fftw_r2r_kind * kind, T_real * temp = nullptr) inline static
PencilDFTForward() [9/9]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForward (T_real * in, std::complex< T_real > * out, int n0, int n1, int n2) inline static
PencilDFTForwardc2c() [1/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForwardc2c (auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
PencilDFTForwardc2c() [2/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForwardc2c (std::complex< T_real > * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) static
Forward DFT for a 3D-pencil array (c2c)
Template Parameters
Rank which dimension for DFT
T_real
Parameters
in input memory of array
m0 size of the input array
m1 size of the input array
m2 size of the input array
out output memory of array
n0 size of the output array
n1 size of the output array
n2 size of the output array
fftw_dir direction of fft: FFTW_FORWARD(-1) and FFTW_BACKWARD(1)
temp temporary memory for fft transformation, default: nullptr, which means this memory will be allocated in function and be deallocated in the end; when the pointer 'temp' specifies a certain memory space, the space will not be reallocated inside this function, and this memory should be manually deallocated outsie the function
References kJustified, and MemoryCopy().
PencilDFTForwardr2r() [1/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForwardr2r (auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, const fftw_r2r_kind kind, auto * temp = nullptr) inline static
PencilDFTForwardr2r() [2/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForwardr2r (std::complex< T_real > * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, const fftw_r2r_kind kind, std::complex< T_real > * temp = nullptr) static
References kJustified, kLeft, and MemoryCopy().
PencilDFTForwardr2r() [3/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTForwardr2r (T_real * in, int m0, int m1, int m2, T_real * out, int n0, int n1, int n2, const fftw_r2r_kind kind, T_real * temp = nullptr) static
References kJustified, kLeft, and MemoryCopy().
PencilDFTHC() [1/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTHC (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2, const int fftw_dir) inline static
PencilDFTHC() [2/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTHC (T_real * in, T_real * out, int n0, int n1, int n2, const int fftw_dir) inline static
PencilDFTr2c() [1/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTr2c (auto * in, auto * out, int n0, int n1, int n2) inline static
PencilDFTr2c() [2/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTr2c (auto * in, int m0, int m1, int m2, auto * out, int n0, int n1, int n2, auto * temp = nullptr) inline static
PencilDFTr2c() [3/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTr2c (T_real * in, int m0, int m1, int m2, std::complex< T_real > * out, int n0, int n1, int n2, std::complex< T_real > * temp = nullptr) static
DFT for a 3D-pencil array (r2c)
Template Parameters
Rank which dimension for DFT
T_real
Parameters
in input memory of array
m0 size of the input array
m1 size of the input array
m2 size of the input array
out output memory of array
n0 size of the output array
n1 size of the output array
n2 size of the output array
fftw_dir direction of fft: FFTW_FORWARD(-1) and FFTW_BACKWARD(1)
temp temporary memory for fft transformation, default: nullptr, which means this memory will be allocated in function and be deallocated in the end; when the pointer 'temp' specifies a certain memory space, the space will not be reallocated inside this function, and this memory should be manually deallocated outsie the function
References kLeft, and MemoryCopy().
PencilDFTr2c() [4/4]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTr2c (T_real * in, std::complex< T_real > * out, int n0, int n1, int n2) static
DFT for a 3D-pencil array (r2c) (the logical sizes of input and output arrays are the same)
Template Parameters
Rank which dimension for DFT
T_real
Parameters
in input memory of array
out output memory of array
n0 logical size of the array (input)
n1 logical size of the array (input)
n2 logical size of the array (input)
PencilDFTr2r() [1/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTr2r (auto * in, auto * out, int n0, int n1, int n2, const fftw_r2r_kind kind) inline static
PencilDFTr2r() [2/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTr2r (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2, const fftw_r2r_kind kind) static
PencilDFTr2r() [3/3]
template<int Rank, typename T_real = double> static void tfft3d::PencilDFTr2r (T_real * in, T_real * out, int n0, int n1, int n2, const fftw_r2r_kind kind) static
PencilDST() [1/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDST (std::complex< T_real > * in, std::complex< T_real > * out, int n0, int n1, int n2, const int fftw_dir, const int dsttype = DST1) static
References DST1, DST2, DST3, and DST4.
PencilDST() [2/2]
template<int Rank, typename T_real = double> static void tfft3d::PencilDST (T_real * in, T_real * out, int n0, int n1, int n2, const int fftw_dir, const int dsttype = DST1) static
References DST1, DST2, DST3, and DST4.
ZeroNyquistWave()
template<int Rank> void tfft3d::ZeroNyquistWave (auto * in, int n0, int n1, int n2, const int align_type)
References FirstDim, kJustified, SecondDim, and ThirdDim.