PhyStar: solver::fluidsol::CartBoxFDMSol< 3, SpaceID > Class Template Reference
solver::fluidsol::CartBoxFDMSol< 3, SpaceID > Class Template Reference
#include <CartBoxFDMSol.hpp>
Public Types
using Field = blockelm::CartField< Real, 3 >
using BTypeMap = std::unordered_map< std::string, std::vector< blockelm::BoundaryPairs > >
using BValMap = std::unordered_map< std::string, std::vector< std::vector< Real > >>
using BoundaryMap = std::unordered_map< std::string, std::vector< std::vector< blockelm::BoundaryData< Real > >> >
Public Member Functions
CartBoxFDMSol ()
virtual ~CartBoxFDMSol ()
virtual void Init ()
virtual void Solve (const int &step, const Real &time, std::vector< std::shared_ptr< ppsol::PPSolBase >> ppsol={})
virtual void SolveStageOne (const int &step, const Real &time, const Real &coef=1.0)
virtual void SolveStageTwo (const int &step, const Real &time, const Real &coef=1.0)
virtual void SolveStageThree (const int &step, const Real &time, const Real &coef=1.0)
virtual void SolveAB2 (const int &step, const Real &time, std::vector< std::shared_ptr< ppsol::PPSolBase >> &ppsol={})
virtual void SolveLSRK3 (const int &step, const Real &time, std::vector< std::shared_ptr< ppsol::PPSolBase >> &ppsol={})
virtual void Finish (const int &step, const Real &time)
virtual void WriteFields (const int &step, const Real &time)
virtual void WriteMidFields (const int &step, const Real &time)
virtual void LoadFields ()
virtual std::string GetSolverName ()
virtual std::string GetMeshName ()
void WriteFieldsTest (const int &step, const Real &time)
auto & CreateUniformMesh (std::vector< int > nsize, std::vector< std::vector< Real >> edges, std::vector< std::vector< int >> ghs={{0}, {0}, {0}})
auto & CreateUniformMesh (int nsize, std::vector< Real > edges, std::vector< int > ghs={0})
auto & CreateVelocityFields (std::vector< std::vector< int >> flgs)
auto & CreatePressureField (std::vector< int > flgs)
auto & CreateGradField (std::vector< int > flgs)
auto & CreateScalarFields (std::vector< int > flgs, const int n)
auto MappingMeshToStretching ()
mapping new mesh of the third direction to stretching mesh
void InitBoundary ()
void InitTempFields ()
void InitFFTP (const blockelm::MeshType methtype)
void InitFFT (const blockelm::MeshType methtype, auto &fft, auto &field, std::string bcname)
void NonLinearTerm (Field &ut, Field &vt, Field &wt, const Real &coef=1.0, const Real &beta=1.0)
void ViscousTerm (Field &ut, Field &vt, Field &wt, const Real &coef=1.0, const Real &beta=1.0)
void PressureTerm (Field &ut, Field &vt, Field &wt, const Real &coef=1.0, const Real &beta=1.0)
void ViscousPoisson (const Real &coef)
void AB2 ()
void PressurePoisson (const Real &coef=1.0)
void Correct (const Real &coef=1.0)
void CalVelocityGradient ()
void UpdateDtIfNecessary (const Real &chdt)
void AddIBMIfNecessary (const Real &coef=1.0)
void AddCouplingForceIfNecessary (const Real &coef=1.0)
void InitUniformFlow (const Real &time)
void InitLinearShear (const Real &time)
void BoundaryOfVelocity ()
void BoundaryOfVelocityNew ()
void BoundaryOfVelocityStar ()
void BoundaryOfPressure ()
void BoundaryOfDeltaPressure ()
auto CalMaxDiv ()
auto CalMaxCFLDt ()
virtual void Statistic (const int &istep, const Real &time)
virtual void StatLog (const int &istep, const Real &time)
virtual void InitStatLogFile ()
void ConfigFlowDict ()
void CheckConfigFlowDict ()
virtual void GenerateInitFlow (const boxfdm::FlowType &ftype, const Real &time)
void InitFilePath ()
Public Member Functions inherited from solver::fluidsol::FDMSolver
FDMSolver ()
virtual ~FDMSolver ()
Public Member Functions inherited from solver::Solver
Solver ()
virtual ~Solver ()
void PrintAbstract ()
void Relase (const SolverNameList &flag)
void ConfigGlobalDict (const std::string filename)
void PrintConfigGlobalDict ()
Public Member Functions inherited from solver::CartDataSpace< 3, SpaceID >
CartDataSpace ()
~CartDataSpace ()
void ConfigDataSpaceDict ()
config information of mpi from ControlDict.in
void CheckConfigDataSpaceDict ()
Public Attributes
blockelm::CartBlock< 3 > & block = CartDataSpace<3, SpaceID>::cartblock
blockelm::CartMesh< 3 > & gb_mesh = CartDataSpace<3, SpaceID>::gb_cartmesh
std::vector< std::vector< Real > > & domain_size = CartDataSpace<3, SpaceID>::domain_size
std::vector< std::vector< Real > > & gb_domain_size = CartDataSpace<3, SpaceID>::gb_domain_size
std::vector< int > & mesh_size = CartDataSpace<3, SpaceID>::mesh_size
std::vector< int > & gb_mesh_size = CartDataSpace<3, SpaceID>::gb_mesh_size
std::vector< int > & start_index = CartDataSpace<3, SpaceID>::start_index
std::vector< std::vector< int > > & ghost_size = CartDataSpace<3, SpaceID>::ghost_size
std::vector< std::vector< int > > & stagger_flag = CartDataSpace<3, SpaceID>::stagger_flag
const std::vector< int > & center_flag = CartDataSpace<3, SpaceID>::center_flag
gsmpi::GSMPICart< 3 > & mpicomm = CartDataSpace<3, SpaceID>::mpicomm
std::vector< ibm::IBMCart< 3 > > & cartibm = CartDataSpace<3, SpaceID>::cartibm
int & ibm_flag = CartDataSpace<3, SpaceID>::ibm_flag
std::vector< blockelm::CartField< Real, 3 > * > & tempfields = CartDataSpace<3, SpaceID>::tempfields
gsmpi::CartFieldGhostComm< Real, 3 > ghostcomm
blin::Vec< fdm::FDMSecondCenteralDiff< fdm::FDMTAG_Type::Stretch >, 3 > fdm
boxfdm::FFTPoisson< 3, SpaceID > fftp
boxfdm::FFTPoisson< 3, SpaceID+2351 > fftu
boxfdm::FFTPoisson< 3, SpaceID+2352 > fftv
boxfdm::FFTPoisson< 3, SpaceID+2353 > fftw
std::unordered_map< std::string, std::vector< std::vector< blockelm::CartBoundary< Real, 3 > > > > boundary
Field us
Field vs
Field ws
Field ps
Field utnew
Field vtnew
Field wtnew
Field utold
Field vtold
Field wtold
Field fx
Field fy
Field fz
Field uf
Field vf
Field wf
blin::Vec< Field, 5 > wrk
blin::Vec3i stf
blin::Vec3i edf
blin::Vec3i stp
blin::Vec3i edp
int stf2w
int edf2w
int stp2w
int edp2w
bool flow_start_flag = true
struct solver::fluidsol::CartBoxFDMSol< 3, SpaceID >:: { ... } flowdict
boxfdm::FlowType flow_type
Real dt
Real kvisc
Real density
Real Re
Real Retau
std::string work_path
Real cfl
int conti
boxfdm::TimeScheme time_scheme
boxfdm::TimeScheme visc_time_scheme
BTypeMap btype
BValMap bval
BoundaryMap bound
Public Attributes inherited from solver::CartDataSpace< 3, SpaceID >
std::vector< Real > domain_size
std::vector< int > mesh_size
std::vector< int > ghost_size
std::vector< int > stagger_flag
Private Attributes
const std::string _name = "CartBoxFDMSol"
Additional Inherited Members
Static Public Member Functions inherited from solver::Solver
static const auto & GlobalDict ()
static const auto & Dt ()
Static Public Member Functions inherited from solver::CartDataSpace< 3, SpaceID >
static std::vector< int > CalTotalShape (const std::vector< int > &flag)
Static Public Attributes inherited from solver::CartDataSpace< 3, SpaceID >
static std::vector< std::vector< Real > > domain_size
static std::vector< std::vector< Real > > gb_domain_size
static std::vector< int > mesh_size
static std::vector< int > gb_mesh_size
static std::vector< int > start_index
static std::vector< std::vector< int > > ghost_size
static std::vector< std::vector< int > > stagger_flag
static const std::vector< int > center_flag
static blockelm::CartMesh< N_dim > gb_cartmesh
static blockelm::CartBlock< N_dim > cartblock
static gsmpi::GSMPICart< N_dim > mpicomm
static std::vector< ibm::IBMCart< N_dim > > cartibm
static int ibm_flag
static std::vector< blockelm::CartField< Real, N_dim > * > tempfields
static tml::tmlnode dataspacetml
struct {
std::vector< Real > domain_size
std::vector< int > mesh_size
std::vector< int > ghost_size
std::vector< int > stagger_flag
} dataspacedict
Protected Member Functions inherited from solver::fluidsol::FluidSolBase
FluidSolBase ()
virtual ~FluidSolBase ()
Protected Attributes inherited from solver::fluidsol::FluidSolBase
tml::tmlnode fluidsoltml
tml::tmlnode fparams
Static Protected Attributes inherited from solver::fluidsol::FluidSolBase
static Real & dtf = dt
Static Protected Attributes inherited from solver::Solver
static std::string header = "PhyStar"
static std::string version = "v0.0.1"
static int count
static Solver * ptr_fluidsol = nullptr
static Solver * ptr_point_particlesol = nullptr
static Solver * ptr_resolved_particlesol = nullptr
static Real dt
static Real kvisc
static Real density
static tml::tmlnode globaltml
struct {
std::string casename
Real time_start
Real time_end
Real time_ndump
int ndim
int step_start
int nstep
int step_end
int step_ndump
int step_nscreen
int step_nstat
int step_nrefresh
int ppsol_flag
int ppsol_same_dict
unsigned int random_seed
} globaldict
Member Typedef Documentation
BoundaryMap
template<int SpaceID> using solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BoundaryMap = std::unordered_map<std::string, std::vector<std::vector<blockelm::BoundaryData<Real> >> >
BTypeMap
template<int SpaceID> using solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BTypeMap = std::unordered_map<std::string, std::vector<blockelm::BoundaryPairs> >
BValMap
template<int SpaceID> using solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BValMap = std::unordered_map<std::string, std::vector<std::vector<Real> >>
Field
template<int SpaceID> using solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Field = blockelm::CartField<Real, 3>
Constructor & Destructor Documentation
CartBoxFDMSol()
template<int SpaceID> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CartBoxFDMSol
References solver::Solver::ptr_fluidsol.
~CartBoxFDMSol()
template<int SpaceID> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::~CartBoxFDMSol virtual
References fileio::FluidCartRegularD< N_dim, FT >::DeallocateBuffer(), and solver::Solver::ptr_fluidsol.
Member Function Documentation
AB2()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::AB2
References solver::Solver::dt.
AddCouplingForceIfNecessary()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::AddCouplingForceIfNecessary (const Real & coef = 1.0)
References solver::CartDataSpace< N_dim, 999 >::ghost_size, and gsmpi::GSMPI_REAL.
AddIBMIfNecessary()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::AddIBMIfNecessary (const Real & coef = 1.0)
References solver::CartDataSpace< N_dim, 999 >::cartibm, ibm::DirectForce, solver::Solver::dt, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, solver::CartDataSpace< N_dim, 999 >::ibm_flag, and ibm::PenaltyFun.
BoundaryOfDeltaPressure()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BoundaryOfDeltaPressure
References solver::CartDataSpace< N_dim, 999 >::mpicomm, blockelm::None, and blockelm::SplitBoundaryPairs().
BoundaryOfPressure()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BoundaryOfPressure
References solver::CartDataSpace< N_dim, 999 >::mpicomm, blockelm::None, and blockelm::SplitBoundaryPairs().
BoundaryOfVelocity()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BoundaryOfVelocity
References solver::CartDataSpace< N_dim, 999 >::mpicomm, blockelm::None, and blockelm::SplitBoundaryPairs().
BoundaryOfVelocityNew()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BoundaryOfVelocityNew
References solver::CartDataSpace< N_dim, 999 >::mpicomm.
BoundaryOfVelocityStar()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::BoundaryOfVelocityStar
References solver::CartDataSpace< N_dim, 999 >::mpicomm, blockelm::None, and blockelm::SplitBoundaryPairs().
CalMaxCFLDt()
template<int SpaceID> auto solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CalMaxCFLDt
References solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::kvisc, quadpack::max(), and solver::CartDataSpace< N_dim, 999 >::mpicomm.
CalMaxDiv()
template<int SpaceID> auto solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CalMaxDiv
References solver::CartDataSpace< N_dim, 999 >::ghost_size, quadpack::max(), solver::CartDataSpace< N_dim, 999 >::mesh_size, and solver::CartDataSpace< N_dim, 999 >::mpicomm.
CalVelocityGradient()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CalVelocityGradient
References solver::CartDataSpace< N_dim, 999 >::ghost_size, and gsmpi::GSMPI_REAL.
CheckConfigFlowDict()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CheckConfigFlowDict () inline
References solver::Solver::density, solver::Solver::dt, solver::Solver::globaldict, and solver::Solver::kvisc.
ConfigFlowDict()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ConfigFlowDict () inline
References blockelm::BoundaryData< T >::bfun, blockelm::BoundaryData< T >::btype, solver::database::controldict, blockelm::DiffBoundaryPairs(), solver::fluidsol::FluidSolBase::fluidsoltml, solver::fluidsol::FluidSolBase::fparams, blockelm::BoundaryData< T >::params, blockelm::SplitBoundaryPairs(), blockelm::BoundaryData< T >::val, blockelm::vConfigBFunType(), blockelm::vConfigBoundaryPairs(), solver::fluidsol::boxfdm::vConfigFlowType(), and solver::fluidsol::boxfdm::vConfigTimeScheme().
Correct()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Correct (const Real & coef = 1.0)
References solver::Solver::dt, solver::CartDataSpace< N_dim, 999 >::ghost_size, and gsmpi::GSMPI_REAL.
CreateGradField()
template<int SpaceID> auto& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CreateGradField (std::vector< int > flgs) inline
References blockelm::CartBlock< N_dim >::CreateGradField().
CreatePressureField()
template<int SpaceID> auto& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CreatePressureField (std::vector< int > flgs) inline
References blockelm::CartBlock< N_dim >::CreatePressureField().
CreateScalarFields()
template<int SpaceID> auto& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CreateScalarFields (std::vector< int > flgs, const int n) inline
References blockelm::CartBlock< N_dim >::CreateScalarFields().
CreateUniformMesh() [1/2]
template<int SpaceID> auto& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CreateUniformMesh (int nsize, std::vector< Real > edges, std::vector< int > ghs = {0}) inline
CreateUniformMesh() [2/2]
template<int SpaceID> auto& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CreateUniformMesh (std::vector< int > nsize, std::vector< std::vector< Real >> edges, std::vector< std::vector< int >> ghs = {{0}, {0}, {0}}) inline
CreateVelocityFields()
template<int SpaceID> auto& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::CreateVelocityFields (std::vector< std::vector< int >> flgs) inline
References blockelm::CartBlock< N_dim >::CreateVelocityFields().
Finish()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Finish (const int & step, const Real & time) virtual
Implements solver::fluidsol::FluidSolBase.
GenerateInitFlow()
template<int SpaceID> virtual void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::GenerateInitFlow (const boxfdm::FlowType & ftype, const Real & time) inline virtual
References solver::fluidsol::boxfdm::LinearShear, solver::fluidsol::boxfdm::Static, and solver::fluidsol::boxfdm::Uniform.
GetMeshName()
template<int SpaceID> std::string solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::GetMeshName virtual
Reimplemented from solver::Solver.
GetSolverName()
template<int SpaceID> std::string solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::GetSolverName virtual
Reimplemented from solver::Solver.
References solver::fluidsol::FluidSolBase::_name.
Init()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Init virtual
Implements solver::fluidsol::FluidSolBase.
References fileio::FluidCartRegularD< N_dim, FT >::AllocateBuffer(), solver::CartDataSpace< N_dim, 999 >::cartibm, solver::CartDataSpace< N_dim, 999 >::center_flag, solver::CartDataSpace< N_dim, 999 >::domain_size, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, solver::CartDataSpace< N_dim, 999 >::ibm_flag, solver::CartDataSpace< N_dim, 999 >::mesh_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, and solver::CartDataSpace< N_dim, 999 >::stagger_flag.
InitBoundary()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitBoundary
References blockelm::CartBoundary< T, N_dim >::CreateBoundaryFromFieldExcludeData(), and solver::CartDataSpace< N_dim, 999 >::mpicomm.
InitFFT()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitFFT (const blockelm::MeshType methtype, auto & fft, auto & field, std::string bcname)
References solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, fdm::Stretch, and blockelm::uniform.
InitFFTP()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitFFTP (const blockelm::MeshType methtype)
References solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, fdm::Stretch, and blockelm::uniform.
InitFilePath()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitFilePath () inline
InitLinearShear()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitLinearShear (const Real & time)
References solver::fluidsol::FluidSolBase::fparams, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, and solver::CartDataSpace< N_dim, 999 >::mesh_size.
InitStatLogFile()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitStatLogFile virtual
References solver::CartDataSpace< N_dim, 999 >::cartibm, and solver::CartDataSpace< N_dim, 999 >::ibm_flag.
InitTempFields()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitTempFields
References solver::CartDataSpace< N_dim, 999 >::tempfields.
InitUniformFlow()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::InitUniformFlow (const Real & time)
References solver::fluidsol::FluidSolBase::fparams, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, and solver::CartDataSpace< N_dim, 999 >::mesh_size.
LoadFields()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::LoadFields virtual
References fileio::FluidCartRegularD< N_dim, FT >::CloseFile(), solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, solver::CartDataSpace< N_dim, 999 >::mpicomm, fileio::FluidCartRegularD< N_dim, FT >::OpenFile(), fileio::FluidCartRegularD< N_dim, FT >::ReadField(), gsmpi::root, fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr(), and fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh().
MappingMeshToStretching()
template<int SpaceID> auto solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::MappingMeshToStretching
mapping new mesh of the third direction to stretching mesh
Template Parameters
SpaceID
Returns
auto&
References blockelm::atan, solver::CartDataSpace< N_dim, 999 >::domain_size, solver::fluidsol::FluidSolBase::fluidsoltml, solver::CartDataSpace< N_dim, 999 >::gb_mesh_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::CartDataSpace< N_dim, 999 >::mpicomm, mathconst::PI_2, gsmpi::root, blockelm::sin, blockelm::tanh, and blockelm::vConfigMeshType().
NonLinearTerm()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::NonLinearTerm (Field & ut, Field & vt, Field & wt, const Real & coef = 1.0, const Real & beta = 1.0)
References blockelm::CartField< T, N_dim >::CopyExcludeData(), blockelm::CartField< T, N_dim >::data, solver::CartDataSpace< N_dim, 999 >::ghost_size, and gsmpi::GSMPI_REAL.
PressurePoisson()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::PressurePoisson (const Real & coef = 1.0)
References solver::fluidsol::boxfdm::CN, blockelm::CartField< T, N_dim >::data, solver::Solver::dt, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, and solver::Solver::kvisc.
PressureTerm()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::PressureTerm (Field & ut, Field & vt, Field & wt, const Real & coef = 1.0, const Real & beta = 1.0)
Solve()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Solve (const int & step, const Real & time, std::vector< std::shared_ptr< ppsol::PPSolBase >> ppsol = {}) virtual
Implements solver::fluidsol::FluidSolBase.
References solver::fluidsol::boxfdm::AB2, solver::Solver::globaldict, solver::fluidsol::boxfdm::LSRK3, and solver::Solver::ptr_point_particlesol.
SolveAB2()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::SolveAB2 (const int & step, const Real & time, std::vector< std::shared_ptr< ppsol::PPSolBase >> & ppsol = {}) virtual
References solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, solver::fluidsol::FluidSolBase::SolveStageOne(), and solver::fluidsol::FluidSolBase::SolveStageTwo().
SolveLSRK3()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::SolveLSRK3 (const int & step, const Real & time, std::vector< std::shared_ptr< ppsol::PPSolBase >> & ppsol = {}) virtual
References solver::Solver::dt, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, solver::fluidsol::FluidSolBase::SolveStageOne(), and solver::fluidsol::FluidSolBase::SolveStageTwo().
SolveStageOne()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::SolveStageOne (const int & step, const Real & time, const Real & coef = 1.0) virtual
Implements solver::fluidsol::FluidSolBase.
References solver::Solver::dt, and solver::fluidsol::boxfdm::None.
SolveStageThree()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::SolveStageThree (const int & step, const Real & time, const Real & coef = 1.0) virtual
References solver::fluidsol::boxfdm::CN.
SolveStageTwo()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::SolveStageTwo (const int & step, const Real & time, const Real & coef = 1.0) virtual
Implements solver::fluidsol::FluidSolBase.
References solver::fluidsol::boxfdm::CN, and solver::Solver::dt.
Statistic()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Statistic (const int & istep, const Real & time) virtual
References solver::CartDataSpace< N_dim, 999 >::ghost_size, and solver::Solver::globaldict.
StatLog()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::StatLog (const int & istep, const Real & time) virtual
References solver::CartDataSpace< N_dim, 999 >::cartibm, and solver::CartDataSpace< N_dim, 999 >::ibm_flag.
UpdateDtIfNecessary()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::UpdateDtIfNecessary (const Real & chdt)
References solver::Solver::dt, and quadpack::min().
ViscousPoisson()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ViscousPoisson (const Real & coef)
References solver::Solver::dt, solver::CartDataSpace< N_dim, 999 >::ghost_size, gsmpi::GSMPI_REAL, and solver::Solver::kvisc.
ViscousTerm()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ViscousTerm (Field & ut, Field & vt, Field & wt, const Real & coef = 1.0, const Real & beta = 1.0)
References solver::Solver::kvisc.
WriteFields()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::WriteFields (const int & step, const Real & time) virtual
Implements solver::fluidsol::FluidSolBase.
References fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo(), fileio::FluidCartRegularD< N_dim, FT >::AddField(), solver::CartDataSpace< N_dim, SpaceID >::CalTotalShape(), fileio::FluidCartRegularD< N_dim, FT >::CloseFile(), blockelm::CartField< T, N_dim >::CopyExcludeData(), fileio::FluidCartRegularD< N_dim, FT >::CreateFile(), solver::Solver::density, solver::fluidsol::FluidSolBase::dtf, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, blockelm::CartField< T, N_dim >::GetFlag(), blockelm::CartField< T, N_dim >::GetShape(), solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, fileio::kOtherInfo, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mpicomm, blockelm::CartField< T, N_dim >::PtrData(), gsmpi::root, fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr(), fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh(), and fileio::FluidCartRegularD< N_dim, FT >::SetMeshc().
WriteFieldsTest()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::WriteFieldsTest (const int & step, const Real & time)
References fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo(), fileio::FluidCartRegularD< N_dim, FT >::AddField(), fileio::FluidCartRegularD< N_dim, FT >::CloseFile(), fileio::FluidCartRegularD< N_dim, FT >::CreateFile(), solver::Solver::density, solver::fluidsol::FluidSolBase::dtf, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, fileio::kOtherInfo, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mpicomm, gsmpi::root, fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr(), fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh(), and fileio::FluidCartRegularD< N_dim, FT >::SetMeshc().
WriteMidFields()
template<int SpaceID> void solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::WriteMidFields (const int & step, const Real & time) virtual
References fileio::FluidCartRegularD< N_dim, FT >::AddAttributeTo(), fileio::FluidCartRegularD< N_dim, FT >::AddField(), fileio::FluidCartRegularD< N_dim, FT >::CloseFile(), fileio::FluidCartRegularD< N_dim, FT >::CreateFile(), solver::Solver::density, solver::fluidsol::FluidSolBase::dtf, solver::CartDataSpace< N_dim, 999 >::gb_domain_size, solver::CartDataSpace< N_dim, 999 >::ghost_size, solver::Solver::globaldict, fileio::kOtherInfo, solver::Solver::kvisc, solver::CartDataSpace< N_dim, 999 >::mpicomm, gsmpi::root, fileio::FluidCartRegularD< N_dim, FT >::SetFileAttr(), fileio::FluidCartRegularD< N_dim, FT >::SetGhostMesh(), and fileio::FluidCartRegularD< N_dim, FT >::SetMeshc().
Member Data Documentation
_name
template<int SpaceID> const std::string solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::_name = "CartBoxFDMSol" private
block
template<int SpaceID> blockelm::CartBlock<3>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::block = CartDataSpace<3, SpaceID>::cartblock
bound
template<int SpaceID> BoundaryMap solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::bound
boundary
template<int SpaceID> std::unordered_map<std::string, std::vector<std::vector<blockelm::CartBoundary<Real, 3> > > > solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::boundary
btype
template<int SpaceID> BTypeMap solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::btype
bval
template<int SpaceID> BValMap solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::bval
cartibm
template<int SpaceID> std::vector<ibm::IBMCart<3> >& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::cartibm = CartDataSpace<3, SpaceID>::cartibm
center_flag
template<int SpaceID> const std::vector<int>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::center_flag = CartDataSpace<3, SpaceID>::center_flag
cfl
template<int SpaceID> Real solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::cfl
conti
template<int SpaceID> int solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::conti
density
template<int SpaceID> Real solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::density
domain_size
template<int SpaceID> std::vector<std::vector<Real> >& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::domain_size = CartDataSpace<3, SpaceID>::domain_size
dt
template<int SpaceID> Real solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::dt
edf
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::edf
edf2w
template<int SpaceID> int solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::edf2w
edp
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::edp
edp2w
template<int SpaceID> int solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::edp2w
fdm
template<int SpaceID> blin::Vec<fdm::FDMSecondCenteralDiff<fdm::FDMTAG_Type::Stretch>, 3> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fdm
fftp
template<int SpaceID> boxfdm::FFTPoisson<3, SpaceID> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fftp
fftu
template<int SpaceID> boxfdm::FFTPoisson<3, SpaceID + 2351> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fftu
fftv
template<int SpaceID> boxfdm::FFTPoisson<3, SpaceID + 2352> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fftv
fftw
template<int SpaceID> boxfdm::FFTPoisson<3, SpaceID + 2353> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fftw
flow_start_flag
template<int SpaceID> bool solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::flow_start_flag = true
flow_type
template<int SpaceID> boxfdm::FlowType solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::flow_type
struct { ... } solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::flowdict
fx
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fx
fy
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fy
fz
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::fz
gb_domain_size
template<int SpaceID> std::vector<std::vector<Real> >& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::gb_domain_size = CartDataSpace<3, SpaceID>::gb_domain_size
gb_mesh
template<int SpaceID> blockelm::CartMesh<3>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::gb_mesh = CartDataSpace<3, SpaceID>::gb_cartmesh
gb_mesh_size
template<int SpaceID> std::vector<int>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::gb_mesh_size = CartDataSpace<3, SpaceID>::gb_mesh_size
ghost_size
template<int SpaceID> std::vector<std::vector<int> >& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ghost_size = CartDataSpace<3, SpaceID>::ghost_size
ghostcomm
template<int SpaceID> gsmpi::CartFieldGhostComm<Real, 3> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ghostcomm
ibm_flag
template<int SpaceID> int& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ibm_flag = CartDataSpace<3, SpaceID>::ibm_flag
kvisc
template<int SpaceID> Real solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::kvisc
mesh_size
template<int SpaceID> std::vector<int>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::mesh_size = CartDataSpace<3, SpaceID>::mesh_size
mpicomm
template<int SpaceID> gsmpi::GSMPICart<3>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::mpicomm = CartDataSpace<3, SpaceID>::mpicomm
ps
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ps
Re
template<int SpaceID> Real solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Re
Retau
template<int SpaceID> Real solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::Retau
stagger_flag
template<int SpaceID> std::vector<std::vector<int> >& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::stagger_flag = CartDataSpace<3, SpaceID>::stagger_flag
start_index
template<int SpaceID> std::vector<int>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::start_index = CartDataSpace<3, SpaceID>::start_index
stf
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::stf
stf2w
template<int SpaceID> int solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::stf2w
stp
template<int SpaceID> blin::Vec3i solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::stp
stp2w
template<int SpaceID> int solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::stp2w
tempfields
template<int SpaceID> std::vector<blockelm::CartField<Real, 3> *>& solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::tempfields = CartDataSpace<3, SpaceID>::tempfields
time_scheme
template<int SpaceID> boxfdm::TimeScheme solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::time_scheme
uf
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::uf
us
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::us
utnew
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::utnew
utold
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::utold
vf
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::vf
visc_time_scheme
template<int SpaceID> boxfdm::TimeScheme solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::visc_time_scheme
vs
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::vs
vtnew
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::vtnew
vtold
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::vtold
wf
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::wf
work_path
template<int SpaceID> std::string solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::work_path
wrk
template<int SpaceID> blin::Vec<Field, 5> solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::wrk
ws
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::ws
wtnew
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::wtnew
wtold
template<int SpaceID> Field solver::fluidsol::CartBoxFDMSol< 3, SpaceID >::wtold
The documentation for this class was generated from the following files:
/mnt/e/linuxOS/PhyStar/Solver/FluidSol/FDMSol/CartBoxFDMSol.hpp
/mnt/e/linuxOS/PhyStar/Solver/FluidSol/FDMSol/CartBoxFDMSol.hxx